<?php

namespace App\Domain\TillData\Models;

use App\Domain\Shared\Casts\UtcDateTimeCast;
use App\Domain\Tenancy\Concerns\BelongsToCompany;
use App\Domain\TillData\Casts\TillEnumCast;
use App\Domain\TillData\Concerns\ScopedToBranch;
use App\Domain\TillData\Concerns\TillOwnedRow;
use App\Domain\TillData\Enums\AccountPayDateReminderChannel;
use Carbon\CarbonImmutable;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * Till entity `AccountPayDate`: branch-owned (read-only on the portal), branch scope. Table `account_pay_dates`.
 *
 * @generated by `php artisan till:entities:generate` from
 * docs/contracts/portal-api-v1.4.1/docs/web-portal-api/schemas/entities/AccountPayDate.schema.json and
 * app/Domain/TillData/definitions.php. Do not edit: change the definitions or a hand-written trait and regenerate.
 *
 * @property string $id
 * @property string $company_id
 * @property string|null $branch_id
 * @property string $customer_id
 * @property string $sale_id
 * @property CarbonImmutable $due_at
 * @property string $note
 * @property string $user_id
 * @property CarbonImmutable|null $replaced_at
 * @property CarbonImmutable|null $reminder_sent_at
 * @property AccountPayDateReminderChannel|null $reminder_channel
 * @property int $reminder_attempts
 * @property CarbonImmutable|null $last_reminder_at
 * @property string $last_reminder_error
 * @property int $row_version
 * @property CarbonImmutable|null $created_at
 * @property CarbonImmutable|null $updated_at
 * @property CarbonImmutable|null $deleted_at
 * @property CarbonImmutable|null $synced_at
 * @property int|null $sync_seq
 * @property array<string, mixed>|null $extra
 * @property CarbonImmutable|null $portal_received_at
 */
final class AccountPayDate extends Model
{
    use BelongsToCompany, ScopedToBranch, SoftDeletes, TillOwnedRow;

    public const TILL_ENTITY = 'AccountPayDate';

    public $incrementing = false;

    public $timestamps = false;

    protected $table = 'account_pay_dates';

    protected $keyType = 'string';

    /**
     * @return array<string, string>
     */
    protected function casts(): array
    {
        return [
            'due_at' => UtcDateTimeCast::class,
            'replaced_at' => UtcDateTimeCast::class,
            'reminder_sent_at' => UtcDateTimeCast::class,
            'reminder_channel' => TillEnumCast::class.':'.AccountPayDateReminderChannel::class,
            'reminder_attempts' => 'integer',
            'last_reminder_at' => UtcDateTimeCast::class,
            'row_version' => 'integer',
            'created_at' => UtcDateTimeCast::class,
            'updated_at' => UtcDateTimeCast::class,
            'deleted_at' => UtcDateTimeCast::class,
            'synced_at' => UtcDateTimeCast::class,
            'sync_seq' => 'integer',
            'extra' => 'array',
            'portal_received_at' => UtcDateTimeCast::class,
        ];
    }
}
