<?php

namespace App\Domain\TillData\Models;

use App\Domain\Shared\Casts\UtcDateTimeCast;
use App\Domain\Tenancy\Concerns\BelongsToCompany;
use App\Domain\TillData\Casts\TillEnumCast;
use App\Domain\TillData\Concerns\HubOwnedRow;
use App\Domain\TillData\Enums\AccountType;
use Carbon\CarbonImmutable;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * Till entity `Account`: hub-owned (portal writes, tills apply), company scope. Table `ledger_accounts`.
 *
 * @generated by `php artisan till:entities:generate` from
 * docs/contracts/portal-api-v1.4.1/docs/web-portal-api/schemas/entities/Account.schema.json and
 * app/Domain/TillData/definitions.php. Do not edit: change the definitions or a hand-written trait and regenerate.
 *
 * @property string $id
 * @property string $company_id
 * @property string $code
 * @property string $name
 * @property AccountType|null $type
 * @property string|null $parent_code
 * @property int|null $vat_box
 * @property bool $is_system
 * @property bool $is_active
 * @property bool $is_debit_balance
 * @property int $row_version
 * @property CarbonImmutable|null $created_at
 * @property CarbonImmutable|null $updated_at
 * @property CarbonImmutable|null $deleted_at
 * @property int|null $hub_version
 * @property CarbonImmutable|null $hub_edited_at
 * @property string|null $hub_hash
 * @property string|null $origin_branch_id
 * @property CarbonImmutable|null $synced_at
 * @property int|null $sync_seq
 * @property array<string, mixed>|null $extra
 * @property CarbonImmutable|null $portal_received_at
 */
final class Account extends Model
{
    use BelongsToCompany, HubOwnedRow, SoftDeletes;

    public const TILL_ENTITY = 'Account';

    public $incrementing = false;

    public $timestamps = false;

    protected $table = 'ledger_accounts';

    protected $keyType = 'string';

    /**
     * @return array<string, string>
     */
    protected function casts(): array
    {
        return [
            'type' => TillEnumCast::class.':'.AccountType::class,
            'vat_box' => 'integer',
            'is_system' => 'boolean',
            'is_active' => 'boolean',
            'is_debit_balance' => 'boolean',
            'row_version' => 'integer',
            'created_at' => UtcDateTimeCast::class,
            'updated_at' => UtcDateTimeCast::class,
            'deleted_at' => UtcDateTimeCast::class,
            'hub_version' => 'integer',
            'hub_edited_at' => UtcDateTimeCast::class,
            'synced_at' => UtcDateTimeCast::class,
            'sync_seq' => 'integer',
            'extra' => 'array',
            'portal_received_at' => UtcDateTimeCast::class,
        ];
    }
}
