<?php

namespace App\Domain\TillData\Models;

use App\Domain\Shared\Casts\MoneyCast;
use App\Domain\Shared\Casts\UtcDateTimeCast;
use App\Domain\Tenancy\Concerns\BelongsToCompany;
use App\Domain\TillData\Casts\TillEnumCast;
use App\Domain\TillData\Concerns\ScopedToBranch;
use App\Domain\TillData\Concerns\ScopedToRegister;
use App\Domain\TillData\Concerns\TillOwnedRow;
use App\Domain\TillData\Enums\CardSettlementStatus;
use Carbon\CarbonImmutable;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * Till entity `CardSettlement`: branch-owned (read-only on the portal), register scope. Table `card_settlements`.
 *
 * @generated by `php artisan till:entities:generate` from
 * docs/contracts/portal-api-v1.3.3/docs/web-portal-api/schemas/entities/CardSettlement.schema.json and
 * app/Domain/TillData/definitions.php. Do not edit: change the definitions or a hand-written trait and regenerate.
 *
 * @property string $id
 * @property string $company_id
 * @property string|null $branch_id
 * @property string|null $register_id
 * @property CarbonImmutable $trading_date
 * @property string $provider
 * @property string $reference
 * @property string $batch_reference
 * @property string $terminal_total
 * @property string $pos_total
 * @property string $variance
 * @property string $fees
 * @property int $transaction_count
 * @property CardSettlementStatus|null $status
 * @property string $message
 * @property CarbonImmutable $settled_at
 * @property string $settled_by_user_id
 * @property string $response_json
 * @property int $row_version
 * @property CarbonImmutable|null $created_at
 * @property CarbonImmutable|null $updated_at
 * @property CarbonImmutable|null $deleted_at
 * @property CarbonImmutable|null $synced_at
 * @property int|null $sync_seq
 * @property array<string, mixed>|null $extra
 * @property CarbonImmutable|null $portal_received_at
 */
final class CardSettlement extends Model
{
    use BelongsToCompany, ScopedToBranch, ScopedToRegister, SoftDeletes, TillOwnedRow;

    public const TILL_ENTITY = 'CardSettlement';

    public $incrementing = false;

    public $timestamps = false;

    protected $table = 'card_settlements';

    protected $keyType = 'string';

    /**
     * @return array<string, string>
     */
    protected function casts(): array
    {
        return [
            'trading_date' => 'immutable_date:Y-m-d',
            'terminal_total' => MoneyCast::class,
            'pos_total' => MoneyCast::class,
            'variance' => MoneyCast::class,
            'fees' => MoneyCast::class,
            'transaction_count' => 'integer',
            'status' => TillEnumCast::class.':'.CardSettlementStatus::class,
            'settled_at' => UtcDateTimeCast::class,
            'row_version' => 'integer',
            'created_at' => UtcDateTimeCast::class,
            'updated_at' => UtcDateTimeCast::class,
            'deleted_at' => UtcDateTimeCast::class,
            'synced_at' => UtcDateTimeCast::class,
            'sync_seq' => 'integer',
            'extra' => 'array',
            'portal_received_at' => UtcDateTimeCast::class,
        ];
    }
}
