<?php

namespace App\Domain\TillData\Models;

use App\Domain\Shared\Casts\MoneyCast;
use App\Domain\Shared\Casts\UtcDateTimeCast;
use App\Domain\Tenancy\Concerns\BelongsToCompany;
use App\Domain\TillData\Casts\TillEnumCast;
use App\Domain\TillData\Concerns\ScopedToBranch;
use App\Domain\TillData\Concerns\ScopedToRegister;
use App\Domain\TillData\Concerns\TillOwnedRow;
use App\Domain\TillData\Enums\CashMovementType;
use Carbon\CarbonImmutable;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * Till entity `CashMovement`: branch-owned (read-only on the portal), register scope. Table `cash_movements`.
 *
 * @generated by `php artisan till:entities:generate` from
 * docs/contracts/portal-api-v1.3.3/docs/web-portal-api/schemas/entities/CashMovement.schema.json and
 * app/Domain/TillData/definitions.php. Do not edit: change the definitions or a hand-written trait and regenerate.
 *
 * @property string $id
 * @property string $company_id
 * @property string|null $branch_id
 * @property string|null $register_id
 * @property string $shift_id
 * @property string $user_id
 * @property CashMovementType|null $type
 * @property string $amount
 * @property string $reason_id
 * @property string $note
 * @property CarbonImmutable $at
 * @property int $row_version
 * @property CarbonImmutable|null $created_at
 * @property CarbonImmutable|null $updated_at
 * @property CarbonImmutable|null $deleted_at
 * @property CarbonImmutable|null $synced_at
 * @property int|null $sync_seq
 * @property array<string, mixed>|null $extra
 * @property CarbonImmutable|null $portal_received_at
 */
final class CashMovement extends Model
{
    use BelongsToCompany, ScopedToBranch, ScopedToRegister, SoftDeletes, TillOwnedRow;

    public const TILL_ENTITY = 'CashMovement';

    public $incrementing = false;

    public $timestamps = false;

    protected $table = 'cash_movements';

    protected $keyType = 'string';

    /**
     * @return array<string, string>
     */
    protected function casts(): array
    {
        return [
            'type' => TillEnumCast::class.':'.CashMovementType::class,
            'amount' => MoneyCast::class,
            'at' => UtcDateTimeCast::class,
            'row_version' => 'integer',
            'created_at' => UtcDateTimeCast::class,
            'updated_at' => UtcDateTimeCast::class,
            'deleted_at' => UtcDateTimeCast::class,
            'synced_at' => UtcDateTimeCast::class,
            'sync_seq' => 'integer',
            'extra' => 'array',
            'portal_received_at' => UtcDateTimeCast::class,
        ];
    }
}
