<?php

namespace App\Domain\TillData\Models;

use App\Domain\Shared\Casts\MoneyCast;
use App\Domain\Shared\Casts\UtcDateTimeCast;
use App\Domain\Tenancy\Concerns\BelongsToCompany;
use App\Domain\TillData\Casts\TillEnumCast;
use App\Domain\TillData\Concerns\ScopedToBranch;
use App\Domain\TillData\Concerns\TillOwnedRow;
use App\Domain\TillData\Enums\CashOfficeBankingCollectionMethod;
use App\Domain\TillData\Enums\CashOfficeBankingStatus;
use Carbon\CarbonImmutable;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * Till entity `CashOfficeBanking`: branch-owned (read-only on the portal), branch scope. Table `cash_office_bankings`.
 *
 * @generated by `php artisan till:entities:generate` from
 * docs/contracts/portal-api-v1.4.1/docs/web-portal-api/schemas/entities/CashOfficeBanking.schema.json and
 * app/Domain/TillData/definitions.php. Do not edit: change the definitions or a hand-written trait and regenerate.
 *
 * @property string $id
 * @property string $company_id
 * @property string|null $branch_id
 * @property string $reference
 * @property string $amount
 * @property string $denominations_json
 * @property CashOfficeBankingStatus|null $status
 * @property string $prepared_by_user_id
 * @property CarbonImmutable $prepared_at
 * @property string $banked_by_user_id
 * @property CarbonImmutable|null $banked_at
 * @property string $bank_reference
 * @property string $note
 * @property string $seal_number
 * @property CashOfficeBankingCollectionMethod|null $collection_method
 * @property string $carrier_name
 * @property string $collected_signature_name
 * @property string $collected_by_user_id
 * @property CarbonImmutable|null $collected_at
 * @property string|null $confirmed_amount
 * @property string|null $variance_amount
 * @property int $row_version
 * @property CarbonImmutable|null $created_at
 * @property CarbonImmutable|null $updated_at
 * @property CarbonImmutable|null $deleted_at
 * @property CarbonImmutable|null $synced_at
 * @property int|null $sync_seq
 * @property array<string, mixed>|null $extra
 * @property CarbonImmutable|null $portal_received_at
 */
final class CashOfficeBanking extends Model
{
    use BelongsToCompany, ScopedToBranch, SoftDeletes, TillOwnedRow;

    public const TILL_ENTITY = 'CashOfficeBanking';

    public $incrementing = false;

    public $timestamps = false;

    protected $table = 'cash_office_bankings';

    protected $keyType = 'string';

    /**
     * @return array<string, string>
     */
    protected function casts(): array
    {
        return [
            'amount' => MoneyCast::class,
            'status' => TillEnumCast::class.':'.CashOfficeBankingStatus::class,
            'prepared_at' => UtcDateTimeCast::class,
            'banked_at' => UtcDateTimeCast::class,
            'collection_method' => TillEnumCast::class.':'.CashOfficeBankingCollectionMethod::class,
            'collected_at' => UtcDateTimeCast::class,
            'confirmed_amount' => MoneyCast::class,
            'variance_amount' => MoneyCast::class,
            'row_version' => 'integer',
            'created_at' => UtcDateTimeCast::class,
            'updated_at' => UtcDateTimeCast::class,
            'deleted_at' => UtcDateTimeCast::class,
            'synced_at' => UtcDateTimeCast::class,
            'sync_seq' => 'integer',
            'extra' => 'array',
            'portal_received_at' => UtcDateTimeCast::class,
        ];
    }
}
