<?php

namespace App\Domain\TillData\Models;

use App\Domain\Shared\Casts\QuantityCast;
use App\Domain\Shared\Casts\UtcDateTimeCast;
use App\Domain\Tenancy\Concerns\BelongsToCompany;
use App\Domain\TillData\Casts\TillEnumCast;
use App\Domain\TillData\Concerns\ScopedToBranch;
use App\Domain\TillData\Concerns\TillOwnedRow;
use App\Domain\TillData\Enums\DateCheckAction;
use Carbon\CarbonImmutable;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * Till entity `DateCheck`: branch-owned (read-only on the portal), branch scope. Table `date_checks`.
 *
 * @generated by `php artisan till:entities:generate` from
 * docs/contracts/portal-api-v1.1/schemas/entities/DateCheck.schema.json and
 * app/Domain/TillData/definitions.php. Do not edit: change the definitions or a hand-written trait and regenerate.
 *
 * @property string $id
 * @property string $company_id
 * @property string|null $branch_id
 * @property string $stock_layer_id
 * @property string $product_id
 * @property string $checked_by_user_id
 * @property CarbonImmutable $checked_at
 * @property DateCheckAction|null $action
 * @property string|null $markdown_percent
 * @property string $note
 * @property int $row_version
 * @property CarbonImmutable|null $created_at
 * @property CarbonImmutable|null $updated_at
 * @property CarbonImmutable|null $deleted_at
 * @property CarbonImmutable|null $synced_at
 * @property int|null $sync_seq
 * @property array<string, mixed>|null $extra
 */
final class DateCheck extends Model
{
    use BelongsToCompany, ScopedToBranch, SoftDeletes, TillOwnedRow;

    public const TILL_ENTITY = 'DateCheck';

    public $incrementing = false;

    public $timestamps = false;

    protected $table = 'date_checks';

    protected $keyType = 'string';

    /**
     * @return array<string, string>
     */
    protected function casts(): array
    {
        return [
            'checked_at' => UtcDateTimeCast::class,
            'action' => TillEnumCast::class.':'.DateCheckAction::class,
            'markdown_percent' => QuantityCast::class,
            'row_version' => 'integer',
            'created_at' => UtcDateTimeCast::class,
            'updated_at' => UtcDateTimeCast::class,
            'deleted_at' => UtcDateTimeCast::class,
            'synced_at' => UtcDateTimeCast::class,
            'sync_seq' => 'integer',
            'extra' => 'array',
        ];
    }
}
