<?php

namespace App\Domain\TillData\Models;

use App\Domain\Shared\Casts\UtcDateTimeCast;
use App\Domain\Tenancy\Concerns\BelongsToCompany;
use App\Domain\TillData\Concerns\ScopedToBranch;
use App\Domain\TillData\Concerns\TillOwnedRow;
use Carbon\CarbonImmutable;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * Till entity `DiaryCheckRecord`: branch-owned (read-only on the portal), branch scope, parent DiaryCheckDefinition. Table `diary_check_records`.
 *
 * @generated by `php artisan till:entities:generate` from
 * docs/contracts/portal-api-v1.3.3/docs/web-portal-api/schemas/entities/DiaryCheckRecord.schema.json and
 * app/Domain/TillData/definitions.php. Do not edit: change the definitions or a hand-written trait and regenerate.
 *
 * @property string $id
 * @property string $company_id
 * @property string|null $branch_id
 * @property string $diary_check_definition_id
 * @property CarbonImmutable $recorded_at
 * @property string $recorded_by_user_id
 * @property string $value
 * @property bool $passed
 * @property string $note
 * @property int $row_version
 * @property CarbonImmutable|null $created_at
 * @property CarbonImmutable|null $updated_at
 * @property CarbonImmutable|null $deleted_at
 * @property CarbonImmutable|null $synced_at
 * @property int|null $sync_seq
 * @property array<string, mixed>|null $extra
 * @property CarbonImmutable|null $portal_received_at
 */
final class DiaryCheckRecord extends Model
{
    use BelongsToCompany, ScopedToBranch, SoftDeletes, TillOwnedRow;

    public const TILL_ENTITY = 'DiaryCheckRecord';

    public $incrementing = false;

    public $timestamps = false;

    protected $table = 'diary_check_records';

    protected $keyType = 'string';

    /**
     * @return array<string, string>
     */
    protected function casts(): array
    {
        return [
            'recorded_at' => UtcDateTimeCast::class,
            'passed' => 'boolean',
            'row_version' => 'integer',
            'created_at' => UtcDateTimeCast::class,
            'updated_at' => UtcDateTimeCast::class,
            'deleted_at' => UtcDateTimeCast::class,
            'synced_at' => UtcDateTimeCast::class,
            'sync_seq' => 'integer',
            'extra' => 'array',
            'portal_received_at' => UtcDateTimeCast::class,
        ];
    }

    /**
     * @return BelongsTo<DiaryCheckDefinition, $this>
     */
    public function diaryCheckDefinition(): BelongsTo
    {
        return $this->belongsTo(DiaryCheckDefinition::class, 'diary_check_definition_id');
    }
}
