<?php

namespace App\Domain\TillData\Models;

use App\Domain\Shared\Casts\MoneyCast;
use App\Domain\Shared\Casts\UtcDateTimeCast;
use App\Domain\Tenancy\Concerns\BelongsToCompany;
use App\Domain\TillData\Casts\TillEnumCast;
use App\Domain\TillData\Concerns\ScopedToBranch;
use App\Domain\TillData\Concerns\TillOwnedRow;
use App\Domain\TillData\Enums\DispensingRecordChargeStatus;
use App\Domain\TillData\Enums\DispensingRecordExemption;
use Carbon\CarbonImmutable;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * Till entity `DispensingRecord`: branch-owned (read-only on the portal), branch scope. Table `dispensing_records`.
 *
 * @generated by `php artisan till:entities:generate` from
 * docs/contracts/portal-api-v1.3.1/docs/web-portal-api/schemas/entities/DispensingRecord.schema.json and
 * app/Domain/TillData/definitions.php. Do not edit: change the definitions or a hand-written trait and regenerate.
 *
 * @property string $id
 * @property string $company_id
 * @property string|null $branch_id
 * @property string $patient_customer_id
 * @property string $prescriber_name
 * @property string $prescriber_registration
 * @property CarbonImmutable $prescription_date
 * @property CarbonImmutable $dispensed_at
 * @property string $dispensed_by_user_id
 * @property string $dispensed_by_name
 * @property DispensingRecordChargeStatus|null $charge_status
 * @property DispensingRecordExemption|null $exemption
 * @property string $charge_amount
 * @property string|null $sale_id
 * @property string $notes
 * @property int $row_version
 * @property CarbonImmutable|null $created_at
 * @property CarbonImmutable|null $updated_at
 * @property CarbonImmutable|null $deleted_at
 * @property CarbonImmutable|null $synced_at
 * @property int|null $sync_seq
 * @property array<string, mixed>|null $extra
 * @property CarbonImmutable|null $portal_received_at
 */
final class DispensingRecord extends Model
{
    use BelongsToCompany, ScopedToBranch, SoftDeletes, TillOwnedRow;

    public const TILL_ENTITY = 'DispensingRecord';

    public $incrementing = false;

    public $timestamps = false;

    protected $table = 'dispensing_records';

    protected $keyType = 'string';

    /**
     * @return array<string, string>
     */
    protected function casts(): array
    {
        return [
            'prescription_date' => 'immutable_date:Y-m-d',
            'dispensed_at' => UtcDateTimeCast::class,
            'charge_status' => TillEnumCast::class.':'.DispensingRecordChargeStatus::class,
            'exemption' => TillEnumCast::class.':'.DispensingRecordExemption::class,
            'charge_amount' => MoneyCast::class,
            'row_version' => 'integer',
            'created_at' => UtcDateTimeCast::class,
            'updated_at' => UtcDateTimeCast::class,
            'deleted_at' => UtcDateTimeCast::class,
            'synced_at' => UtcDateTimeCast::class,
            'sync_seq' => 'integer',
            'extra' => 'array',
            'portal_received_at' => UtcDateTimeCast::class,
        ];
    }

    /**
     * @return HasMany<DispensingItem, $this>
     */
    public function dispensingItems(): HasMany
    {
        return $this->hasMany(DispensingItem::class, 'dispensing_record_id');
    }
}
