<?php

namespace App\Domain\TillData\Models;

use App\Domain\Shared\Casts\MoneyCast;
use App\Domain\Shared\Casts\QuantityCast;
use App\Domain\Shared\Casts\UtcDateTimeCast;
use App\Domain\Tenancy\Concerns\BelongsToCompany;
use App\Domain\TillData\Concerns\ScopedToBranch;
use App\Domain\TillData\Concerns\TillOwnedRow;
use Carbon\CarbonImmutable;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * Till entity `FixedAsset`: branch-owned (read-only on the portal), branch scope. Table `fixed_assets`.
 *
 * @generated by `php artisan till:entities:generate` from
 * docs/contracts/portal-api-v1.3.1/docs/web-portal-api/schemas/entities/FixedAsset.schema.json and
 * app/Domain/TillData/definitions.php. Do not edit: change the definitions or a hand-written trait and regenerate.
 *
 * @property string $id
 * @property string $company_id
 * @property string|null $branch_id
 * @property string $name
 * @property string $code
 * @property string $fixed_asset_category_id
 * @property CarbonImmutable $purchase_date
 * @property string $purchase_cost_amount
 * @property string|null $supplier_id
 * @property int|null $useful_life_years
 * @property string|null $depreciation_rate_percent
 * @property string $residual_value_amount
 * @property CarbonImmutable|null $disposal_date
 * @property string|null $disposal_proceeds_amount
 * @property bool $is_active
 * @property string|null $notes
 * @property int $row_version
 * @property CarbonImmutable|null $created_at
 * @property CarbonImmutable|null $updated_at
 * @property CarbonImmutable|null $deleted_at
 * @property CarbonImmutable|null $synced_at
 * @property int|null $sync_seq
 * @property array<string, mixed>|null $extra
 * @property CarbonImmutable|null $portal_received_at
 */
final class FixedAsset extends Model
{
    use BelongsToCompany, ScopedToBranch, SoftDeletes, TillOwnedRow;

    public const TILL_ENTITY = 'FixedAsset';

    public $incrementing = false;

    public $timestamps = false;

    protected $table = 'fixed_assets';

    protected $keyType = 'string';

    /**
     * @return array<string, string>
     */
    protected function casts(): array
    {
        return [
            'purchase_date' => 'immutable_date:Y-m-d',
            'purchase_cost_amount' => MoneyCast::class,
            'useful_life_years' => 'integer',
            'depreciation_rate_percent' => QuantityCast::class,
            'residual_value_amount' => MoneyCast::class,
            'disposal_date' => 'immutable_date:Y-m-d',
            'disposal_proceeds_amount' => MoneyCast::class,
            'is_active' => 'boolean',
            'row_version' => 'integer',
            'created_at' => UtcDateTimeCast::class,
            'updated_at' => UtcDateTimeCast::class,
            'deleted_at' => UtcDateTimeCast::class,
            'synced_at' => UtcDateTimeCast::class,
            'sync_seq' => 'integer',
            'extra' => 'array',
            'portal_received_at' => UtcDateTimeCast::class,
        ];
    }
}
