<?php

namespace App\Domain\TillData\Models;

use App\Domain\Shared\Casts\QuantityCast;
use App\Domain\Shared\Casts\UtcDateTimeCast;
use App\Domain\Tenancy\Concerns\BelongsToCompany;
use App\Domain\TillData\Concerns\ScopedToBranch;
use App\Domain\TillData\Concerns\TillOwnedRow;
use Carbon\CarbonImmutable;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * Till entity `GoodsReceiptLine`: branch-owned (read-only on the portal), child scope, parent GoodsReceipt. Table `goods_receipt_lines`.
 *
 * @generated by `php artisan till:entities:generate` from
 * docs/contracts/portal-api-v1.1/schemas/entities/GoodsReceiptLine.schema.json and
 * app/Domain/TillData/definitions.php. Do not edit: change the definitions or a hand-written trait and regenerate.
 *
 * @property string $id
 * @property string $company_id
 * @property string|null $branch_id
 * @property string $goods_receipt_id
 * @property string|null $purchase_order_line_id
 * @property string $product_id
 * @property string|null $expected_product_id
 * @property string $expected_qty
 * @property string $received_qty
 * @property int $case_qty
 * @property string $unit_cost
 * @property string|null $vat_rate_id
 * @property string $vat_percentage
 * @property bool $is_short_or_over
 * @property string $note
 * @property CarbonImmutable|null $expiry_date
 * @property string|null $batch_no
 * @property int $row_version
 * @property CarbonImmutable|null $created_at
 * @property CarbonImmutable|null $updated_at
 * @property CarbonImmutable|null $deleted_at
 * @property CarbonImmutable|null $synced_at
 * @property int|null $sync_seq
 * @property array<string, mixed>|null $extra
 */
final class GoodsReceiptLine extends Model
{
    use BelongsToCompany, ScopedToBranch, SoftDeletes, TillOwnedRow;

    public const TILL_ENTITY = 'GoodsReceiptLine';

    public $incrementing = false;

    public $timestamps = false;

    protected $table = 'goods_receipt_lines';

    protected $keyType = 'string';

    /**
     * @return array<string, string>
     */
    protected function casts(): array
    {
        return [
            'expected_qty' => QuantityCast::class,
            'received_qty' => QuantityCast::class,
            'case_qty' => 'integer',
            'unit_cost' => QuantityCast::class,
            'vat_percentage' => QuantityCast::class,
            'is_short_or_over' => 'boolean',
            'expiry_date' => 'immutable_date:Y-m-d',
            'row_version' => 'integer',
            'created_at' => UtcDateTimeCast::class,
            'updated_at' => UtcDateTimeCast::class,
            'deleted_at' => UtcDateTimeCast::class,
            'synced_at' => UtcDateTimeCast::class,
            'sync_seq' => 'integer',
            'extra' => 'array',
        ];
    }

    /**
     * @return BelongsTo<GoodsReceipt, $this>
     */
    public function goodsReceipt(): BelongsTo
    {
        return $this->belongsTo(GoodsReceipt::class, 'goods_receipt_id');
    }
}
