<?php

namespace App\Domain\TillData\Models;

use App\Domain\Shared\Casts\UtcDateTimeCast;
use App\Domain\Tenancy\Concerns\BelongsToCompany;
use App\Domain\TillData\Casts\TillEnumCast;
use App\Domain\TillData\Concerns\ScopedToBranch;
use App\Domain\TillData\Concerns\ScopedToRegister;
use App\Domain\TillData\Concerns\TillOwnedRow;
use App\Domain\TillData\Enums\HardwareCheckKind;
use App\Domain\TillData\Enums\HardwareCheckResult;
use Carbon\CarbonImmutable;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * Till entity `HardwareCheck`: branch-owned (read-only on the portal), register scope. Table `hardware_checks`.
 *
 * @generated by `php artisan till:entities:generate` from
 * docs/contracts/portal-api-v1.1/schemas/entities/HardwareCheck.schema.json and
 * app/Domain/TillData/definitions.php. Do not edit: change the definitions or a hand-written trait and regenerate.
 *
 * @property string $id
 * @property string $company_id
 * @property string|null $branch_id
 * @property string|null $register_id
 * @property HardwareCheckKind|null $kind
 * @property HardwareCheckResult|null $result
 * @property string $adapter
 * @property string $port
 * @property string $evidence
 * @property string $instruction
 * @property int $elapsed_ms
 * @property CarbonImmutable $at
 * @property string $user_id
 * @property string $user_name
 * @property string $confirms_check_id
 * @property string $notes
 * @property int $row_version
 * @property CarbonImmutable|null $created_at
 * @property CarbonImmutable|null $updated_at
 * @property CarbonImmutable|null $deleted_at
 * @property CarbonImmutable|null $synced_at
 * @property int|null $sync_seq
 * @property array<string, mixed>|null $extra
 */
final class HardwareCheck extends Model
{
    use BelongsToCompany, ScopedToBranch, ScopedToRegister, SoftDeletes, TillOwnedRow;

    public const TILL_ENTITY = 'HardwareCheck';

    public $incrementing = false;

    public $timestamps = false;

    protected $table = 'hardware_checks';

    protected $keyType = 'string';

    /**
     * @return array<string, string>
     */
    protected function casts(): array
    {
        return [
            'kind' => TillEnumCast::class.':'.HardwareCheckKind::class,
            'result' => TillEnumCast::class.':'.HardwareCheckResult::class,
            'elapsed_ms' => 'integer',
            'at' => UtcDateTimeCast::class,
            'row_version' => 'integer',
            'created_at' => UtcDateTimeCast::class,
            'updated_at' => UtcDateTimeCast::class,
            'deleted_at' => UtcDateTimeCast::class,
            'synced_at' => UtcDateTimeCast::class,
            'sync_seq' => 'integer',
            'extra' => 'array',
        ];
    }
}
