<?php

namespace App\Domain\TillData\Models;

use App\Domain\Shared\Casts\UtcDateTimeCast;
use App\Domain\Tenancy\Concerns\BelongsToCompany;
use App\Domain\TillData\Concerns\ScopedToBranch;
use App\Domain\TillData\Concerns\TillOwnedRow;
use Carbon\CarbonImmutable;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * Till entity `OfflineCardReconciliation`: branch-owned (read-only on the portal), branch scope. Table `offline_card_reconciliations`.
 *
 * @generated by `php artisan till:entities:generate` from
 * docs/contracts/portal-api-v1.1/schemas/entities/OfflineCardReconciliation.schema.json and
 * app/Domain/TillData/definitions.php. Do not edit: change the definitions or a hand-written trait and regenerate.
 *
 * @property string $id
 * @property string $company_id
 * @property string|null $branch_id
 * @property string $sale_payment_id
 * @property string $sale_id
 * @property CarbonImmutable $reconciled_at
 * @property string $reconciled_by_user_id
 * @property string $reconciled_by_name
 * @property int $row_version
 * @property CarbonImmutable|null $created_at
 * @property CarbonImmutable|null $updated_at
 * @property CarbonImmutable|null $deleted_at
 * @property CarbonImmutable|null $synced_at
 * @property int|null $sync_seq
 * @property array<string, mixed>|null $extra
 */
final class OfflineCardReconciliation extends Model
{
    use BelongsToCompany, ScopedToBranch, SoftDeletes, TillOwnedRow;

    public const TILL_ENTITY = 'OfflineCardReconciliation';

    public $incrementing = false;

    public $timestamps = false;

    protected $table = 'offline_card_reconciliations';

    protected $keyType = 'string';

    /**
     * @return array<string, string>
     */
    protected function casts(): array
    {
        return [
            'reconciled_at' => UtcDateTimeCast::class,
            'row_version' => 'integer',
            'created_at' => UtcDateTimeCast::class,
            'updated_at' => UtcDateTimeCast::class,
            'deleted_at' => UtcDateTimeCast::class,
            'synced_at' => UtcDateTimeCast::class,
            'sync_seq' => 'integer',
            'extra' => 'array',
        ];
    }
}
