<?php

namespace App\Domain\TillData\Models;

use App\Domain\Shared\Casts\MoneyCast;
use App\Domain\Shared\Casts\UtcDateTimeCast;
use App\Domain\Tenancy\Concerns\BelongsToCompany;
use App\Domain\TillData\Casts\TillEnumCast;
use App\Domain\TillData\Concerns\ScopedToBranch;
use App\Domain\TillData\Concerns\ScopedToRegister;
use App\Domain\TillData\Concerns\TillOwnedRow;
use App\Domain\TillData\Enums\PaymentAttemptStatus;
use Carbon\CarbonImmutable;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * Till entity `PaymentAttempt`: branch-owned (read-only on the portal), register scope. Table `payment_attempts`.
 *
 * @generated by `php artisan till:entities:generate` from
 * docs/contracts/portal-api-v1.4.1/docs/web-portal-api/schemas/entities/PaymentAttempt.schema.json and
 * app/Domain/TillData/definitions.php. Do not edit: change the definitions or a hand-written trait and regenerate.
 *
 * @property string $id
 * @property string $company_id
 * @property string|null $branch_id
 * @property string|null $register_id
 * @property string $sale_id
 * @property string $provider
 * @property string $amount
 * @property string $cashback
 * @property PaymentAttemptStatus|null $status
 * @property string $terminal_txn_id
 * @property string $provider_ref
 * @property string $auth_code
 * @property string $scheme
 * @property string $last4
 * @property string $entry_mode
 * @property string $response_json
 * @property string $idempotency_key
 * @property string $user_id
 * @property CarbonImmutable $at
 * @property string $uti
 * @property string $reference
 * @property string $transport_mode
 * @property string $requested_amount
 * @property bool $is_refund
 * @property string|null $original_attempt_id
 * @property string $decline_reason
 * @property string $resolution_reason
 * @property int $receipt_print_count
 * @property CarbonImmutable|null $last_receipt_printed_at
 * @property string $last_receipt_printed_by
 * @property string $asked_amount
 * @property bool $needs_recovery
 * @property bool $is_approved
 * @property int $row_version
 * @property CarbonImmutable|null $created_at
 * @property CarbonImmutable|null $updated_at
 * @property CarbonImmutable|null $deleted_at
 * @property CarbonImmutable|null $synced_at
 * @property int|null $sync_seq
 * @property array<string, mixed>|null $extra
 * @property CarbonImmutable|null $portal_received_at
 */
final class PaymentAttempt extends Model
{
    use BelongsToCompany, ScopedToBranch, ScopedToRegister, SoftDeletes, TillOwnedRow;

    public const TILL_ENTITY = 'PaymentAttempt';

    public $incrementing = false;

    public $timestamps = false;

    protected $table = 'payment_attempts';

    protected $keyType = 'string';

    /**
     * @return array<string, string>
     */
    protected function casts(): array
    {
        return [
            'amount' => MoneyCast::class,
            'cashback' => MoneyCast::class,
            'status' => TillEnumCast::class.':'.PaymentAttemptStatus::class,
            'at' => UtcDateTimeCast::class,
            'requested_amount' => MoneyCast::class,
            'is_refund' => 'boolean',
            'receipt_print_count' => 'integer',
            'last_receipt_printed_at' => UtcDateTimeCast::class,
            'asked_amount' => MoneyCast::class,
            'needs_recovery' => 'boolean',
            'is_approved' => 'boolean',
            'row_version' => 'integer',
            'created_at' => UtcDateTimeCast::class,
            'updated_at' => UtcDateTimeCast::class,
            'deleted_at' => UtcDateTimeCast::class,
            'synced_at' => UtcDateTimeCast::class,
            'sync_seq' => 'integer',
            'extra' => 'array',
            'portal_received_at' => UtcDateTimeCast::class,
        ];
    }
}
