<?php

namespace App\Domain\TillData\Models;

use App\Domain\Shared\Casts\UtcDateTimeCast;
use App\Domain\Tenancy\Concerns\BelongsToCompany;
use App\Domain\TillData\Concerns\HubOwnedRow;
use Carbon\CarbonImmutable;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * Till entity `PaymentType`: hub-owned (portal writes, tills apply), company scope. Table `payment_types`.
 *
 * @generated by `php artisan till:entities:generate` from
 * docs/contracts/portal-api-v1.3.3/docs/web-portal-api/schemas/entities/PaymentType.schema.json and
 * app/Domain/TillData/definitions.php. Do not edit: change the definitions or a hand-written trait and regenerate.
 *
 * @property string $id
 * @property string $company_id
 * @property string $name
 * @property int $position
 * @property bool $is_cash
 * @property bool $is_card
 * @property bool $is_voucher
 * @property bool $is_points
 * @property bool $is_account
 * @property bool $is_drs_refund
 * @property bool $opens_drawer
 * @property bool $show_on_payment
 * @property bool $show_on_refund
 * @property bool $show_on_customer_payment
 * @property bool $is_active
 * @property int $row_version
 * @property CarbonImmutable|null $created_at
 * @property CarbonImmutable|null $updated_at
 * @property CarbonImmutable|null $deleted_at
 * @property int|null $hub_version
 * @property CarbonImmutable|null $hub_edited_at
 * @property string|null $hub_hash
 * @property string|null $origin_branch_id
 * @property CarbonImmutable|null $synced_at
 * @property int|null $sync_seq
 * @property array<string, mixed>|null $extra
 * @property CarbonImmutable|null $portal_received_at
 */
final class PaymentType extends Model
{
    use BelongsToCompany, HubOwnedRow, SoftDeletes;

    public const TILL_ENTITY = 'PaymentType';

    public $incrementing = false;

    public $timestamps = false;

    protected $table = 'payment_types';

    protected $keyType = 'string';

    /**
     * @return array<string, string>
     */
    protected function casts(): array
    {
        return [
            'position' => 'integer',
            'is_cash' => 'boolean',
            'is_card' => 'boolean',
            'is_voucher' => 'boolean',
            'is_points' => 'boolean',
            'is_account' => 'boolean',
            'is_drs_refund' => 'boolean',
            'opens_drawer' => 'boolean',
            'show_on_payment' => 'boolean',
            'show_on_refund' => 'boolean',
            'show_on_customer_payment' => 'boolean',
            'is_active' => 'boolean',
            'row_version' => 'integer',
            'created_at' => UtcDateTimeCast::class,
            'updated_at' => UtcDateTimeCast::class,
            'deleted_at' => UtcDateTimeCast::class,
            'hub_version' => 'integer',
            'hub_edited_at' => UtcDateTimeCast::class,
            'synced_at' => UtcDateTimeCast::class,
            'sync_seq' => 'integer',
            'extra' => 'array',
            'portal_received_at' => UtcDateTimeCast::class,
        ];
    }
}
