<?php

namespace App\Domain\TillData\Models;

use App\Domain\Shared\Casts\MoneyCast;
use App\Domain\Shared\Casts\QuantityCast;
use App\Domain\Shared\Casts\UtcDateTimeCast;
use App\Domain\Tenancy\Concerns\BelongsToCompany;
use App\Domain\TillData\Casts\TillEnumCast;
use App\Domain\TillData\Concerns\ScopedToBranch;
use App\Domain\TillData\Concerns\TillOwnedRow;
use App\Domain\TillData\Enums\PriceChangeLineStatus;
use App\Domain\TillData\Enums\PriceLevel;
use Carbon\CarbonImmutable;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * Till entity `PriceChangeLine`: branch-owned (read-only on the portal), child scope, parent PriceChangeBatch. Table `price_change_lines`.
 *
 * @generated by `php artisan till:entities:generate` from
 * docs/contracts/portal-api-v1.1/schemas/entities/PriceChangeLine.schema.json and
 * app/Domain/TillData/definitions.php. Do not edit: change the definitions or a hand-written trait and regenerate.
 *
 * @property string $id
 * @property string $company_id
 * @property string|null $branch_id
 * @property string $batch_id
 * @property string $product_id
 * @property string|null $price_branch_id
 * @property PriceLevel|null $level
 * @property string $product_name
 * @property string $old_price
 * @property string $new_price
 * @property string $cost_price
 * @property PriceChangeLineStatus|null $status
 * @property string $note
 * @property bool $label_printed
 * @property CarbonImmutable|null $label_printed_at
 * @property string|null $change_percent
 * @property bool $awaits_label
 * @property int $row_version
 * @property CarbonImmutable|null $created_at
 * @property CarbonImmutable|null $updated_at
 * @property CarbonImmutable|null $deleted_at
 * @property CarbonImmutable|null $synced_at
 * @property int|null $sync_seq
 * @property array<string, mixed>|null $extra
 */
final class PriceChangeLine extends Model
{
    use BelongsToCompany, ScopedToBranch, SoftDeletes, TillOwnedRow;

    public const TILL_ENTITY = 'PriceChangeLine';

    public $incrementing = false;

    public $timestamps = false;

    protected $table = 'price_change_lines';

    protected $keyType = 'string';

    /**
     * @return array<string, string>
     */
    protected function casts(): array
    {
        return [
            'level' => TillEnumCast::class.':'.PriceLevel::class,
            'old_price' => MoneyCast::class,
            'new_price' => MoneyCast::class,
            'cost_price' => QuantityCast::class,
            'status' => TillEnumCast::class.':'.PriceChangeLineStatus::class,
            'label_printed' => 'boolean',
            'label_printed_at' => UtcDateTimeCast::class,
            'change_percent' => QuantityCast::class,
            'awaits_label' => 'boolean',
            'row_version' => 'integer',
            'created_at' => UtcDateTimeCast::class,
            'updated_at' => UtcDateTimeCast::class,
            'deleted_at' => UtcDateTimeCast::class,
            'synced_at' => UtcDateTimeCast::class,
            'sync_seq' => 'integer',
            'extra' => 'array',
        ];
    }

    /**
     * @return BelongsTo<PriceChangeBatch, $this>
     */
    public function priceChangeBatch(): BelongsTo
    {
        return $this->belongsTo(PriceChangeBatch::class, 'batch_id');
    }
}
