<?php

namespace App\Domain\TillData\Models;

use App\Domain\Shared\Casts\UtcDateTimeCast;
use App\Domain\Tenancy\Concerns\BelongsToCompany;
use App\Domain\TillData\Casts\TillEnumCast;
use App\Domain\TillData\Concerns\ScopedToBranch;
use App\Domain\TillData\Concerns\TillOwnedRow;
use App\Domain\TillData\Enums\PriceChangeBatchStatus;
use Carbon\CarbonImmutable;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * Till entity `PriceChangeBatch`: branch-owned (read-only on the portal), branch scope. Table `price_change_batches`.
 *
 * @generated by `php artisan till:entities:generate` from
 * docs/contracts/portal-api-v1.3.3/docs/web-portal-api/schemas/entities/PriceChangeBatch.schema.json and
 * app/Domain/TillData/definitions.php. Do not edit: change the definitions or a hand-written trait and regenerate.
 *
 * @property string $id
 * @property string $company_id
 * @property string|null $branch_id
 * @property string $reference
 * @property string $name
 * @property PriceChangeBatchStatus|null $status
 * @property CarbonImmutable|null $effective_at
 * @property string $reason
 * @property string $source
 * @property string $created_by_user_id
 * @property string $approved_by_user_id
 * @property string $approval_override_user_id
 * @property CarbonImmutable|null $approved_at
 * @property string $went_live_by_user_id
 * @property CarbonImmutable|null $went_live_at
 * @property string $cancelled_by_user_id
 * @property CarbonImmutable|null $cancelled_at
 * @property string $cancel_reason
 * @property int $row_version
 * @property CarbonImmutable|null $created_at
 * @property CarbonImmutable|null $updated_at
 * @property CarbonImmutable|null $deleted_at
 * @property CarbonImmutable|null $synced_at
 * @property int|null $sync_seq
 * @property array<string, mixed>|null $extra
 * @property CarbonImmutable|null $portal_received_at
 */
final class PriceChangeBatch extends Model
{
    use BelongsToCompany, ScopedToBranch, SoftDeletes, TillOwnedRow;

    public const TILL_ENTITY = 'PriceChangeBatch';

    public $incrementing = false;

    public $timestamps = false;

    protected $table = 'price_change_batches';

    protected $keyType = 'string';

    /**
     * @return array<string, string>
     */
    protected function casts(): array
    {
        return [
            'status' => TillEnumCast::class.':'.PriceChangeBatchStatus::class,
            'effective_at' => UtcDateTimeCast::class,
            'approved_at' => UtcDateTimeCast::class,
            'went_live_at' => UtcDateTimeCast::class,
            'cancelled_at' => UtcDateTimeCast::class,
            'row_version' => 'integer',
            'created_at' => UtcDateTimeCast::class,
            'updated_at' => UtcDateTimeCast::class,
            'deleted_at' => UtcDateTimeCast::class,
            'synced_at' => UtcDateTimeCast::class,
            'sync_seq' => 'integer',
            'extra' => 'array',
            'portal_received_at' => UtcDateTimeCast::class,
        ];
    }

    /**
     * @return HasMany<PriceChangeLine, $this>
     */
    public function priceChangeLines(): HasMany
    {
        return $this->hasMany(PriceChangeLine::class, 'batch_id');
    }
}
