<?php

namespace App\Domain\TillData\Models;

use App\Domain\Shared\Casts\UtcDateTimeCast;
use App\Domain\Tenancy\Concerns\BelongsToCompany;
use App\Domain\TillData\Casts\TillEnumCast;
use App\Domain\TillData\Concerns\ScopedToBranch;
use App\Domain\TillData\Concerns\TillOwnedRow;
use App\Domain\TillData\Enums\PrinterProfileRole;
use App\Domain\TillData\Enums\PrinterProfileTransport;
use Carbon\CarbonImmutable;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * Till entity `PrinterProfile`: branch-owned (read-only on the portal), branch scope. Table `printer_profiles`.
 *
 * @generated by `php artisan till:entities:generate` from
 * docs/contracts/portal-api-v1.4.1/docs/web-portal-api/schemas/entities/PrinterProfile.schema.json and
 * app/Domain/TillData/definitions.php. Do not edit: change the definitions or a hand-written trait and regenerate.
 *
 * @property string $id
 * @property string $company_id
 * @property string|null $branch_id
 * @property string $name
 * @property PrinterProfileRole|null $role
 * @property string $driver_key
 * @property PrinterProfileTransport|null $transport
 * @property string $address
 * @property int $port
 * @property int $paper_width_mm
 * @property int $chars_per_line
 * @property bool $has_cutter
 * @property bool $has_drawer_kick
 * @property int $drawer_kick_pin
 * @property int $code_page
 * @property string $logo_path
 * @property bool $is_default
 * @property int $row_version
 * @property CarbonImmutable|null $created_at
 * @property CarbonImmutable|null $updated_at
 * @property CarbonImmutable|null $deleted_at
 * @property CarbonImmutable|null $synced_at
 * @property int|null $sync_seq
 * @property array<string, mixed>|null $extra
 * @property CarbonImmutable|null $portal_received_at
 */
final class PrinterProfile extends Model
{
    use BelongsToCompany, ScopedToBranch, SoftDeletes, TillOwnedRow;

    public const TILL_ENTITY = 'PrinterProfile';

    public $incrementing = false;

    public $timestamps = false;

    protected $table = 'printer_profiles';

    protected $keyType = 'string';

    /**
     * @return array<string, string>
     */
    protected function casts(): array
    {
        return [
            'role' => TillEnumCast::class.':'.PrinterProfileRole::class,
            'transport' => TillEnumCast::class.':'.PrinterProfileTransport::class,
            'port' => 'integer',
            'paper_width_mm' => 'integer',
            'chars_per_line' => 'integer',
            'has_cutter' => 'boolean',
            'has_drawer_kick' => 'boolean',
            'drawer_kick_pin' => 'integer',
            'code_page' => 'integer',
            'is_default' => 'boolean',
            'row_version' => 'integer',
            'created_at' => UtcDateTimeCast::class,
            'updated_at' => UtcDateTimeCast::class,
            'deleted_at' => UtcDateTimeCast::class,
            'synced_at' => UtcDateTimeCast::class,
            'sync_seq' => 'integer',
            'extra' => 'array',
            'portal_received_at' => UtcDateTimeCast::class,
        ];
    }
}
