<?php

namespace App\Domain\TillData\Models;

use App\Domain\Shared\Casts\MoneyCast;
use App\Domain\Shared\Casts\QuantityCast;
use App\Domain\Shared\Casts\UtcDateTimeCast;
use App\Domain\Tenancy\Concerns\BelongsToCompany;
use App\Domain\TillData\Casts\TillEnumCast;
use App\Domain\TillData\Concerns\HubOwnedRow;
use App\Domain\TillData\Enums\AgeRule;
use App\Domain\TillData\Enums\NegativeStockPolicy;
use App\Domain\TillData\Enums\UnitType;
use Carbon\CarbonImmutable;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * Till entity `Product`: hub-owned (portal writes, tills apply), company scope. Table `products`.
 *
 * @generated by `php artisan till:entities:generate` from
 * docs/contracts/portal-api-v1.3.1/docs/web-portal-api/schemas/entities/Product.schema.json and
 * app/Domain/TillData/definitions.php. Do not edit: change the definitions or a hand-written trait and regenerate.
 *
 * @property string $id
 * @property string $company_id
 * @property string $name
 * @property string $short_name
 * @property string|null $sku
 * @property string|null $brand
 * @property string|null $description
 * @property string $department_id
 * @property string $category_id
 * @property string|null $sub_category_id
 * @property string|null $parent_product_id
 * @property string|null $variant_label
 * @property UnitType|null $unit_type
 * @property string $unit_code
 * @property string $vat_rate_id
 * @property string $cost_price
 * @property string $sell_price
 * @property string|null $trade_price
 * @property string|null $pmp_price
 * @property bool $track_stock
 * @property string|null $min_stock_qty
 * @property string|null $max_stock_qty
 * @property string|null $reorder_qty
 * @property NegativeStockPolicy|null $negative_stock_mode
 * @property string|null $bin_location
 * @property AgeRule|null $age_rule
 * @property int|null $max_qty_per_sale
 * @property string|null $max_qty_reason
 * @property string|null $availability_from
 * @property string|null $availability_to
 * @property string|null $availability_seasonal_event_id
 * @property bool $tracks_expiry_dates
 * @property CarbonImmutable|null $nearest_expiry_date
 * @property bool $is_hfss
 * @property bool $is_deposit_item
 * @property string|null $deposit_amount
 * @property bool $is_alcohol
 * @property string|null $abv_percent
 * @property string|null $volume_ml
 * @property bool $is_tobacco
 * @property bool $is_lottery
 * @property bool $is_knife
 * @property bool $is_banned
 * @property bool $vape_duty_applies
 * @property string|null $commodity_code
 * @property string|null $net_mass_kg
 * @property string $tile_colour_hex
 * @property string|null $image_path
 * @property string|null $tile_emoji
 * @property int $tile_position
 * @property bool $is_active
 * @property CarbonImmutable|null $archived_at
 * @property string|null $merged_into_product_id
 * @property bool $is_variant_parent
 * @property string|null $variant1_name
 * @property string|null $variant1_value
 * @property string|null $variant2_name
 * @property string|null $variant2_value
 * @property string|null $variant3_name
 * @property string|null $variant3_value
 * @property string|null $variant4_name
 * @property string|null $variant4_value
 * @property bool $is_variant
 * @property bool $is_weighed
 * @property bool $is_open_price
 * @property bool $is_age_restricted
 * @property string|null $receipt_name
 * @property int $row_version
 * @property CarbonImmutable|null $created_at
 * @property CarbonImmutable|null $updated_at
 * @property CarbonImmutable|null $deleted_at
 * @property int|null $hub_version
 * @property CarbonImmutable|null $hub_edited_at
 * @property string|null $hub_hash
 * @property string|null $origin_branch_id
 * @property CarbonImmutable|null $synced_at
 * @property int|null $sync_seq
 * @property array<string, mixed>|null $extra
 * @property CarbonImmutable|null $portal_received_at
 */
final class Product extends Model
{
    use BelongsToCompany, HubOwnedRow, SoftDeletes;

    public const TILL_ENTITY = 'Product';

    public $incrementing = false;

    public $timestamps = false;

    protected $table = 'products';

    protected $keyType = 'string';

    /**
     * @return array<string, string>
     */
    protected function casts(): array
    {
        return [
            'unit_type' => TillEnumCast::class.':'.UnitType::class,
            'cost_price' => QuantityCast::class,
            'sell_price' => MoneyCast::class,
            'trade_price' => MoneyCast::class,
            'pmp_price' => MoneyCast::class,
            'track_stock' => 'boolean',
            'min_stock_qty' => QuantityCast::class,
            'max_stock_qty' => QuantityCast::class,
            'reorder_qty' => QuantityCast::class,
            'negative_stock_mode' => TillEnumCast::class.':'.NegativeStockPolicy::class,
            'age_rule' => TillEnumCast::class.':'.AgeRule::class,
            'max_qty_per_sale' => 'integer',
            'tracks_expiry_dates' => 'boolean',
            'nearest_expiry_date' => 'immutable_date:Y-m-d',
            'is_hfss' => 'boolean',
            'is_deposit_item' => 'boolean',
            'deposit_amount' => MoneyCast::class,
            'is_alcohol' => 'boolean',
            'abv_percent' => QuantityCast::class,
            'volume_ml' => QuantityCast::class,
            'is_tobacco' => 'boolean',
            'is_lottery' => 'boolean',
            'is_knife' => 'boolean',
            'is_banned' => 'boolean',
            'vape_duty_applies' => 'boolean',
            'net_mass_kg' => QuantityCast::class,
            'tile_position' => 'integer',
            'is_active' => 'boolean',
            'archived_at' => UtcDateTimeCast::class,
            'is_variant_parent' => 'boolean',
            'is_variant' => 'boolean',
            'is_weighed' => 'boolean',
            'is_open_price' => 'boolean',
            'is_age_restricted' => 'boolean',
            'row_version' => 'integer',
            'created_at' => UtcDateTimeCast::class,
            'updated_at' => UtcDateTimeCast::class,
            'deleted_at' => UtcDateTimeCast::class,
            'hub_version' => 'integer',
            'hub_edited_at' => UtcDateTimeCast::class,
            'synced_at' => UtcDateTimeCast::class,
            'sync_seq' => 'integer',
            'extra' => 'array',
            'portal_received_at' => UtcDateTimeCast::class,
        ];
    }

    /**
     * @return HasMany<MedicineClassification, $this>
     */
    public function medicineClassifications(): HasMany
    {
        return $this->hasMany(MedicineClassification::class, 'product_id');
    }

    /**
     * @return HasMany<ProductAlias, $this>
     */
    public function productAliases(): HasMany
    {
        return $this->hasMany(ProductAlias::class, 'product_id');
    }

    /**
     * @return HasMany<ProductBarcode, $this>
     */
    public function productBarcodes(): HasMany
    {
        return $this->hasMany(ProductBarcode::class, 'product_id');
    }

    /**
     * @return HasMany<ProductSupplier, $this>
     */
    public function productSuppliers(): HasMany
    {
        return $this->hasMany(ProductSupplier::class, 'product_id');
    }

    /**
     * @return HasMany<ProductUnit, $this>
     */
    public function productUnits(): HasMany
    {
        return $this->hasMany(ProductUnit::class, 'product_id');
    }
}
