<?php

namespace App\Domain\TillData\Models;

use App\Domain\Shared\Casts\QuantityCast;
use App\Domain\Shared\Casts\UtcDateTimeCast;
use App\Domain\Tenancy\Concerns\BelongsToCompany;
use App\Domain\TillData\Concerns\ScopedToBranch;
use App\Domain\TillData\Concerns\TillOwnedRow;
use Carbon\CarbonImmutable;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * Till entity `PurchaseOrderLine`: branch-owned (read-only on the portal), child scope, parent PurchaseOrder. Table `purchase_order_lines`.
 *
 * @generated by `php artisan till:entities:generate` from
 * docs/contracts/portal-api-v1.4.1/docs/web-portal-api/schemas/entities/PurchaseOrderLine.schema.json and
 * app/Domain/TillData/definitions.php. Do not edit: change the definitions or a hand-written trait and regenerate.
 *
 * @property string $id
 * @property string $company_id
 * @property string|null $branch_id
 * @property string $purchase_order_id
 * @property string $product_id
 * @property int $position
 * @property int $ordered_cases
 * @property int $case_qty_snapshot
 * @property string $ordered_units
 * @property string $unit_cost_snapshot
 * @property string $received_qty
 * @property string $vat_rate_id
 * @property string $vat_percentage
 * @property int $row_version
 * @property CarbonImmutable|null $created_at
 * @property CarbonImmutable|null $updated_at
 * @property CarbonImmutable|null $deleted_at
 * @property CarbonImmutable|null $synced_at
 * @property int|null $sync_seq
 * @property array<string, mixed>|null $extra
 * @property CarbonImmutable|null $portal_received_at
 */
final class PurchaseOrderLine extends Model
{
    use BelongsToCompany, ScopedToBranch, SoftDeletes, TillOwnedRow;

    public const TILL_ENTITY = 'PurchaseOrderLine';

    public $incrementing = false;

    public $timestamps = false;

    protected $table = 'purchase_order_lines';

    protected $keyType = 'string';

    /**
     * @return array<string, string>
     */
    protected function casts(): array
    {
        return [
            'position' => 'integer',
            'ordered_cases' => 'integer',
            'case_qty_snapshot' => 'integer',
            'ordered_units' => QuantityCast::class,
            'unit_cost_snapshot' => QuantityCast::class,
            'received_qty' => QuantityCast::class,
            'vat_percentage' => QuantityCast::class,
            'row_version' => 'integer',
            'created_at' => UtcDateTimeCast::class,
            'updated_at' => UtcDateTimeCast::class,
            'deleted_at' => UtcDateTimeCast::class,
            'synced_at' => UtcDateTimeCast::class,
            'sync_seq' => 'integer',
            'extra' => 'array',
            'portal_received_at' => UtcDateTimeCast::class,
        ];
    }

    /**
     * @return BelongsTo<PurchaseOrder, $this>
     */
    public function purchaseOrder(): BelongsTo
    {
        return $this->belongsTo(PurchaseOrder::class, 'purchase_order_id');
    }
}
