<?php

namespace App\Domain\TillData\Models;

use App\Domain\Shared\Casts\MoneyCast;
use App\Domain\Shared\Casts\QuantityCast;
use App\Domain\Shared\Casts\UtcDateTimeCast;
use App\Domain\Tenancy\Concerns\BelongsToCompany;
use App\Domain\TillData\Casts\TillEnumCast;
use App\Domain\TillData\Concerns\HubOwnedRow;
use App\Domain\TillData\Enums\RebateAgreementBasis;
use App\Domain\TillData\Enums\RebateAgreementScope;
use Carbon\CarbonImmutable;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * Till entity `RebateAgreement`: hub-owned (portal writes, tills apply), company scope. Table `rebate_agreements`.
 *
 * @generated by `php artisan till:entities:generate` from
 * docs/contracts/portal-api-v1.3.1/docs/web-portal-api/schemas/entities/RebateAgreement.schema.json and
 * app/Domain/TillData/definitions.php. Do not edit: change the definitions or a hand-written trait and regenerate.
 *
 * @property string $id
 * @property string $company_id
 * @property string $supplier_id
 * @property string $name
 * @property RebateAgreementScope|null $scope
 * @property string $scope_id
 * @property RebateAgreementBasis|null $basis
 * @property string $rate
 * @property CarbonImmutable $period_from
 * @property CarbonImmutable $period_to
 * @property string $threshold
 * @property bool $is_active
 * @property string $note
 * @property int $row_version
 * @property CarbonImmutable|null $created_at
 * @property CarbonImmutable|null $updated_at
 * @property CarbonImmutable|null $deleted_at
 * @property int|null $hub_version
 * @property CarbonImmutable|null $hub_edited_at
 * @property string|null $hub_hash
 * @property string|null $origin_branch_id
 * @property CarbonImmutable|null $synced_at
 * @property int|null $sync_seq
 * @property array<string, mixed>|null $extra
 * @property CarbonImmutable|null $portal_received_at
 */
final class RebateAgreement extends Model
{
    use BelongsToCompany, HubOwnedRow, SoftDeletes;

    public const TILL_ENTITY = 'RebateAgreement';

    public $incrementing = false;

    public $timestamps = false;

    protected $table = 'rebate_agreements';

    protected $keyType = 'string';

    /**
     * @return array<string, string>
     */
    protected function casts(): array
    {
        return [
            'scope' => TillEnumCast::class.':'.RebateAgreementScope::class,
            'basis' => TillEnumCast::class.':'.RebateAgreementBasis::class,
            'rate' => QuantityCast::class,
            'period_from' => 'immutable_date:Y-m-d',
            'period_to' => 'immutable_date:Y-m-d',
            'threshold' => MoneyCast::class,
            'is_active' => 'boolean',
            'row_version' => 'integer',
            'created_at' => UtcDateTimeCast::class,
            'updated_at' => UtcDateTimeCast::class,
            'deleted_at' => UtcDateTimeCast::class,
            'hub_version' => 'integer',
            'hub_edited_at' => UtcDateTimeCast::class,
            'synced_at' => UtcDateTimeCast::class,
            'sync_seq' => 'integer',
            'extra' => 'array',
            'portal_received_at' => UtcDateTimeCast::class,
        ];
    }
}
