<?php

namespace App\Domain\TillData\Models;

use App\Domain\Shared\Casts\MoneyCast;
use App\Domain\Shared\Casts\UtcDateTimeCast;
use App\Domain\Tenancy\Concerns\BelongsToCompany;
use App\Domain\TillData\Casts\TillEnumCast;
use App\Domain\TillData\Concerns\ScopedToBranch;
use App\Domain\TillData\Concerns\TillOwnedRow;
use App\Domain\TillData\Enums\ExpensePaymentType;
use App\Domain\TillData\Enums\RecurringBillFrequency;
use Carbon\CarbonImmutable;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * Till entity `RecurringBill`: branch-owned (read-only on the portal), branch scope. Table `recurring_bills`.
 *
 * @generated by `php artisan till:entities:generate` from
 * docs/contracts/portal-api-v1.1/schemas/entities/RecurringBill.schema.json and
 * app/Domain/TillData/definitions.php. Do not edit: change the definitions or a hand-written trait and regenerate.
 *
 * @property string $id
 * @property string $company_id
 * @property string|null $branch_id
 * @property string $description
 * @property string $reason_id
 * @property string $supplier_id
 * @property string $payee_name
 * @property string $net
 * @property string $vat_rate_id
 * @property ExpensePaymentType|null $payment_type
 * @property RecurringBillFrequency|null $frequency
 * @property int $due_day
 * @property CarbonImmutable $next_due_date
 * @property bool $is_active
 * @property string $last_expense_id
 * @property CarbonImmutable|null $last_recorded_date
 * @property string $note
 * @property int $row_version
 * @property CarbonImmutable|null $created_at
 * @property CarbonImmutable|null $updated_at
 * @property CarbonImmutable|null $deleted_at
 * @property CarbonImmutable|null $synced_at
 * @property int|null $sync_seq
 * @property array<string, mixed>|null $extra
 */
final class RecurringBill extends Model
{
    use BelongsToCompany, ScopedToBranch, SoftDeletes, TillOwnedRow;

    public const TILL_ENTITY = 'RecurringBill';

    public $incrementing = false;

    public $timestamps = false;

    protected $table = 'recurring_bills';

    protected $keyType = 'string';

    /**
     * @return array<string, string>
     */
    protected function casts(): array
    {
        return [
            'net' => MoneyCast::class,
            'payment_type' => TillEnumCast::class.':'.ExpensePaymentType::class,
            'frequency' => TillEnumCast::class.':'.RecurringBillFrequency::class,
            'due_day' => 'integer',
            'next_due_date' => 'immutable_date:Y-m-d',
            'is_active' => 'boolean',
            'last_recorded_date' => 'immutable_date:Y-m-d',
            'row_version' => 'integer',
            'created_at' => UtcDateTimeCast::class,
            'updated_at' => UtcDateTimeCast::class,
            'deleted_at' => UtcDateTimeCast::class,
            'synced_at' => UtcDateTimeCast::class,
            'sync_seq' => 'integer',
            'extra' => 'array',
        ];
    }
}
