<?php

namespace App\Domain\TillData\Models;

use App\Domain\Shared\Casts\MoneyCast;
use App\Domain\Shared\Casts\UtcDateTimeCast;
use App\Domain\Tenancy\Concerns\BelongsToCompany;
use App\Domain\TillData\Casts\RateCast;
use App\Domain\TillData\Casts\TillEnumCast;
use App\Domain\TillData\Concerns\ScopedToBranch;
use App\Domain\TillData\Concerns\ScopedToRegister;
use App\Domain\TillData\Concerns\TillOwnedRow;
use App\Domain\TillData\Enums\SalePaymentStatus;
use Carbon\CarbonImmutable;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * Till entity `SalePayment`: branch-owned (read-only on the portal), child scope, parent Sale. Table `sale_payments`.
 *
 * @generated by `php artisan till:entities:generate` from
 * docs/contracts/portal-api-v1.3.1/docs/web-portal-api/schemas/entities/SalePayment.schema.json and
 * app/Domain/TillData/definitions.php. Do not edit: change the definitions or a hand-written trait and regenerate.
 *
 * @property string $id
 * @property string $company_id
 * @property string|null $branch_id
 * @property string|null $register_id
 * @property string $sale_id
 * @property string $payment_type_id
 * @property string $payment_type_name
 * @property int $position
 * @property string $amount
 * @property string $cashback
 * @property string $change_given
 * @property SalePaymentStatus|null $status
 * @property string $terminal_txn_id
 * @property string $provider_ref
 * @property string $scheme
 * @property string $last4
 * @property string $auth_code
 * @property string $idempotency_key
 * @property string $currency
 * @property string $foreign_amount
 * @property string $exchange_rate
 * @property string $applied_amount
 * @property bool $is_offline
 * @property int $row_version
 * @property CarbonImmutable|null $created_at
 * @property CarbonImmutable|null $updated_at
 * @property CarbonImmutable|null $deleted_at
 * @property CarbonImmutable|null $synced_at
 * @property int|null $sync_seq
 * @property array<string, mixed>|null $extra
 * @property CarbonImmutable|null $portal_received_at
 */
final class SalePayment extends Model
{
    use BelongsToCompany, ScopedToBranch, ScopedToRegister, SoftDeletes, TillOwnedRow;

    public const TILL_ENTITY = 'SalePayment';

    public $incrementing = false;

    public $timestamps = false;

    protected $table = 'sale_payments';

    protected $keyType = 'string';

    /**
     * @return array<string, string>
     */
    protected function casts(): array
    {
        return [
            'position' => 'integer',
            'amount' => MoneyCast::class,
            'cashback' => MoneyCast::class,
            'change_given' => MoneyCast::class,
            'status' => TillEnumCast::class.':'.SalePaymentStatus::class,
            'foreign_amount' => MoneyCast::class,
            'exchange_rate' => RateCast::class,
            'applied_amount' => MoneyCast::class,
            'is_offline' => 'boolean',
            'row_version' => 'integer',
            'created_at' => UtcDateTimeCast::class,
            'updated_at' => UtcDateTimeCast::class,
            'deleted_at' => UtcDateTimeCast::class,
            'synced_at' => UtcDateTimeCast::class,
            'sync_seq' => 'integer',
            'extra' => 'array',
            'portal_received_at' => UtcDateTimeCast::class,
        ];
    }

    /**
     * @return BelongsTo<Sale, $this>
     */
    public function sale(): BelongsTo
    {
        return $this->belongsTo(Sale::class, 'sale_id');
    }
}
