<?php

namespace App\Domain\TillData\Models;

use App\Domain\Shared\Casts\MoneyCast;
use App\Domain\Shared\Casts\UtcDateTimeCast;
use App\Domain\Tenancy\Concerns\BelongsToCompany;
use App\Domain\TillData\Casts\TillEnumCast;
use App\Domain\TillData\Concerns\SaleQueries;
use App\Domain\TillData\Concerns\ScopedToBranch;
use App\Domain\TillData\Concerns\ScopedToRegister;
use App\Domain\TillData\Concerns\TillOwnedRow;
use App\Domain\TillData\Enums\SaleStatus;
use App\Domain\TillData\Enums\SaleType;
use Carbon\CarbonImmutable;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * Till entity `Sale`: branch-owned (read-only on the portal), register scope. Table `sales`.
 *
 * @generated by `php artisan till:entities:generate` from
 * docs/contracts/portal-api-v1.3.3/docs/web-portal-api/schemas/entities/Sale.schema.json and
 * app/Domain/TillData/definitions.php. Do not edit: change the definitions or a hand-written trait and regenerate.
 *
 * @property string $id
 * @property string $company_id
 * @property string|null $branch_id
 * @property string|null $register_id
 * @property string $shift_id
 * @property string $user_id
 * @property string|null $customer_id
 * @property int $number
 * @property string $receipt_number
 * @property SaleType|null $type
 * @property SaleStatus|null $status
 * @property string|null $original_sale_id
 * @property bool $no_receipt
 * @property string $refund_price_basis
 * @property string|null $reason_id
 * @property string $approved_by
 * @property string|null $void_reason_id
 * @property string $voided_by
 * @property string $subtotal
 * @property string $discount_total
 * @property string $promo_total
 * @property string $deposit_total
 * @property string $vat_total
 * @property string $total
 * @property string $held_name
 * @property CarbonImmutable|null $completed_at
 * @property string $receipt_json
 * @property string $idempotency_key
 * @property int $row_version
 * @property CarbonImmutable|null $created_at
 * @property CarbonImmutable|null $updated_at
 * @property CarbonImmutable|null $deleted_at
 * @property CarbonImmutable|null $synced_at
 * @property int|null $sync_seq
 * @property array<string, mixed>|null $extra
 * @property CarbonImmutable|null $portal_received_at
 */
final class Sale extends Model
{
    use BelongsToCompany, SaleQueries, ScopedToBranch, ScopedToRegister, SoftDeletes, TillOwnedRow;

    public const TILL_ENTITY = 'Sale';

    public $incrementing = false;

    public $timestamps = false;

    protected $table = 'sales';

    protected $keyType = 'string';

    /**
     * @return array<string, string>
     */
    protected function casts(): array
    {
        return [
            'number' => 'integer',
            'type' => TillEnumCast::class.':'.SaleType::class,
            'status' => TillEnumCast::class.':'.SaleStatus::class,
            'no_receipt' => 'boolean',
            'subtotal' => MoneyCast::class,
            'discount_total' => MoneyCast::class,
            'promo_total' => MoneyCast::class,
            'deposit_total' => MoneyCast::class,
            'vat_total' => MoneyCast::class,
            'total' => MoneyCast::class,
            'completed_at' => UtcDateTimeCast::class,
            'row_version' => 'integer',
            'created_at' => UtcDateTimeCast::class,
            'updated_at' => UtcDateTimeCast::class,
            'deleted_at' => UtcDateTimeCast::class,
            'synced_at' => UtcDateTimeCast::class,
            'sync_seq' => 'integer',
            'extra' => 'array',
            'portal_received_at' => UtcDateTimeCast::class,
        ];
    }

    /**
     * @return HasMany<SaleLine, $this>
     */
    public function saleLines(): HasMany
    {
        return $this->hasMany(SaleLine::class, 'sale_id');
    }

    /**
     * @return HasMany<SalePayment, $this>
     */
    public function salePayments(): HasMany
    {
        return $this->hasMany(SalePayment::class, 'sale_id');
    }

    /**
     * @return HasMany<SaleVat, $this>
     */
    public function saleVats(): HasMany
    {
        return $this->hasMany(SaleVat::class, 'sale_id');
    }
}
