<?php

namespace App\Domain\TillData\Models;

use App\Domain\Shared\Casts\MoneyCast;
use App\Domain\Shared\Casts\QuantityCast;
use App\Domain\Shared\Casts\UtcDateTimeCast;
use App\Domain\Tenancy\Concerns\BelongsToCompany;
use App\Domain\TillData\Concerns\ScopedToBranch;
use App\Domain\TillData\Concerns\ScopedToRegister;
use App\Domain\TillData\Concerns\TillOwnedRow;
use Carbon\CarbonImmutable;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * Till entity `SalesDaily`: branch-owned (read-only on the portal), register scope. Table `sales_daily`.
 *
 * @generated by `php artisan till:entities:generate` from
 * docs/contracts/portal-api-v1.3.1/docs/web-portal-api/schemas/entities/SalesDaily.schema.json and
 * app/Domain/TillData/definitions.php. Do not edit: change the definitions or a hand-written trait and regenerate.
 *
 * @property string $id
 * @property string $company_id
 * @property string|null $branch_id
 * @property string|null $register_id
 * @property CarbonImmutable $date
 * @property string $product_id
 * @property string $user_id
 * @property string $qty
 * @property string $net
 * @property string $vat
 * @property string $gross
 * @property string $cost
 * @property string $discount
 * @property string $promo
 * @property string $refund_qty
 * @property string $refund_net
 * @property string $profit
 * @property int $row_version
 * @property CarbonImmutable|null $created_at
 * @property CarbonImmutable|null $updated_at
 * @property CarbonImmutable|null $deleted_at
 * @property CarbonImmutable|null $synced_at
 * @property int|null $sync_seq
 * @property array<string, mixed>|null $extra
 * @property CarbonImmutable|null $portal_received_at
 */
final class SalesDaily extends Model
{
    use BelongsToCompany, ScopedToBranch, ScopedToRegister, SoftDeletes, TillOwnedRow;

    public const TILL_ENTITY = 'SalesDaily';

    public $incrementing = false;

    public $timestamps = false;

    protected $table = 'sales_daily';

    protected $keyType = 'string';

    /**
     * @return array<string, string>
     */
    protected function casts(): array
    {
        return [
            'date' => 'immutable_date:Y-m-d',
            'qty' => QuantityCast::class,
            'net' => MoneyCast::class,
            'vat' => MoneyCast::class,
            'gross' => MoneyCast::class,
            'cost' => QuantityCast::class,
            'discount' => MoneyCast::class,
            'promo' => MoneyCast::class,
            'refund_qty' => QuantityCast::class,
            'refund_net' => MoneyCast::class,
            'profit' => MoneyCast::class,
            'row_version' => 'integer',
            'created_at' => UtcDateTimeCast::class,
            'updated_at' => UtcDateTimeCast::class,
            'deleted_at' => UtcDateTimeCast::class,
            'synced_at' => UtcDateTimeCast::class,
            'sync_seq' => 'integer',
            'extra' => 'array',
            'portal_received_at' => UtcDateTimeCast::class,
        ];
    }
}
