<?php

namespace App\Domain\TillData\Models;

use App\Domain\Shared\Casts\MoneyCast;
use App\Domain\Shared\Casts\UtcDateTimeCast;
use App\Domain\Tenancy\Concerns\BelongsToCompany;
use App\Domain\TillData\Casts\TillEnumCast;
use App\Domain\TillData\Concerns\ScopedToBranch;
use App\Domain\TillData\Concerns\ScopedToRegister;
use App\Domain\TillData\Concerns\TillOwnedRow;
use App\Domain\TillData\Enums\ShiftMode;
use App\Domain\TillData\Enums\ShiftStatus;
use Carbon\CarbonImmutable;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * Till entity `Shift`: branch-owned (read-only on the portal), register scope. Table `shifts`.
 *
 * @generated by `php artisan till:entities:generate` from
 * docs/contracts/portal-api-v1.3.3/docs/web-portal-api/schemas/entities/Shift.schema.json and
 * app/Domain/TillData/definitions.php. Do not edit: change the definitions or a hand-written trait and regenerate.
 *
 * @property string $id
 * @property string $company_id
 * @property string|null $branch_id
 * @property string|null $register_id
 * @property string $user_id
 * @property CarbonImmutable $opened_at
 * @property CarbonImmutable|null $closed_at
 * @property string $opening_float
 * @property string $closed_by
 * @property string $override_by
 * @property string $override_reason
 * @property ShiftStatus|null $status
 * @property string $variance_total
 * @property string $close_notes
 * @property ShiftMode|null $mode
 * @property string $drawer_owner_user_id
 * @property int $row_version
 * @property CarbonImmutable|null $created_at
 * @property CarbonImmutable|null $updated_at
 * @property CarbonImmutable|null $deleted_at
 * @property CarbonImmutable|null $synced_at
 * @property int|null $sync_seq
 * @property array<string, mixed>|null $extra
 * @property CarbonImmutable|null $portal_received_at
 */
final class Shift extends Model
{
    use BelongsToCompany, ScopedToBranch, ScopedToRegister, SoftDeletes, TillOwnedRow;

    public const TILL_ENTITY = 'Shift';

    public $incrementing = false;

    public $timestamps = false;

    protected $table = 'shifts';

    protected $keyType = 'string';

    /**
     * @return array<string, string>
     */
    protected function casts(): array
    {
        return [
            'opened_at' => UtcDateTimeCast::class,
            'closed_at' => UtcDateTimeCast::class,
            'opening_float' => MoneyCast::class,
            'status' => TillEnumCast::class.':'.ShiftStatus::class,
            'variance_total' => MoneyCast::class,
            'mode' => TillEnumCast::class.':'.ShiftMode::class,
            'row_version' => 'integer',
            'created_at' => UtcDateTimeCast::class,
            'updated_at' => UtcDateTimeCast::class,
            'deleted_at' => UtcDateTimeCast::class,
            'synced_at' => UtcDateTimeCast::class,
            'sync_seq' => 'integer',
            'extra' => 'array',
            'portal_received_at' => UtcDateTimeCast::class,
        ];
    }

    /**
     * @return HasMany<ShiftTender, $this>
     */
    public function shiftTenders(): HasMany
    {
        return $this->hasMany(ShiftTender::class, 'shift_id');
    }
}
