<?php

namespace App\Domain\TillData\Models;

use App\Domain\Shared\Casts\UtcDateTimeCast;
use App\Domain\Tenancy\Concerns\BelongsToCompany;
use App\Domain\TillData\Casts\TillEnumCast;
use App\Domain\TillData\Concerns\ScopedToBranch;
use App\Domain\TillData\Concerns\TillOwnedRow;
use App\Domain\TillData\Enums\ShopRoutineRunStatus;
use App\Domain\TillData\Enums\ShopRoutineRunType;
use Carbon\CarbonImmutable;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * Till entity `ShopRoutineRun`: branch-owned (read-only on the portal), branch scope. Table `shop_routine_runs`.
 *
 * @generated by `php artisan till:entities:generate` from
 * docs/contracts/portal-api-v1.3.3/docs/web-portal-api/schemas/entities/ShopRoutineRun.schema.json and
 * app/Domain/TillData/definitions.php. Do not edit: change the definitions or a hand-written trait and regenerate.
 *
 * @property string $id
 * @property string $company_id
 * @property string|null $branch_id
 * @property ShopRoutineRunType|null $type
 * @property CarbonImmutable $trading_date
 * @property ShopRoutineRunStatus|null $status
 * @property string $steps_json
 * @property string $started_by
 * @property CarbonImmutable $started_at
 * @property CarbonImmutable|null $completed_at
 * @property string $idempotency_key
 * @property int $row_version
 * @property CarbonImmutable|null $created_at
 * @property CarbonImmutable|null $updated_at
 * @property CarbonImmutable|null $deleted_at
 * @property CarbonImmutable|null $synced_at
 * @property int|null $sync_seq
 * @property array<string, mixed>|null $extra
 * @property CarbonImmutable|null $portal_received_at
 */
final class ShopRoutineRun extends Model
{
    use BelongsToCompany, ScopedToBranch, SoftDeletes, TillOwnedRow;

    public const TILL_ENTITY = 'ShopRoutineRun';

    public $incrementing = false;

    public $timestamps = false;

    protected $table = 'shop_routine_runs';

    protected $keyType = 'string';

    /**
     * @return array<string, string>
     */
    protected function casts(): array
    {
        return [
            'type' => TillEnumCast::class.':'.ShopRoutineRunType::class,
            'trading_date' => 'immutable_date:Y-m-d',
            'status' => TillEnumCast::class.':'.ShopRoutineRunStatus::class,
            'started_at' => UtcDateTimeCast::class,
            'completed_at' => UtcDateTimeCast::class,
            'row_version' => 'integer',
            'created_at' => UtcDateTimeCast::class,
            'updated_at' => UtcDateTimeCast::class,
            'deleted_at' => UtcDateTimeCast::class,
            'synced_at' => UtcDateTimeCast::class,
            'sync_seq' => 'integer',
            'extra' => 'array',
            'portal_received_at' => UtcDateTimeCast::class,
        ];
    }
}
