<?php

namespace App\Domain\TillData\Models;

use App\Domain\Shared\Casts\QuantityCast;
use App\Domain\Shared\Casts\UtcDateTimeCast;
use App\Domain\Tenancy\Concerns\BelongsToCompany;
use App\Domain\TillData\Concerns\ScopedToBranch;
use App\Domain\TillData\Concerns\TillOwnedRow;
use Carbon\CarbonImmutable;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * Till entity `StockTransferReceiptLine`: branch-owned (read-only on the portal), branch scope, parent StockTransferReceipt. Table `stock_transfer_receipt_lines`.
 *
 * @generated by `php artisan till:entities:generate` from
 * docs/contracts/portal-api-v1.4.1/docs/web-portal-api/schemas/entities/StockTransferReceiptLine.schema.json and
 * app/Domain/TillData/definitions.php. Do not edit: change the definitions or a hand-written trait and regenerate.
 *
 * @property string $id
 * @property string $company_id
 * @property string|null $branch_id
 * @property string $receipt_id
 * @property string $transfer_id
 * @property string $transfer_line_id
 * @property string $product_id
 * @property string $qty_dispatched
 * @property string $qty_received
 * @property string $qty_variance
 * @property string $unit_cost
 * @property int $row_version
 * @property CarbonImmutable|null $created_at
 * @property CarbonImmutable|null $updated_at
 * @property CarbonImmutable|null $deleted_at
 * @property CarbonImmutable|null $synced_at
 * @property int|null $sync_seq
 * @property array<string, mixed>|null $extra
 * @property CarbonImmutable|null $portal_received_at
 */
final class StockTransferReceiptLine extends Model
{
    use BelongsToCompany, ScopedToBranch, SoftDeletes, TillOwnedRow;

    public const TILL_ENTITY = 'StockTransferReceiptLine';

    public $incrementing = false;

    public $timestamps = false;

    protected $table = 'stock_transfer_receipt_lines';

    protected $keyType = 'string';

    /**
     * @return array<string, string>
     */
    protected function casts(): array
    {
        return [
            'qty_dispatched' => QuantityCast::class,
            'qty_received' => QuantityCast::class,
            'qty_variance' => QuantityCast::class,
            'unit_cost' => QuantityCast::class,
            'row_version' => 'integer',
            'created_at' => UtcDateTimeCast::class,
            'updated_at' => UtcDateTimeCast::class,
            'deleted_at' => UtcDateTimeCast::class,
            'synced_at' => UtcDateTimeCast::class,
            'sync_seq' => 'integer',
            'extra' => 'array',
            'portal_received_at' => UtcDateTimeCast::class,
        ];
    }

    /**
     * @return BelongsTo<StockTransferReceipt, $this>
     */
    public function stockTransferReceipt(): BelongsTo
    {
        return $this->belongsTo(StockTransferReceipt::class, 'receipt_id');
    }
}
