<?php

namespace App\Domain\TillData\Models;

use App\Domain\Shared\Casts\MoneyCast;
use App\Domain\Shared\Casts\QuantityCast;
use App\Domain\Shared\Casts\UtcDateTimeCast;
use App\Domain\Tenancy\Concerns\BelongsToCompany;
use App\Domain\TillData\Casts\TillEnumCast;
use App\Domain\TillData\Concerns\ScopedToBranch;
use App\Domain\TillData\Concerns\TillOwnedRow;
use App\Domain\TillData\Enums\StockTakeScope;
use App\Domain\TillData\Enums\StockTakeStatus;
use Carbon\CarbonImmutable;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * Till entity `StockTake`: branch-owned (read-only on the portal), branch scope. Table `stock_takes`.
 *
 * @generated by `php artisan till:entities:generate` from
 * docs/contracts/portal-api-v1.3.3/docs/web-portal-api/schemas/entities/StockTake.schema.json and
 * app/Domain/TillData/definitions.php. Do not edit: change the definitions or a hand-written trait and regenerate.
 *
 * @property string $id
 * @property string $company_id
 * @property string|null $branch_id
 * @property string $reference
 * @property string $name
 * @property StockTakeScope|null $scope
 * @property string $scope_id
 * @property StockTakeStatus|null $status
 * @property bool $is_blind
 * @property bool $count_uncounted_as_zero
 * @property string $started_by_user_id
 * @property CarbonImmutable $started_at
 * @property string $approved_by_user_id
 * @property CarbonImmutable|null $approved_at
 * @property CarbonImmutable|null $cancelled_at
 * @property string $recount_threshold_value
 * @property string $recount_threshold_percent
 * @property string $approval_over_value
 * @property string $note
 * @property bool $is_high_value_count
 * @property int $row_version
 * @property CarbonImmutable|null $created_at
 * @property CarbonImmutable|null $updated_at
 * @property CarbonImmutable|null $deleted_at
 * @property CarbonImmutable|null $synced_at
 * @property int|null $sync_seq
 * @property array<string, mixed>|null $extra
 * @property CarbonImmutable|null $portal_received_at
 */
final class StockTake extends Model
{
    use BelongsToCompany, ScopedToBranch, SoftDeletes, TillOwnedRow;

    public const TILL_ENTITY = 'StockTake';

    public $incrementing = false;

    public $timestamps = false;

    protected $table = 'stock_takes';

    protected $keyType = 'string';

    /**
     * @return array<string, string>
     */
    protected function casts(): array
    {
        return [
            'scope' => TillEnumCast::class.':'.StockTakeScope::class,
            'status' => TillEnumCast::class.':'.StockTakeStatus::class,
            'is_blind' => 'boolean',
            'count_uncounted_as_zero' => 'boolean',
            'started_at' => UtcDateTimeCast::class,
            'approved_at' => UtcDateTimeCast::class,
            'cancelled_at' => UtcDateTimeCast::class,
            'recount_threshold_value' => MoneyCast::class,
            'recount_threshold_percent' => QuantityCast::class,
            'approval_over_value' => MoneyCast::class,
            'is_high_value_count' => 'boolean',
            'row_version' => 'integer',
            'created_at' => UtcDateTimeCast::class,
            'updated_at' => UtcDateTimeCast::class,
            'deleted_at' => UtcDateTimeCast::class,
            'synced_at' => UtcDateTimeCast::class,
            'sync_seq' => 'integer',
            'extra' => 'array',
            'portal_received_at' => UtcDateTimeCast::class,
        ];
    }

    /**
     * @return HasMany<StockTakeLine, $this>
     */
    public function stockTakeLines(): HasMany
    {
        return $this->hasMany(StockTakeLine::class, 'stock_take_id');
    }

    /**
     * @return HasMany<StockTakeSection, $this>
     */
    public function stockTakeSections(): HasMany
    {
        return $this->hasMany(StockTakeSection::class, 'stock_take_id');
    }
}
