<?php

namespace App\Domain\TillData\Models;

use App\Domain\Shared\Casts\QuantityCast;
use App\Domain\Shared\Casts\UtcDateTimeCast;
use App\Domain\Tenancy\Concerns\BelongsToCompany;
use App\Domain\TillData\Casts\TillEnumCast;
use App\Domain\TillData\Concerns\ScopedToBranch;
use App\Domain\TillData\Concerns\TillOwnedRow;
use App\Domain\TillData\Enums\StockTransferStatus;
use Carbon\CarbonImmutable;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * Till entity `StockTransfer`: branch-owned (read-only on the portal), branch scope. Table `stock_transfers`.
 *
 * @generated by `php artisan till:entities:generate` from
 * docs/contracts/portal-api-v1.3.3/docs/web-portal-api/schemas/entities/StockTransfer.schema.json and
 * app/Domain/TillData/definitions.php. Do not edit: change the definitions or a hand-written trait and regenerate.
 *
 * @property string $id
 * @property string $company_id
 * @property string|null $branch_id
 * @property string $reference
 * @property string $from_branch_id
 * @property string $to_branch_id
 * @property StockTransferStatus|null $status
 * @property CarbonImmutable $requested_at
 * @property string $requested_by_user_id
 * @property CarbonImmutable|null $dispatched_at
 * @property string $dispatched_by_user_id
 * @property string $dispatched_cost
 * @property bool $is_return
 * @property string|null $return_of_transfer_id
 * @property string $note
 * @property int $row_version
 * @property CarbonImmutable|null $created_at
 * @property CarbonImmutable|null $updated_at
 * @property CarbonImmutable|null $deleted_at
 * @property CarbonImmutable|null $synced_at
 * @property int|null $sync_seq
 * @property array<string, mixed>|null $extra
 * @property CarbonImmutable|null $portal_received_at
 */
final class StockTransfer extends Model
{
    use BelongsToCompany, ScopedToBranch, SoftDeletes, TillOwnedRow;

    public const TILL_ENTITY = 'StockTransfer';

    public $incrementing = false;

    public $timestamps = false;

    protected $table = 'stock_transfers';

    protected $keyType = 'string';

    /**
     * @return array<string, string>
     */
    protected function casts(): array
    {
        return [
            'status' => TillEnumCast::class.':'.StockTransferStatus::class,
            'requested_at' => UtcDateTimeCast::class,
            'dispatched_at' => UtcDateTimeCast::class,
            'dispatched_cost' => QuantityCast::class,
            'is_return' => 'boolean',
            'row_version' => 'integer',
            'created_at' => UtcDateTimeCast::class,
            'updated_at' => UtcDateTimeCast::class,
            'deleted_at' => UtcDateTimeCast::class,
            'synced_at' => UtcDateTimeCast::class,
            'sync_seq' => 'integer',
            'extra' => 'array',
            'portal_received_at' => UtcDateTimeCast::class,
        ];
    }

    /**
     * @return HasMany<StockTransferLine, $this>
     */
    public function stockTransferLines(): HasMany
    {
        return $this->hasMany(StockTransferLine::class, 'transfer_id');
    }

    /**
     * @return HasMany<StockTransferReceipt, $this>
     */
    public function stockTransferReceipts(): HasMany
    {
        return $this->hasMany(StockTransferReceipt::class, 'transfer_id');
    }
}
