<?php

namespace App\Domain\TillData\Models;

use App\Domain\Shared\Casts\MoneyCast;
use App\Domain\Shared\Casts\UtcDateTimeCast;
use App\Domain\Tenancy\Concerns\BelongsToCompany;
use App\Domain\TillData\Casts\TillEnumCast;
use App\Domain\TillData\Concerns\ScopedToBranch;
use App\Domain\TillData\Concerns\TillOwnedRow;
use App\Domain\TillData\Enums\SupplierPaymentMethod;
use Carbon\CarbonImmutable;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * Till entity `SupplierPayment`: branch-owned (read-only on the portal), branch scope. Table `supplier_payments`.
 *
 * @generated by `php artisan till:entities:generate` from
 * docs/contracts/portal-api-v1.3.1/docs/web-portal-api/schemas/entities/SupplierPayment.schema.json and
 * app/Domain/TillData/definitions.php. Do not edit: change the definitions or a hand-written trait and regenerate.
 *
 * @property string $id
 * @property string $company_id
 * @property string|null $branch_id
 * @property string $supplier_id
 * @property string $supplier_name
 * @property CarbonImmutable $payment_date
 * @property SupplierPaymentMethod|null $method
 * @property string|null $reference
 * @property string $amount
 * @property string $allocated_amount
 * @property string $unallocated
 * @property string|null $notes
 * @property bool $is_reversed
 * @property CarbonImmutable|null $reversed_at
 * @property string|null $reversed_by_user_id
 * @property int $row_version
 * @property CarbonImmutable|null $created_at
 * @property CarbonImmutable|null $updated_at
 * @property CarbonImmutable|null $deleted_at
 * @property CarbonImmutable|null $synced_at
 * @property int|null $sync_seq
 * @property array<string, mixed>|null $extra
 * @property CarbonImmutable|null $portal_received_at
 */
final class SupplierPayment extends Model
{
    use BelongsToCompany, ScopedToBranch, SoftDeletes, TillOwnedRow;

    public const TILL_ENTITY = 'SupplierPayment';

    public $incrementing = false;

    public $timestamps = false;

    protected $table = 'supplier_payments';

    protected $keyType = 'string';

    /**
     * @return array<string, string>
     */
    protected function casts(): array
    {
        return [
            'payment_date' => 'immutable_date:Y-m-d',
            'method' => TillEnumCast::class.':'.SupplierPaymentMethod::class,
            'amount' => MoneyCast::class,
            'allocated_amount' => MoneyCast::class,
            'unallocated' => MoneyCast::class,
            'is_reversed' => 'boolean',
            'reversed_at' => UtcDateTimeCast::class,
            'row_version' => 'integer',
            'created_at' => UtcDateTimeCast::class,
            'updated_at' => UtcDateTimeCast::class,
            'deleted_at' => UtcDateTimeCast::class,
            'synced_at' => UtcDateTimeCast::class,
            'sync_seq' => 'integer',
            'extra' => 'array',
            'portal_received_at' => UtcDateTimeCast::class,
        ];
    }

    /**
     * @return HasMany<SupplierPaymentAllocation, $this>
     */
    public function supplierPaymentAllocations(): HasMany
    {
        return $this->hasMany(SupplierPaymentAllocation::class, 'supplier_payment_id');
    }
}
