<?php

namespace App\Domain\TillData\Models;

use App\Domain\Shared\Casts\MoneyCast;
use App\Domain\Shared\Casts\UtcDateTimeCast;
use App\Domain\Tenancy\Concerns\BelongsToCompany;
use App\Domain\TillData\Casts\TillEnumCast;
use App\Domain\TillData\Concerns\HubOwnedRow;
use App\Domain\TillData\Enums\SupplierOrderMethod;
use App\Domain\TillData\Enums\SupplierTermsKind;
use Carbon\CarbonImmutable;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * Till entity `Supplier`: hub-owned (portal writes, tills apply), company scope. Table `suppliers`.
 *
 * @generated by `php artisan till:entities:generate` from
 * docs/contracts/portal-api-v1.3.1/docs/web-portal-api/schemas/entities/Supplier.schema.json and
 * app/Domain/TillData/definitions.php. Do not edit: change the definitions or a hand-written trait and regenerate.
 *
 * @property string $id
 * @property string $company_id
 * @property string $name
 * @property string $code
 * @property bool $is_active
 * @property string|null $contact_name
 * @property string|null $phone
 * @property string|null $email
 * @property string|null $address_line1
 * @property string|null $address_line2
 * @property string|null $town
 * @property string|null $postcode
 * @property string|null $account_number
 * @property SupplierTermsKind|null $terms_kind
 * @property int $payment_terms_days
 * @property int $default_lead_days
 * @property string $minimum_order_value
 * @property SupplierOrderMethod|null $order_method
 * @property string $delivery_days
 * @property string|null $vat_number
 * @property string|null $notes
 * @property int $row_version
 * @property CarbonImmutable|null $created_at
 * @property CarbonImmutable|null $updated_at
 * @property CarbonImmutable|null $deleted_at
 * @property int|null $hub_version
 * @property CarbonImmutable|null $hub_edited_at
 * @property string|null $hub_hash
 * @property string|null $origin_branch_id
 * @property CarbonImmutable|null $synced_at
 * @property int|null $sync_seq
 * @property array<string, mixed>|null $extra
 * @property CarbonImmutable|null $portal_received_at
 */
final class Supplier extends Model
{
    use BelongsToCompany, HubOwnedRow, SoftDeletes;

    public const TILL_ENTITY = 'Supplier';

    public $incrementing = false;

    public $timestamps = false;

    protected $table = 'suppliers';

    protected $keyType = 'string';

    /**
     * @return array<string, string>
     */
    protected function casts(): array
    {
        return [
            'is_active' => 'boolean',
            'terms_kind' => TillEnumCast::class.':'.SupplierTermsKind::class,
            'payment_terms_days' => 'integer',
            'default_lead_days' => 'integer',
            'minimum_order_value' => MoneyCast::class,
            'order_method' => TillEnumCast::class.':'.SupplierOrderMethod::class,
            'row_version' => 'integer',
            'created_at' => UtcDateTimeCast::class,
            'updated_at' => UtcDateTimeCast::class,
            'deleted_at' => UtcDateTimeCast::class,
            'hub_version' => 'integer',
            'hub_edited_at' => UtcDateTimeCast::class,
            'synced_at' => UtcDateTimeCast::class,
            'sync_seq' => 'integer',
            'extra' => 'array',
            'portal_received_at' => UtcDateTimeCast::class,
        ];
    }
}
