<?php

namespace App\Domain\TillData\Models;

use App\Domain\Shared\Casts\UtcDateTimeCast;
use App\Domain\Tenancy\Concerns\BelongsToCompany;
use App\Domain\TillData\Casts\TillEnumCast;
use App\Domain\TillData\Concerns\HubOwnedRow;
use App\Domain\TillData\Enums\TaxRuleMode;
use App\Domain\TillData\Enums\TaxRuleScope;
use Carbon\CarbonImmutable;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * Till entity `TaxRule`: hub-owned (portal writes, tills apply), company scope. Table `tax_rules`.
 *
 * @generated by `php artisan till:entities:generate` from
 * docs/contracts/portal-api-v1.3.1/docs/web-portal-api/schemas/entities/TaxRule.schema.json and
 * app/Domain/TillData/definitions.php. Do not edit: change the definitions or a hand-written trait and regenerate.
 *
 * @property string $id
 * @property string $company_id
 * @property TaxRuleScope|null $scope
 * @property string $target_id
 * @property TaxRuleMode|null $mode
 * @property string $vat_rate_id
 * @property int $priority
 * @property CarbonImmutable $effective_from
 * @property CarbonImmutable|null $effective_to
 * @property string $note
 * @property bool $is_active
 * @property int $row_version
 * @property CarbonImmutable|null $created_at
 * @property CarbonImmutable|null $updated_at
 * @property CarbonImmutable|null $deleted_at
 * @property int|null $hub_version
 * @property CarbonImmutable|null $hub_edited_at
 * @property string|null $hub_hash
 * @property string|null $origin_branch_id
 * @property CarbonImmutable|null $synced_at
 * @property int|null $sync_seq
 * @property array<string, mixed>|null $extra
 * @property CarbonImmutable|null $portal_received_at
 */
final class TaxRule extends Model
{
    use BelongsToCompany, HubOwnedRow, SoftDeletes;

    public const TILL_ENTITY = 'TaxRule';

    public $incrementing = false;

    public $timestamps = false;

    protected $table = 'tax_rules';

    protected $keyType = 'string';

    /**
     * @return array<string, string>
     */
    protected function casts(): array
    {
        return [
            'scope' => TillEnumCast::class.':'.TaxRuleScope::class,
            'mode' => TillEnumCast::class.':'.TaxRuleMode::class,
            'priority' => 'integer',
            'effective_from' => 'immutable_date:Y-m-d',
            'effective_to' => 'immutable_date:Y-m-d',
            'is_active' => 'boolean',
            'row_version' => 'integer',
            'created_at' => UtcDateTimeCast::class,
            'updated_at' => UtcDateTimeCast::class,
            'deleted_at' => UtcDateTimeCast::class,
            'hub_version' => 'integer',
            'hub_edited_at' => UtcDateTimeCast::class,
            'synced_at' => UtcDateTimeCast::class,
            'sync_seq' => 'integer',
            'extra' => 'array',
            'portal_received_at' => UtcDateTimeCast::class,
        ];
    }
}
