<?php

namespace App\Domain\TillData\Models;

use App\Domain\Shared\Casts\UtcDateTimeCast;
use App\Domain\Tenancy\Concerns\BelongsToCompany;
use App\Domain\TillData\Concerns\ScopedToBranch;
use App\Domain\TillData\Concerns\ScopedToRegister;
use App\Domain\TillData\Concerns\TillOwnedRow;
use Carbon\CarbonImmutable;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * Till entity `AuditLog`: branch-owned (read-only on the portal), register scope. Table `till_audit_logs`.
 *
 * @generated by `php artisan till:entities:generate` from
 * docs/contracts/portal-api-v1.1/schemas/entities/AuditLog.schema.json and
 * app/Domain/TillData/definitions.php. Do not edit: change the definitions or a hand-written trait and regenerate.
 *
 * @property string $id
 * @property string $company_id
 * @property string|null $branch_id
 * @property string|null $register_id
 * @property string $user_id
 * @property string $entity_name
 * @property string $entity_id
 * @property string $action
 * @property string $before_json
 * @property string $after_json
 * @property CarbonImmutable $at
 * @property string $reason
 * @property int $row_version
 * @property CarbonImmutable|null $created_at
 * @property CarbonImmutable|null $updated_at
 * @property CarbonImmutable|null $deleted_at
 * @property CarbonImmutable|null $synced_at
 * @property int|null $sync_seq
 * @property array<string, mixed>|null $extra
 */
final class TillAuditLog extends Model
{
    use BelongsToCompany, ScopedToBranch, ScopedToRegister, SoftDeletes, TillOwnedRow;

    public const TILL_ENTITY = 'AuditLog';

    public $incrementing = false;

    public $timestamps = false;

    protected $table = 'till_audit_logs';

    protected $keyType = 'string';

    /**
     * @return array<string, string>
     */
    protected function casts(): array
    {
        return [
            'at' => UtcDateTimeCast::class,
            'row_version' => 'integer',
            'created_at' => UtcDateTimeCast::class,
            'updated_at' => UtcDateTimeCast::class,
            'deleted_at' => UtcDateTimeCast::class,
            'synced_at' => UtcDateTimeCast::class,
            'sync_seq' => 'integer',
            'extra' => 'array',
        ];
    }
}
