<?php

namespace App\Domain\TillData\Models;

use App\Domain\Shared\Casts\UtcDateTimeCast;
use App\Domain\Tenancy\Concerns\BelongsToCompany;
use App\Domain\TillData\Concerns\ScopedToBranch;
use App\Domain\TillData\Concerns\TillOwnedRow;
use Carbon\CarbonImmutable;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * Till entity `Licence`: branch-owned (read-only on the portal), sender scope. Table `till_licences`.
 *
 * @generated by `php artisan till:entities:generate` from
 * docs/contracts/portal-api-v1.3.1/docs/web-portal-api/schemas/entities/Licence.schema.json and
 * app/Domain/TillData/definitions.php. Do not edit: change the definitions or a hand-written trait and regenerate.
 *
 * @property string $id
 * @property string $company_id
 * @property string|null $branch_id
 * @property string|null $licence_key_hash
 * @property string|null $licence_key_last4
 * @property CarbonImmutable $trial_started_at
 * @property CarbonImmutable $trial_ends_at
 * @property CarbonImmutable|null $activated_at
 * @property CarbonImmutable|null $expires_at
 * @property int $grace_days
 * @property bool $is_dealer
 * @property int $branch_limit
 * @property int $register_limit
 * @property string $device_id
 * @property int $row_version
 * @property CarbonImmutable|null $created_at
 * @property CarbonImmutable|null $updated_at
 * @property CarbonImmutable|null $deleted_at
 * @property CarbonImmutable|null $synced_at
 * @property int|null $sync_seq
 * @property array<string, mixed>|null $extra
 * @property CarbonImmutable|null $portal_received_at
 */
final class TillLicence extends Model
{
    use BelongsToCompany, ScopedToBranch, SoftDeletes, TillOwnedRow;

    public const TILL_ENTITY = 'Licence';

    public $incrementing = false;

    public $timestamps = false;

    protected $table = 'till_licences';

    protected $keyType = 'string';

    /**
     * @var list<string>
     */
    protected $hidden = ['licence_key_hash'];

    /**
     * @return array<string, string>
     */
    protected function casts(): array
    {
        return [
            'trial_started_at' => UtcDateTimeCast::class,
            'trial_ends_at' => UtcDateTimeCast::class,
            'activated_at' => UtcDateTimeCast::class,
            'expires_at' => UtcDateTimeCast::class,
            'grace_days' => 'integer',
            'is_dealer' => 'boolean',
            'branch_limit' => 'integer',
            'register_limit' => 'integer',
            'row_version' => 'integer',
            'created_at' => UtcDateTimeCast::class,
            'updated_at' => UtcDateTimeCast::class,
            'deleted_at' => UtcDateTimeCast::class,
            'synced_at' => UtcDateTimeCast::class,
            'sync_seq' => 'integer',
            'extra' => 'array',
            'portal_received_at' => UtcDateTimeCast::class,
        ];
    }
}
