<?php

namespace App\Domain\TillData\Models;

use App\Domain\Shared\Casts\UtcDateTimeCast;
use App\Domain\Tenancy\Concerns\BelongsToCompany;
use App\Domain\TillData\Casts\TillEnumCast;
use App\Domain\TillData\Concerns\ScopedToBranch;
use App\Domain\TillData\Concerns\TillOwnedRow;
use App\Domain\TillData\Enums\SyncConflictResolution;
use App\Domain\TillData\Enums\SyncOwnership;
use Carbon\CarbonImmutable;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * Till entity `SyncConflict`: branch-owned (read-only on the portal), branch scope. Table `till_sync_conflicts`.
 *
 * @generated by `php artisan till:entities:generate` from
 * docs/contracts/portal-api-v1.3.1/docs/web-portal-api/schemas/entities/SyncConflict.schema.json and
 * app/Domain/TillData/definitions.php. Do not edit: change the definitions or a hand-written trait and regenerate.
 *
 * @property string $id
 * @property string $company_id
 * @property string|null $branch_id
 * @property string $entity
 * @property string $entity_id
 * @property SyncOwnership|null $ownership
 * @property int $hub_version
 * @property int $branch_version
 * @property CarbonImmutable $detected_at
 * @property SyncConflictResolution|null $resolution
 * @property CarbonImmutable|null $resolved_at
 * @property string|null $resolved_by_user_id
 * @property string $detail
 * @property int $row_version
 * @property CarbonImmutable|null $created_at
 * @property CarbonImmutable|null $updated_at
 * @property CarbonImmutable|null $deleted_at
 * @property CarbonImmutable|null $synced_at
 * @property int|null $sync_seq
 * @property array<string, mixed>|null $extra
 * @property CarbonImmutable|null $portal_received_at
 */
final class TillSyncConflict extends Model
{
    use BelongsToCompany, ScopedToBranch, SoftDeletes, TillOwnedRow;

    public const TILL_ENTITY = 'SyncConflict';

    public $incrementing = false;

    public $timestamps = false;

    protected $table = 'till_sync_conflicts';

    protected $keyType = 'string';

    /**
     * @return array<string, string>
     */
    protected function casts(): array
    {
        return [
            'ownership' => TillEnumCast::class.':'.SyncOwnership::class,
            'hub_version' => 'integer',
            'branch_version' => 'integer',
            'detected_at' => UtcDateTimeCast::class,
            'resolution' => TillEnumCast::class.':'.SyncConflictResolution::class,
            'resolved_at' => UtcDateTimeCast::class,
            'row_version' => 'integer',
            'created_at' => UtcDateTimeCast::class,
            'updated_at' => UtcDateTimeCast::class,
            'deleted_at' => UtcDateTimeCast::class,
            'synced_at' => UtcDateTimeCast::class,
            'sync_seq' => 'integer',
            'extra' => 'array',
            'portal_received_at' => UtcDateTimeCast::class,
        ];
    }
}
