<?php

namespace App\Domain\TillData\Models;

use App\Domain\Shared\Casts\UtcDateTimeCast;
use App\Domain\Tenancy\Concerns\BelongsToCompany;
use App\Domain\TillData\Concerns\HubOwnedRow;
use Carbon\CarbonImmutable;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * Till entity `Role`: hub-owned (portal writes, tills apply), company scope. Table `till_roles`.
 *
 * @generated by `php artisan till:entities:generate` from
 * docs/contracts/portal-api-v1.4.1/docs/web-portal-api/schemas/entities/Role.schema.json and
 * app/Domain/TillData/definitions.php. Do not edit: change the definitions or a hand-written trait and regenerate.
 *
 * @property string $id
 * @property string $company_id
 * @property string $name
 * @property int $level
 * @property bool $is_system
 * @property bool $simple_mode_default
 * @property array<mixed>|null $permissions
 * @property int $row_version
 * @property CarbonImmutable|null $created_at
 * @property CarbonImmutable|null $updated_at
 * @property CarbonImmutable|null $deleted_at
 * @property int|null $hub_version
 * @property CarbonImmutable|null $hub_edited_at
 * @property string|null $hub_hash
 * @property string|null $origin_branch_id
 * @property CarbonImmutable|null $synced_at
 * @property int|null $sync_seq
 * @property array<string, mixed>|null $extra
 * @property CarbonImmutable|null $portal_received_at
 */
final class TillRole extends Model
{
    use BelongsToCompany, HubOwnedRow, SoftDeletes;

    public const TILL_ENTITY = 'Role';

    public $incrementing = false;

    public $timestamps = false;

    protected $table = 'till_roles';

    protected $keyType = 'string';

    /**
     * @return array<string, string>
     */
    protected function casts(): array
    {
        return [
            'level' => 'integer',
            'is_system' => 'boolean',
            'simple_mode_default' => 'boolean',
            'permissions' => 'array',
            'row_version' => 'integer',
            'created_at' => UtcDateTimeCast::class,
            'updated_at' => UtcDateTimeCast::class,
            'deleted_at' => UtcDateTimeCast::class,
            'hub_version' => 'integer',
            'hub_edited_at' => UtcDateTimeCast::class,
            'synced_at' => UtcDateTimeCast::class,
            'sync_seq' => 'integer',
            'extra' => 'array',
            'portal_received_at' => UtcDateTimeCast::class,
        ];
    }
}
