<?php

namespace App\Domain\TillData\Models;

use App\Domain\Shared\Casts\QuantityCast;
use App\Domain\Shared\Casts\UtcDateTimeCast;
use App\Domain\Tenancy\Concerns\BelongsToCompany;
use App\Domain\TillData\Concerns\ScopedToBranch;
use App\Domain\TillData\Concerns\TillOwnedRow;
use Carbon\CarbonImmutable;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * Till entity `TimesheetApproval`: branch-owned (read-only on the portal), branch scope. Table `timesheet_approvals`.
 *
 * @generated by `php artisan till:entities:generate` from
 * docs/contracts/portal-api-v1.1/schemas/entities/TimesheetApproval.schema.json and
 * app/Domain/TillData/definitions.php. Do not edit: change the definitions or a hand-written trait and regenerate.
 *
 * @property string $id
 * @property string $company_id
 * @property string|null $branch_id
 * @property string $user_id
 * @property CarbonImmutable $week_start
 * @property string $approved_by_user_id
 * @property CarbonImmutable $approved_at
 * @property string $total_hours
 * @property string $overtime_hours
 * @property int $row_version
 * @property CarbonImmutable|null $created_at
 * @property CarbonImmutable|null $updated_at
 * @property CarbonImmutable|null $deleted_at
 * @property CarbonImmutable|null $synced_at
 * @property int|null $sync_seq
 * @property array<string, mixed>|null $extra
 */
final class TimesheetApproval extends Model
{
    use BelongsToCompany, ScopedToBranch, SoftDeletes, TillOwnedRow;

    public const TILL_ENTITY = 'TimesheetApproval';

    public $incrementing = false;

    public $timestamps = false;

    protected $table = 'timesheet_approvals';

    protected $keyType = 'string';

    /**
     * @return array<string, string>
     */
    protected function casts(): array
    {
        return [
            'week_start' => 'immutable_date:Y-m-d',
            'approved_at' => UtcDateTimeCast::class,
            'total_hours' => QuantityCast::class,
            'overtime_hours' => QuantityCast::class,
            'row_version' => 'integer',
            'created_at' => UtcDateTimeCast::class,
            'updated_at' => UtcDateTimeCast::class,
            'deleted_at' => UtcDateTimeCast::class,
            'synced_at' => UtcDateTimeCast::class,
            'sync_seq' => 'integer',
            'extra' => 'array',
        ];
    }
}
