<?php

namespace App\Domain\TillData\Models;

use App\Domain\Shared\Casts\MoneyCast;
use App\Domain\Shared\Casts\QuantityCast;
use App\Domain\Shared\Casts\UtcDateTimeCast;
use App\Domain\Tenancy\Concerns\BelongsToCompany;
use App\Domain\TillData\Casts\TillEnumCast;
use App\Domain\TillData\Concerns\ScopedToBranch;
use App\Domain\TillData\Concerns\TillOwnedRow;
use App\Domain\TillData\Enums\VatReturnScheme;
use Carbon\CarbonImmutable;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * Till entity `VatReturn`: branch-owned (read-only on the portal), sender scope. Table `vat_returns`.
 *
 * @generated by `php artisan till:entities:generate` from
 * docs/contracts/portal-api-v1.1/schemas/entities/VatReturn.schema.json and
 * app/Domain/TillData/definitions.php. Do not edit: change the definitions or a hand-written trait and regenerate.
 *
 * @property string $id
 * @property string $company_id
 * @property string|null $branch_id
 * @property CarbonImmutable $period_start
 * @property CarbonImmutable $period_end
 * @property VatReturnScheme|null $scheme
 * @property string $flat_rate_percent
 * @property string $box1
 * @property string $box2
 * @property string $box3
 * @property string $box4
 * @property string $box5
 * @property string $box6
 * @property string $box7
 * @property string $box8
 * @property string $box9
 * @property CarbonImmutable $filed_at
 * @property string $filed_by_user_id
 * @property int $row_version
 * @property CarbonImmutable|null $created_at
 * @property CarbonImmutable|null $updated_at
 * @property CarbonImmutable|null $deleted_at
 * @property CarbonImmutable|null $synced_at
 * @property int|null $sync_seq
 * @property array<string, mixed>|null $extra
 */
final class VatReturn extends Model
{
    use BelongsToCompany, ScopedToBranch, SoftDeletes, TillOwnedRow;

    public const TILL_ENTITY = 'VatReturn';

    public $incrementing = false;

    public $timestamps = false;

    protected $table = 'vat_returns';

    protected $keyType = 'string';

    /**
     * @return array<string, string>
     */
    protected function casts(): array
    {
        return [
            'period_start' => 'immutable_date:Y-m-d',
            'period_end' => 'immutable_date:Y-m-d',
            'scheme' => TillEnumCast::class.':'.VatReturnScheme::class,
            'flat_rate_percent' => QuantityCast::class,
            'box1' => MoneyCast::class,
            'box2' => MoneyCast::class,
            'box3' => MoneyCast::class,
            'box4' => MoneyCast::class,
            'box5' => MoneyCast::class,
            'box6' => MoneyCast::class,
            'box7' => MoneyCast::class,
            'box8' => MoneyCast::class,
            'box9' => MoneyCast::class,
            'filed_at' => UtcDateTimeCast::class,
            'row_version' => 'integer',
            'created_at' => UtcDateTimeCast::class,
            'updated_at' => UtcDateTimeCast::class,
            'deleted_at' => UtcDateTimeCast::class,
            'synced_at' => UtcDateTimeCast::class,
            'sync_seq' => 'integer',
            'extra' => 'array',
        ];
    }
}
