<?php

namespace App\Domain\TillData\Enums;

/**
 * Till enum `AccountType` (the entity schemas). Used by Account.type.
 *
 * @generated by `php artisan till:entities:generate`
 * from docs/contracts/portal-api-v1.4.1/docs/web-portal-api. Do not edit.
 */
enum AccountType: string
{
    case Asset = 'asset';
    case Liability = 'liability';
    case Equity = 'equity';
    case Income = 'income';
    case Expense = 'expense';
}
