<?php

namespace App\Domain\TillData\Enums;

/**
 * Till enum `AgeRule` (samples/enums.json). Used by AgeRefusal.ageRule, Category.ageRuleDefault, Product.ageRule.
 *
 * @generated by `php artisan till:entities:generate`
 * from docs/contracts/portal-api-v1.1. Do not edit.
 */
enum AgeRule: string
{
    case None = 'none';
    case Over16 = 'over16';
    case Over18 = 'over18';
    case TobaccoGenerational = 'tobaccoGenerational';
    case Nicotine = 'nicotine';
    case Lottery18 = 'lottery18';
    case Knives18 = 'knives18';
    case Fireworks18 = 'fireworks18';
    case Solvents18 = 'solvents18';
    case EnergyDrink16 = 'energyDrink16';
    case Paracetamol16 = 'paracetamol16';
}
