<?php

namespace App\Domain\TillData\Enums;

/**
 * Till enum `BackupRunLayer` (the entity schemas). Used by BackupRun.layer.
 *
 * @generated by `php artisan till:entities:generate`
 * from docs/contracts/portal-api-v1.1. Do not edit.
 */
enum BackupRunLayer: string
{
    case Local = 'local';
    case ExternalFolder = 'externalFolder';
    case Cloud = 'cloud';
}
