<?php

namespace App\Domain\TillData\Enums;

/**
 * Till enum `BarcodeSource` (samples/enums.json). Used by ProductBarcode.source.
 *
 * @generated by `php artisan till:entities:generate`
 * from docs/contracts/portal-api-v1.1. Do not edit.
 */
enum BarcodeSource: string
{
    case Internal = 'internal';
    case Supplier = 'supplier';
    case Plu = 'plu';
    case Weighted = 'weighted';
    case Coupon = 'coupon';
    case Gs1 = 'gs1';
}
