<?php

namespace App\Domain\TillData\Enums;

/**
 * Till enum `CashCountStage` (the entity schemas). Used by CashCount.stage.
 *
 * @generated by `php artisan till:entities:generate`
 * from docs/contracts/portal-api-v1.3.1/docs/web-portal-api. Do not edit.
 */
enum CashCountStage: string
{
    case Open = 'open';
    case Close = 'close';
    case Spot = 'spot';
}
