<?php

namespace App\Domain\TillData\Enums;

/**
 * Till enum `CashOfficeBankingCollectionMethod` (the entity schemas). Used by CashOfficeBanking.collectionMethod.
 *
 * @generated by `php artisan till:entities:generate`
 * from docs/contracts/portal-api-v1.3.3/docs/web-portal-api. Do not edit.
 */
enum CashOfficeBankingCollectionMethod: string
{
    case OwnBanking = 'ownBanking';
    case Carrier = 'carrier';
}
