<?php

namespace App\Domain\TillData\Enums;

/**
 * Till enum `CashMovementType` (the entity schemas). Used by CashMovement.type.
 *
 * @generated by `php artisan till:entities:generate`
 * from docs/contracts/portal-api-v1.4.1/docs/web-portal-api. Do not edit.
 */
enum CashMovementType: string
{
    case OpeningFloat = 'openingFloat';
    case PaidIn = 'paidIn';
    case PaidOut = 'paidOut';
    case SafeDrop = 'safeDrop';
    case BankDrop = 'bankDrop';
    case FloatTopUp = 'floatTopUp';
    case ClosingCount = 'closingCount';
    case Sale = 'sale';
    case Refund = 'refund';
    case Counterfeit = 'counterfeit';
    case PettyCashOut = 'pettyCashOut';
    case PettyCashIn = 'pettyCashIn';
    case ChangeOrderReceived = 'changeOrderReceived';
    case CashReconciliationVariance = 'cashReconciliationVariance';
    case SafeBankDrop = 'safeBankDrop';
    case VoucherSale = 'voucherSale';
    case AccountPayment = 'accountPayment';
    case CustomerAdvance = 'customerAdvance';
    case CustomerAdvanceRefund = 'customerAdvanceRefund';
}
