<?php

namespace App\Domain\TillData\Enums;

/**
 * Till enum `ChangeOrderStatus` (the entity schemas). Used by ChangeOrder.status.
 *
 * @generated by `php artisan till:entities:generate`
 * from docs/contracts/portal-api-v1.3.3/docs/web-portal-api. Do not edit.
 */
enum ChangeOrderStatus: string
{
    case Requested = 'requested';
    case Received = 'received';
    case Cancelled = 'cancelled';
}
