<?php

namespace App\Domain\TillData\Enums;

/**
 * Till enum `ClockEventType` (the entity schemas). Used by ClockEvent.type.
 *
 * @generated by `php artisan till:entities:generate`
 * from docs/contracts/portal-api-v1.3.3/docs/web-portal-api. Do not edit.
 */
enum ClockEventType: string
{
    case In = 'in';
    case Out = 'out';
    case BreakStart = 'breakStart';
    case BreakEnd = 'breakEnd';
}
