<?php

namespace App\Domain\TillData\Enums;

/**
 * Till enum `ConsentChannel` (the entity schemas). Used by Consent.channel.
 *
 * @generated by `php artisan till:entities:generate`
 * from docs/contracts/portal-api-v1.4.1/docs/web-portal-api. Do not edit.
 */
enum ConsentChannel: string
{
    case Email = 'email';
    case Sms = 'sms';
    case WhatsApp = 'whatsApp';
    case Post = 'post';
}
