<?php

namespace App\Domain\TillData\Enums;

/**
 * Till enum `ConsentSource` (the entity schemas). Used by Consent.source.
 *
 * @generated by `php artisan till:entities:generate`
 * from docs/contracts/portal-api-v1.3.3/docs/web-portal-api. Do not edit.
 */
enum ConsentSource: string
{
    case Till = 'till';
    case Web = 'web';
    case Form = 'form';
}
