<?php

namespace App\Domain\TillData\Enums;

/**
 * Till enum `CustomerOrderPaymentKind` (samples/enums.json). Used by CustomerOrderPayment.kind.
 *
 * @generated by `php artisan till:entities:generate`
 * from docs/contracts/portal-api-v1.3.3/docs/web-portal-api. Do not edit.
 */
enum CustomerOrderPaymentKind: string
{
    case Deposit = 'deposit';
    case PartPayment = 'partPayment';
    case Collection = 'collection';
    case Refund = 'refund';
}
