<?php

namespace App\Domain\TillData\Enums;

/**
 * Till enum `CustomerOrderStatus` (samples/enums.json). Used by CustomerOrder.status.
 *
 * @generated by `php artisan till:entities:generate`
 * from docs/contracts/portal-api-v1.1. Do not edit.
 */
enum CustomerOrderStatus: string
{
    case Ordered = 'ordered';
    case Ready = 'ready';
    case Collected = 'collected';
    case Cancelled = 'cancelled';
    case Expired = 'expired';
}
