<?php

namespace App\Domain\TillData\Enums;

/**
 * Till enum `DiaryCheckDefinitionSchedule` (the entity schemas). Used by DiaryCheckDefinition.schedule.
 *
 * @generated by `php artisan till:entities:generate`
 * from docs/contracts/portal-api-v1.3.1/docs/web-portal-api. Do not edit.
 */
enum DiaryCheckDefinitionSchedule: string
{
    case Daily = 'daily';
    case PerShift = 'perShift';
    case Weekly = 'weekly';
}
