<?php

namespace App\Domain\TillData\Enums;

/**
 * Till enum `DiscountSource` (samples/enums.json). Used by PromotionRedemption.source, SaleLine.discountSource.
 *
 * @generated by `php artisan till:entities:generate`
 * from docs/contracts/portal-api-v1.3.1/docs/web-portal-api. Do not edit.
 */
enum DiscountSource: string
{
    case Manual = 'manual';
    case Promotion = 'promotion';
    case CustomerGroup = 'customerGroup';
    case Staff = 'staff';
    case Coupon = 'coupon';
}
