<?php

namespace App\Domain\TillData\Enums;

/**
 * Till enum `DispensingRecordChargeStatus` (the entity schemas). Used by DispensingRecord.chargeStatus.
 *
 * @generated by `php artisan till:entities:generate`
 * from docs/contracts/portal-api-v1.3.1/docs/web-portal-api. Do not edit.
 */
enum DispensingRecordChargeStatus: string
{
    case Paid = 'paid';
    case Exempt = 'exempt';
    case Private = 'private';
}
