<?php

namespace App\Domain\TillData\Enums;

/**
 * Till enum `EReceiptLogChannel` (the entity schemas). Used by EReceiptLog.channel.
 *
 * @generated by `php artisan till:entities:generate`
 * from docs/contracts/portal-api-v1.3.3/docs/web-portal-api. Do not edit.
 */
enum EReceiptLogChannel: string
{
    case Email = 'email';
    case WhatsApp = 'whatsApp';
}
