<?php

namespace App\Domain\TillData\Enums;

/**
 * Till enum `ExpensePaymentType` (the entity schemas). Used by Expense.paymentType, RecurringBill.paymentType.
 *
 * @generated by `php artisan till:entities:generate`
 * from docs/contracts/portal-api-v1.1. Do not edit.
 */
enum ExpensePaymentType: string
{
    case Cash = 'cash';
    case Card = 'card';
    case Bank = 'bank';
    case Owner = 'owner';
}
