<?php

namespace App\Domain\TillData\Enums;

/**
 * Till enum `FinancialPeriodStatus` (the entity schemas). Used by FinancialPeriod.status.
 *
 * @generated by `php artisan till:entities:generate`
 * from docs/contracts/portal-api-v1.1. Do not edit.
 */
enum FinancialPeriodStatus: string
{
    case Open = 'open';
    case Closed = 'closed';
    case Locked = 'locked';
}
