<?php

namespace App\Domain\TillData\Enums;

/**
 * Till enum `HardwareCheckKind` (the entity schemas). Used by HardwareCheck.kind.
 *
 * @generated by `php artisan till:entities:generate`
 * from docs/contracts/portal-api-v1.4.1/docs/web-portal-api. Do not edit.
 */
enum HardwareCheckKind: string
{
    case ReceiptPrinter = 'receiptPrinter';
    case CashDrawer = 'cashDrawer';
    case Scanner = 'scanner';
    case Scale = 'scale';
    case LabelPrinter = 'labelPrinter';
    case PaymentTerminal = 'paymentTerminal';
    case CustomerDisplay = 'customerDisplay';
    case Cctv = 'cctv';
}
