<?php

namespace App\Domain\TillData\Enums;

/**
 * Till enum `ImportJobStatus` (the entity schemas). Used by ImportJob.status.
 *
 * @generated by `php artisan till:entities:generate`
 * from docs/contracts/portal-api-v1.3.3/docs/web-portal-api. Do not edit.
 */
enum ImportJobStatus: string
{
    case Running = 'running';
    case Completed = 'completed';
    case Cancelled = 'cancelled';
    case Failed = 'failed';
}
