<?php

namespace App\Domain\TillData\Enums;

/**
 * Till enum `MedicineClassificationClass` (the entity schemas). Used by MedicineClassification.class.
 *
 * @generated by `php artisan till:entities:generate`
 * from docs/contracts/portal-api-v1.3.1/docs/web-portal-api. Do not edit.
 */
enum MedicineClassificationClass: string
{
    case GeneralSale = 'generalSale';
    case PharmacyOnly = 'pharmacyOnly';
    case PrescriptionOnly = 'prescriptionOnly';
}
