<?php

namespace App\Domain\TillData\Enums;

/**
 * Till enum `NegativeStockPolicy` (samples/enums.json). Used by Category.negativeStockMode, Product.negativeStockMode.
 *
 * @generated by `php artisan till:entities:generate`
 * from docs/contracts/portal-api-v1.4.1/docs/web-portal-api. Do not edit.
 */
enum NegativeStockPolicy: string
{
    case Allow = 'allow';
    case Warn = 'warn';
    case Block = 'block';
}
