<?php

namespace App\Domain\TillData\Enums;

/**
 * Till enum `NewsTitleFrequency` (the entity schemas). Used by NewsTitle.frequency.
 *
 * @generated by `php artisan till:entities:generate`
 * from docs/contracts/portal-api-v1.4.1/docs/web-portal-api. Do not edit.
 */
enum NewsTitleFrequency: string
{
    case Daily = 'daily';
    case Weekly = 'weekly';
    case PartWork = 'partWork';
}
