<?php

namespace App\Domain\TillData\Enums;

/**
 * Till enum `NewsDeliveryStatus` (the entity schemas). Used by NewsDelivery.status.
 *
 * @generated by `php artisan till:entities:generate`
 * from docs/contracts/portal-api-v1.1. Do not edit.
 */
enum NewsDeliveryStatus: string
{
    case Received = 'received';
    case PartReturned = 'partReturned';
    case Settled = 'settled';
}
