<?php

namespace App\Domain\TillData\Enums;

/**
 * Till enum `ParcelDirection` (the entity schemas). Used by Parcel.direction.
 *
 * @generated by `php artisan till:entities:generate`
 * from docs/contracts/portal-api-v1.3.1/docs/web-portal-api. Do not edit.
 */
enum ParcelDirection: string
{
    case DropOff = 'dropOff';
    case Collection = 'collection';
}
