<?php

namespace App\Domain\TillData\Enums;

/**
 * Till enum `ParcelStatus` (the entity schemas). Used by Parcel.status.
 *
 * @generated by `php artisan till:entities:generate`
 * from docs/contracts/portal-api-v1.3.1/docs/web-portal-api. Do not edit.
 */
enum ParcelStatus: string
{
    case Open = 'open';
    case HandedOver = 'handedOver';
}
