<?php

namespace App\Domain\TillData\Enums;

/**
 * Till enum `PaymentAttemptStatus` (the entity schemas). Used by PaymentAttempt.status.
 *
 * @generated by `php artisan till:entities:generate`
 * from docs/contracts/portal-api-v1.1. Do not edit.
 */
enum PaymentAttemptStatus: string
{
    case Requested = 'requested';
    case Approved = 'approved';
    case Declined = 'declined';
    case Timeout = 'timeout';
    case Unknown = 'unknown';
    case Recovered = 'recovered';
    case Reversed = 'reversed';
}
