<?php

namespace App\Domain\TillData\Enums;

/**
 * Till enum `PriceChangeBatchStatus` (the entity schemas). Used by PriceChangeBatch.status.
 *
 * @generated by `php artisan till:entities:generate`
 * from docs/contracts/portal-api-v1.1. Do not edit.
 */
enum PriceChangeBatchStatus: string
{
    case Draft = 'draft';
    case Approved = 'approved';
    case Scheduled = 'scheduled';
    case Live = 'live';
    case Cancelled = 'cancelled';
}
