<?php

namespace App\Domain\TillData\Enums;

/**
 * Till enum `PrinterProfileTransport` (the entity schemas). Used by PrinterProfile.transport.
 *
 * @generated by `php artisan till:entities:generate`
 * from docs/contracts/portal-api-v1.4.1/docs/web-portal-api. Do not edit.
 */
enum PrinterProfileTransport: string
{
    case Windows = 'windows';
    case Serial = 'serial';
    case Tcp = 'tcp';
    case File = 'file';
}
