<?php

namespace App\Domain\TillData\Enums;

/**
 * Till enum `PrinterProfileRole` (the entity schemas). Used by PrinterProfile.role.
 *
 * @generated by `php artisan till:entities:generate`
 * from docs/contracts/portal-api-v1.3.1/docs/web-portal-api. Do not edit.
 */
enum PrinterProfileRole: string
{
    case Receipt = 'receipt';
    case Token = 'token';
    case Label = 'label';
    case Report = 'report';
    case Kitchen = 'kitchen';
    case CashDrawer = 'cashDrawer';
    case A4Label = 'a4Label';
}
