<?php

namespace App\Domain\TillData\Enums;

/**
 * Till enum `PrintJobStatus` (the entity schemas). Used by PrintJob.status.
 *
 * @generated by `php artisan till:entities:generate`
 * from docs/contracts/portal-api-v1.3.3/docs/web-portal-api. Do not edit.
 */
enum PrintJobStatus: string
{
    case Queued = 'queued';
    case Printing = 'printing';
    case Printed = 'printed';
    case Failed = 'failed';
}
