<?php

namespace App\Domain\TillData\Enums;

/**
 * Till enum `ProductRecallStatus` (the entity schemas). Used by ProductRecall.status.
 *
 * @generated by `php artisan till:entities:generate`
 * from docs/contracts/portal-api-v1.3.1/docs/web-portal-api. Do not edit.
 */
enum ProductRecallStatus: string
{
    case Open = 'open';
    case Closed = 'closed';
}
