<?php

namespace App\Domain\TillData\Enums;

/**
 * Till enum `ProductAliasSource` (the entity schemas). Used by ProductAlias.source.
 *
 * @generated by `php artisan till:entities:generate`
 * from docs/contracts/portal-api-v1.4.1/docs/web-portal-api. Do not edit.
 */
enum ProductAliasSource: string
{
    case Manual = 'manual';
    case Learned = 'learned';
    case Import = 'import';
}
