<?php

namespace App\Domain\TillData\Enums;

/**
 * Till enum `PromotionType` (the entity schemas). Used by PromotionRedemption.type, PromotionRule.type.
 *
 * @generated by `php artisan till:entities:generate`
 * from docs/contracts/portal-api-v1.1. Do not edit.
 */
enum PromotionType: string
{
    case PercentOff = 'percentOff';
    case FixedOff = 'fixedOff';
    case FixedPrice = 'fixedPrice';
    case MultiBuy = 'multiBuy';
    case Bogof = 'bogof';
    case MixMatch = 'mixMatch';
    case MealDeal = 'mealDeal';
}
