<?php

namespace App\Domain\TillData\Enums;

/**
 * Till enum `PurchaseReturnLineReason` (the entity schemas). Used by PurchaseReturnLine.reason.
 *
 * @generated by `php artisan till:entities:generate`
 * from docs/contracts/portal-api-v1.4.1/docs/web-portal-api. Do not edit.
 */
enum PurchaseReturnLineReason: string
{
    case Damaged = 'damaged';
    case Wrong = 'wrong';
    case Expired = 'expired';
    case Recalled = 'recalled';
    case Other = 'other';
}
