<?php

namespace App\Domain\TillData\Enums;

/**
 * Till enum `RebateAgreementScope` (the entity schemas). Used by RebateAgreement.scope.
 *
 * @generated by `php artisan till:entities:generate`
 * from docs/contracts/portal-api-v1.3.1/docs/web-portal-api. Do not edit.
 */
enum RebateAgreementScope: string
{
    case Supplier = 'supplier';
    case Department = 'department';
    case Product = 'product';
}
