<?php

namespace App\Domain\TillData\Enums;

/**
 * Till enum `SaleStatus` (samples/enums.json). Used by Sale.status.
 *
 * @generated by `php artisan till:entities:generate`
 * from docs/contracts/portal-api-v1.1. Do not edit.
 */
enum SaleStatus: string
{
    case Open = 'open';
    case Held = 'held';
    case Completed = 'completed';
    case Voided = 'voided';
}
