<?php

namespace App\Domain\TillData\Enums;

/**
 * Till enum `SaleType` (samples/enums.json). Used by Sale.type.
 *
 * @generated by `php artisan till:entities:generate`
 * from docs/contracts/portal-api-v1.3.3/docs/web-portal-api. Do not edit.
 */
enum SaleType: string
{
    case Sale = 'sale';
    case Refund = 'refund';
    case Exchange = 'exchange';
    case Quote = 'quote';
    case Training = 'training';
    case Deposit = 'deposit';
}
