<?php

namespace App\Domain\TillData\Enums;

/**
 * Till enum `SalePaymentStatus` (samples/enums.json). Used by SalePayment.status.
 *
 * @generated by `php artisan till:entities:generate`
 * from docs/contracts/portal-api-v1.3.1/docs/web-portal-api. Do not edit.
 */
enum SalePaymentStatus: string
{
    case Approved = 'approved';
    case Reversed = 'reversed';
    case Recovered = 'recovered';
}
