<?php

namespace App\Domain\TillData\Enums;

/**
 * Till enum `SettingScope` (samples/enums.json). Used by Setting.scope.
 *
 * @generated by `php artisan till:entities:generate`
 * from docs/contracts/portal-api-v1.4.1/docs/web-portal-api. Do not edit.
 */
enum SettingScope: string
{
    case Company = 'company';
    case Branch = 'branch';
    case Register = 'register';
}
