<?php

namespace App\Domain\TillData\Enums;

/**
 * Till enum `ShiftStatus` (the entity schemas). Used by Shift.status.
 *
 * @generated by `php artisan till:entities:generate`
 * from docs/contracts/portal-api-v1.1. Do not edit.
 */
enum ShiftStatus: string
{
    case Open = 'open';
    case Closed = 'closed';
}
