<?php

namespace App\Domain\TillData\Enums;

/**
 * Till enum `ShopRoutineRunType` (the entity schemas). Used by ShopRoutineRun.type.
 *
 * @generated by `php artisan till:entities:generate`
 * from docs/contracts/portal-api-v1.1. Do not edit.
 */
enum ShopRoutineRunType: string
{
    case Close = 'close';
    case Open = 'open';
}
