<?php

namespace App\Domain\TillData\Enums;

/**
 * Till enum `ShopRoutineRunStatus` (the entity schemas). Used by ShopRoutineRun.status.
 *
 * @generated by `php artisan till:entities:generate`
 * from docs/contracts/portal-api-v1.4.1/docs/web-portal-api. Do not edit.
 */
enum ShopRoutineRunStatus: string
{
    case InProgress = 'inProgress';
    case Completed = 'completed';
    case Failed = 'failed';
}
