<?php

namespace App\Domain\TillData\Enums;

/**
 * Till enum `StockTakeStatus` (the entity schemas). Used by StockTake.status.
 *
 * @generated by `php artisan till:entities:generate`
 * from docs/contracts/portal-api-v1.1. Do not edit.
 */
enum StockTakeStatus: string
{
    case Draft = 'draft';
    case Counting = 'counting';
    case Review = 'review';
    case Approved = 'approved';
    case Cancelled = 'cancelled';
}
