<?php

namespace App\Domain\TillData\Enums;

/**
 * Till enum `StockTakeScope` (the entity schemas). Used by StockTake.scope.
 *
 * @generated by `php artisan till:entities:generate`
 * from docs/contracts/portal-api-v1.3.1/docs/web-portal-api. Do not edit.
 */
enum StockTakeScope: string
{
    case Branch = 'branch';
    case Department = 'department';
    case Category = 'category';
    case Supplier = 'supplier';
    case ProductList = 'productList';
}
