<?php

namespace App\Domain\TillData\Enums;

/**
 * Till enum `StockTransferStatus` (the entity schemas). Used by StockTransfer.status.
 *
 * @generated by `php artisan till:entities:generate`
 * from docs/contracts/portal-api-v1.3.1/docs/web-portal-api. Do not edit.
 */
enum StockTransferStatus: string
{
    case Requested = 'requested';
    case Dispatched = 'dispatched';
    case Received = 'received';
    case Closed = 'closed';
    case Cancelled = 'cancelled';
}
