<?php

namespace App\Domain\TillData\Enums;

/**
 * Till enum `StockMovementType` (samples/enums.json). Used by StockMovement.type.
 *
 * @generated by `php artisan till:entities:generate`
 * from docs/contracts/portal-api-v1.4.1/docs/web-portal-api. Do not edit.
 */
enum StockMovementType: string
{
    case Sale = 'sale';
    case Refund = 'refund';
    case Adjustment = 'adjustment';
    case Received = 'received';
    case Wastage = 'wastage';
    case Transfer = 'transfer';
    case StockTake = 'stockTake';
    case Damaged = 'damaged';
    case SupplierReturn = 'supplierReturn';
    case Expiry = 'expiry';
    case Theft = 'theft';
    case OpeningStock = 'openingStock';
    case PromotionSample = 'promotionSample';
}
