<?php

namespace App\Domain\TillData\Enums;

/**
 * Till enum `StoreCreditVoucherType` (the entity schemas). Used by StoreCreditVoucher.type.
 *
 * @generated by `php artisan till:entities:generate`
 * from docs/contracts/portal-api-v1.1. Do not edit.
 */
enum StoreCreditVoucherType: string
{
    case Gift = 'gift';
    case StoreCredit = 'storeCredit';
    case DrsRefund = 'drsRefund';
    case Loyalty = 'loyalty';
}
