<?php

namespace App\Domain\TillData\Enums;

/**
 * Till enum `SupplierPaymentAllocationTargetType` (the entity schemas). Used by SupplierPaymentAllocation.targetType.
 *
 * @generated by `php artisan till:entities:generate`
 * from docs/contracts/portal-api-v1.1. Do not edit.
 */
enum SupplierPaymentAllocationTargetType: string
{
    case Invoice = 'invoice';
    case CreditNote = 'creditNote';
}
