<?php

namespace App\Domain\TillData\Enums;

/**
 * Till enum `SupplierInvoiceStatus` (the entity schemas). Used by SupplierInvoice.status.
 *
 * @generated by `php artisan till:entities:generate`
 * from docs/contracts/portal-api-v1.1. Do not edit.
 */
enum SupplierInvoiceStatus: string
{
    case Draft = 'draft';
    case Matched = 'matched';
    case Approved = 'approved';
    case PartPaid = 'partPaid';
    case Paid = 'paid';
    case Disputed = 'disputed';
}
