<?php

namespace App\Domain\TillData\Enums;

/**
 * Till enum `SyncConflictResolution` (the entity schemas). Used by SyncConflict.resolution.
 *
 * @generated by `php artisan till:entities:generate`
 * from docs/contracts/portal-api-v1.1. Do not edit.
 */
enum SyncConflictResolution: string
{
    case Pending = 'pending';
    case HubWins = 'hubWins';
    case BranchWins = 'branchWins';
    case Ignored = 'ignored';
}
