<?php

namespace App\Domain\TillData\Enums;

/**
 * Till enum `SyncOwnership` (samples/enums.json). Used by SyncConflict.ownership.
 *
 * @generated by `php artisan till:entities:generate`
 * from docs/contracts/portal-api-v1.1. Do not edit.
 */
enum SyncOwnership: string
{
    case HubOwned = 'hubOwned';
    case BranchOwned = 'branchOwned';
}
