<?php

namespace App\Domain\TillData\Enums;

/**
 * Till enum `TaxRuleMode` (the entity schemas). Used by TaxRule.mode.
 *
 * @generated by `php artisan till:entities:generate`
 * from docs/contracts/portal-api-v1.3.3/docs/web-portal-api. Do not edit.
 */
enum TaxRuleMode: string
{
    case Include = 'include';
    case Exclude = 'exclude';
}
