<?php

namespace App\Domain\TillData\Enums;

/**
 * Till enum `TemperatureUnitKind` (the entity schemas). Used by TemperatureUnit.kind.
 *
 * @generated by `php artisan till:entities:generate`
 * from docs/contracts/portal-api-v1.3.3/docs/web-portal-api. Do not edit.
 */
enum TemperatureUnitKind: string
{
    case Fridge = 'fridge';
    case Freezer = 'freezer';
}
