<?php

namespace App\Domain\TillData\Enums;

/**
 * Till enum `UnitType` (samples/enums.json). Used by Product.unitType.
 *
 * @generated by `php artisan till:entities:generate`
 * from docs/contracts/portal-api-v1.1. Do not edit.
 */
enum UnitType: string
{
    case Pcs = 'pcs';
    case Kg = 'kg';
    case Open = 'open';
}
