<?php

namespace App\Domain\TillData\Enums;

/**
 * Till enum `UnitKind` (the entity schemas). Used by Unit.kind.
 *
 * @generated by `php artisan till:entities:generate`
 * from docs/contracts/portal-api-v1.3.3/docs/web-portal-api. Do not edit.
 */
enum UnitKind: string
{
    case Each = 'each';
    case Weight = 'weight';
    case Volume = 'volume';
    case Length = 'length';
    case Area = 'area';
    case Other = 'other';
}
