<?php

namespace App\Domain\TillData\Enums;

/**
 * Till enum `UpdateRunAction` (the entity schemas). Used by UpdateRun.action.
 *
 * @generated by `php artisan till:entities:generate`
 * from docs/contracts/portal-api-v1.1. Do not edit.
 */
enum UpdateRunAction: string
{
    case Checked = 'checked';
    case Downloaded = 'downloaded';
    case Installed = 'installed';
    case Refused = 'refused';
    case Migrated = 'migrated';
    case RolledBack = 'rolledBack';
    case VersionChanged = 'versionChanged';
    case NotesSeen = 'notesSeen';
}
