<?php

namespace App\Domain\TillData\Enums;

/**
 * Till enum `VatTreatment` (samples/enums.json). Used by VatRate.treatment.
 *
 * @generated by `php artisan till:entities:generate`
 * from docs/contracts/portal-api-v1.4.1/docs/web-portal-api. Do not edit.
 */
enum VatTreatment: string
{
    case Apply = 'apply';
    case Exempt = 'exempt';
    case OutOfScope = 'outOfScope';
}
