<?php

namespace App\Domain\TillData\Enums;

/**
 * Till enum `VoucherTransactionType` (the entity schemas). Used by VoucherTransaction.type.
 *
 * @generated by `php artisan till:entities:generate`
 * from docs/contracts/portal-api-v1.3.1/docs/web-portal-api. Do not edit.
 */
enum VoucherTransactionType: string
{
    case Issue = 'issue';
    case Activate = 'activate';
    case Redeem = 'redeem';
    case Reload = 'reload';
    case Expire = 'expire';
    case Cancel = 'cancel';
}
