<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

/**
 * Till entity store, tables new in contract 0.1.52: ProductRecallBranchState.
 *
 * @generated by `php artisan till:entities:generate` from docs/contracts/portal-api-v1.4.1/docs/web-portal-api
 * and app/Domain/TillData/definitions.php. Do not edit.
 */
return new class extends Migration
{
    public function up(): void
    {
        Schema::create('product_recall_branch_states', function (Blueprint $table) {
            $table->string('id', 26)->primary();
            $table->string('company_id', 26);
            $table->string('branch_id', 26)->nullable();
            $table->string('recall_id', 64)->nullable();
            $table->string('status', 40)->nullable();
            $table->string('closed_by_user_id', 64)->nullable();
            $table->dateTime('closed_at')->nullable();
            $table->text('note')->nullable();
            $table->unsignedBigInteger('row_version')->default(0);
            $table->dateTime('created_at')->nullable();
            $table->dateTime('updated_at')->nullable();
            $table->dateTime('deleted_at')->nullable();
            $table->dateTime('synced_at')->nullable();
            $table->unsignedBigInteger('sync_seq')->nullable();
            $table->json('extra')->nullable();
            $table->dateTime('portal_received_at')->nullable();

            $table->index(['company_id', 'updated_at'], 'product_recall_branch_states_company_id_updated_at_index');
            $table->index(['company_id', 'branch_id'], 'product_recall_branch_states_company_id_branch_id_index');
            $table->index(['company_id', 'recall_id', 'branch_id'], 'product_recall_branch_states_79efab21_idx');
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('product_recall_branch_states');
    }
};
