<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

/**
 * Till entity store, columns and indexes new in contract 0.1.52: 1 tables.
 *
 * @generated by `php artisan till:entities:generate` from docs/contracts/portal-api-v1.4.1/docs/web-portal-api
 * and app/Domain/TillData/definitions.php. Do not edit.
 */
return new class extends Migration
{
    public function up(): void
    {
        Schema::table('account_pay_dates', function (Blueprint $table) {
            $table->string('reminder_setup_key', 255)->nullable();
        });
    }

    public function down(): void
    {
        Schema::table('account_pay_dates', function (Blueprint $table) {
            $table->dropColumn(['reminder_setup_key']);
        });
    }
};
