<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

/**
 * Till entity store, tables new in contract 0.1.51: AccountPayDate.
 *
 * @generated by `php artisan till:entities:generate` from docs/contracts/portal-api-v1.4.1/docs/web-portal-api
 * and app/Domain/TillData/definitions.php. Do not edit.
 */
return new class extends Migration
{
    public function up(): void
    {
        Schema::create('account_pay_dates', function (Blueprint $table) {
            $table->string('id', 26)->primary();
            $table->string('company_id', 26);
            $table->string('branch_id', 26)->nullable();
            $table->string('customer_id', 64)->nullable();
            $table->string('sale_id', 64)->nullable();
            $table->dateTime('due_at')->nullable();
            $table->text('note')->nullable();
            $table->string('user_id', 64)->nullable();
            $table->dateTime('replaced_at')->nullable();
            $table->dateTime('reminder_sent_at')->nullable();
            $table->string('reminder_channel', 40)->nullable();
            $table->integer('reminder_attempts')->nullable();
            $table->dateTime('last_reminder_at')->nullable();
            $table->text('last_reminder_error')->nullable();
            $table->unsignedBigInteger('row_version')->default(0);
            $table->dateTime('created_at')->nullable();
            $table->dateTime('updated_at')->nullable();
            $table->dateTime('deleted_at')->nullable();
            $table->dateTime('synced_at')->nullable();
            $table->unsignedBigInteger('sync_seq')->nullable();
            $table->json('extra')->nullable();
            $table->dateTime('portal_received_at')->nullable();

            $table->index(['company_id', 'updated_at'], 'account_pay_dates_company_id_updated_at_index');
            $table->index(['company_id', 'branch_id'], 'account_pay_dates_company_id_branch_id_index');
            $table->index(['company_id', 'customer_id', 'replaced_at'], 'account_pay_dates_company_id_customer_id_replaced_at_index');
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('account_pay_dates');
    }
};
