<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

/**
 * Till entity store, group "stock": StockMovement, StockLayer, FifoStockLayer, StockReservation, StockTake, StockTakeSection, StockTakeLine, DateCheck.
 *
 * @generated by `php artisan till:entities:generate` from docs/contracts/portal-api-v1.1
 * and app/Domain/TillData/definitions.php. Do not edit.
 */
return new class extends Migration
{
    public function up(): void
    {
        Schema::create('stock_movements', function (Blueprint $table) {
            $table->string('id', 26)->primary();
            $table->string('company_id', 26);
            $table->string('branch_id', 26)->nullable();
            $table->string('register_id', 26)->nullable();
            $table->string('product_id', 64)->nullable();
            $table->string('type', 40)->nullable();
            $table->decimal('qty_delta', 14, 4)->nullable();
            $table->decimal('qty_before', 14, 4)->nullable();
            $table->decimal('qty_after', 14, 4)->nullable();
            $table->decimal('unit_cost', 14, 4)->nullable();
            $table->string('reason_id', 64)->nullable();
            $table->text('note')->nullable();
            $table->string('ref_type', 255)->nullable();
            $table->string('ref_id', 64)->nullable();
            $table->string('ref_line_id', 64)->nullable();
            $table->string('user_id', 64)->nullable();
            $table->dateTime('at')->nullable();
            $table->unsignedBigInteger('row_version')->default(0);
            $table->dateTime('created_at')->nullable();
            $table->dateTime('updated_at')->nullable();
            $table->dateTime('deleted_at')->nullable();
            $table->dateTime('synced_at')->nullable();
            $table->unsignedBigInteger('sync_seq')->nullable();
            $table->json('extra')->nullable();

            $table->index(['company_id', 'updated_at'], 'stock_movements_company_id_updated_at_index');
            $table->index(['company_id', 'branch_id'], 'stock_movements_company_id_branch_id_index');
            $table->index(['company_id', 'branch_id', 'product_id', 'at'], 'stock_movements_company_id_branch_id_product_id_at_index');
            $table->index(['ref_id'], 'stock_movements_ref_id_index');
        });

        Schema::create('stock_layers', function (Blueprint $table) {
            $table->string('id', 26)->primary();
            $table->string('company_id', 26);
            $table->string('branch_id', 26)->nullable();
            $table->string('product_id', 64)->nullable();
            $table->string('grn_line_id', 64)->nullable();
            $table->decimal('qty_remaining', 14, 4)->nullable();
            $table->decimal('unit_cost', 14, 4)->nullable();
            $table->dateTime('received_at')->nullable();
            $table->date('expiry_date')->nullable();
            $table->string('batch_no', 255)->nullable();
            $table->unsignedBigInteger('row_version')->default(0);
            $table->dateTime('created_at')->nullable();
            $table->dateTime('updated_at')->nullable();
            $table->dateTime('deleted_at')->nullable();
            $table->dateTime('synced_at')->nullable();
            $table->unsignedBigInteger('sync_seq')->nullable();
            $table->json('extra')->nullable();

            $table->index(['company_id', 'updated_at'], 'stock_layers_company_id_updated_at_index');
            $table->index(['company_id', 'branch_id'], 'stock_layers_company_id_branch_id_index');
            $table->index(['company_id', 'branch_id', 'product_id'], 'stock_layers_company_id_branch_id_product_id_index');
        });

        Schema::create('fifo_stock_layers', function (Blueprint $table) {
            $table->string('id', 26)->primary();
            $table->string('company_id', 26);
            $table->string('branch_id', 26)->nullable();
            $table->string('product_id', 64)->nullable();
            $table->dateTime('received_at')->nullable();
            $table->decimal('unit_cost', 14, 4)->nullable();
            $table->decimal('qty_remaining', 14, 4)->nullable();
            $table->string('ref_type', 255)->nullable();
            $table->string('ref_id', 64)->nullable();
            $table->unsignedBigInteger('row_version')->default(0);
            $table->dateTime('created_at')->nullable();
            $table->dateTime('updated_at')->nullable();
            $table->dateTime('deleted_at')->nullable();
            $table->dateTime('synced_at')->nullable();
            $table->unsignedBigInteger('sync_seq')->nullable();
            $table->json('extra')->nullable();

            $table->index(['company_id', 'updated_at'], 'fifo_stock_layers_company_id_updated_at_index');
            $table->index(['company_id', 'branch_id'], 'fifo_stock_layers_company_id_branch_id_index');
            $table->index(['company_id', 'branch_id', 'product_id'], 'fifo_stock_layers_company_id_branch_id_product_id_index');
        });

        Schema::create('stock_reservations', function (Blueprint $table) {
            $table->string('id', 26)->primary();
            $table->string('company_id', 26);
            $table->string('branch_id', 26)->nullable();
            $table->string('product_id', 64)->nullable();
            $table->decimal('qty', 14, 4)->nullable();
            $table->string('status', 40)->nullable();
            $table->string('order_id', 64)->nullable();
            $table->string('customer_name', 255)->nullable();
            $table->dateTime('expires_at')->nullable();
            $table->string('created_by_user_id', 64)->nullable();
            $table->dateTime('ended_at')->nullable();
            $table->text('ended_reason')->nullable();
            $table->text('note')->nullable();
            $table->unsignedBigInteger('row_version')->default(0);
            $table->dateTime('created_at')->nullable();
            $table->dateTime('updated_at')->nullable();
            $table->dateTime('deleted_at')->nullable();
            $table->dateTime('synced_at')->nullable();
            $table->unsignedBigInteger('sync_seq')->nullable();
            $table->json('extra')->nullable();

            $table->index(['company_id', 'updated_at'], 'stock_reservations_company_id_updated_at_index');
            $table->index(['company_id', 'branch_id'], 'stock_reservations_company_id_branch_id_index');
        });

        Schema::create('stock_takes', function (Blueprint $table) {
            $table->string('id', 26)->primary();
            $table->string('company_id', 26);
            $table->string('branch_id', 26)->nullable();
            $table->string('reference', 255)->nullable();
            $table->string('name', 255)->nullable();
            $table->string('scope', 40)->nullable();
            $table->string('scope_id', 64)->nullable();
            $table->string('status', 40)->nullable();
            $table->boolean('is_blind')->nullable();
            $table->boolean('count_uncounted_as_zero')->nullable();
            $table->string('started_by_user_id', 64)->nullable();
            $table->dateTime('started_at')->nullable();
            $table->string('approved_by_user_id', 64)->nullable();
            $table->dateTime('approved_at')->nullable();
            $table->dateTime('cancelled_at')->nullable();
            $table->decimal('recount_threshold_value', 12, 2)->nullable();
            $table->decimal('recount_threshold_percent', 9, 4)->nullable();
            $table->decimal('approval_over_value', 12, 2)->nullable();
            $table->text('note')->nullable();
            $table->boolean('is_high_value_count')->nullable();
            $table->unsignedBigInteger('row_version')->default(0);
            $table->dateTime('created_at')->nullable();
            $table->dateTime('updated_at')->nullable();
            $table->dateTime('deleted_at')->nullable();
            $table->dateTime('synced_at')->nullable();
            $table->unsignedBigInteger('sync_seq')->nullable();
            $table->json('extra')->nullable();

            $table->index(['company_id', 'updated_at'], 'stock_takes_company_id_updated_at_index');
            $table->index(['company_id', 'branch_id'], 'stock_takes_company_id_branch_id_index');
        });

        Schema::create('stock_take_sections', function (Blueprint $table) {
            $table->string('id', 26)->primary();
            $table->string('company_id', 26);
            $table->string('branch_id', 26)->nullable();
            $table->string('stock_take_id', 64)->nullable();
            $table->string('name', 255)->nullable();
            $table->string('assigned_user_id', 64)->nullable();
            $table->boolean('is_complete')->nullable();
            $table->unsignedBigInteger('row_version')->default(0);
            $table->dateTime('created_at')->nullable();
            $table->dateTime('updated_at')->nullable();
            $table->dateTime('deleted_at')->nullable();
            $table->dateTime('synced_at')->nullable();
            $table->unsignedBigInteger('sync_seq')->nullable();
            $table->json('extra')->nullable();

            $table->index(['company_id', 'updated_at'], 'stock_take_sections_company_id_updated_at_index');
            $table->index(['company_id', 'branch_id'], 'stock_take_sections_company_id_branch_id_index');
            $table->index(['stock_take_id'], 'stock_take_sections_stock_take_id_index');
        });

        Schema::create('stock_take_lines', function (Blueprint $table) {
            $table->string('id', 26)->primary();
            $table->string('company_id', 26);
            $table->string('branch_id', 26)->nullable();
            $table->string('stock_take_id', 64)->nullable();
            $table->string('product_id', 64)->nullable();
            $table->string('product_name', 255)->nullable();
            $table->string('section_id', 64)->nullable();
            $table->decimal('snapshot_qty', 14, 4)->nullable();
            $table->decimal('counted_qty', 14, 4)->nullable();
            $table->decimal('unit_cost', 14, 4)->nullable();
            $table->integer('count_count')->nullable();
            $table->string('counted_by_user_id', 64)->nullable();
            $table->dateTime('counted_at')->nullable();
            $table->text('note')->nullable();
            $table->boolean('recount_required')->nullable();
            $table->decimal('variance_qty', 14, 4)->nullable();
            $table->decimal('variance_cost', 14, 4)->nullable();
            $table->unsignedBigInteger('row_version')->default(0);
            $table->dateTime('created_at')->nullable();
            $table->dateTime('updated_at')->nullable();
            $table->dateTime('deleted_at')->nullable();
            $table->dateTime('synced_at')->nullable();
            $table->unsignedBigInteger('sync_seq')->nullable();
            $table->json('extra')->nullable();

            $table->index(['company_id', 'updated_at'], 'stock_take_lines_company_id_updated_at_index');
            $table->index(['company_id', 'branch_id'], 'stock_take_lines_company_id_branch_id_index');
            $table->index(['stock_take_id'], 'stock_take_lines_stock_take_id_index');
        });

        Schema::create('date_checks', function (Blueprint $table) {
            $table->string('id', 26)->primary();
            $table->string('company_id', 26);
            $table->string('branch_id', 26)->nullable();
            $table->string('stock_layer_id', 64)->nullable();
            $table->string('product_id', 64)->nullable();
            $table->string('checked_by_user_id', 64)->nullable();
            $table->dateTime('checked_at')->nullable();
            $table->string('action', 40)->nullable();
            $table->decimal('markdown_percent', 9, 4)->nullable();
            $table->text('note')->nullable();
            $table->unsignedBigInteger('row_version')->default(0);
            $table->dateTime('created_at')->nullable();
            $table->dateTime('updated_at')->nullable();
            $table->dateTime('deleted_at')->nullable();
            $table->dateTime('synced_at')->nullable();
            $table->unsignedBigInteger('sync_seq')->nullable();
            $table->json('extra')->nullable();

            $table->index(['company_id', 'updated_at'], 'date_checks_company_id_updated_at_index');
            $table->index(['company_id', 'branch_id'], 'date_checks_company_id_branch_id_index');
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('date_checks');
        Schema::dropIfExists('stock_take_lines');
        Schema::dropIfExists('stock_take_sections');
        Schema::dropIfExists('stock_takes');
        Schema::dropIfExists('stock_reservations');
        Schema::dropIfExists('fifo_stock_layers');
        Schema::dropIfExists('stock_layers');
        Schema::dropIfExists('stock_movements');
    }
};
