<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

/**
 * Till entity store, group "purchasing": Supplier, PurchaseOrder, PurchaseOrderLine, GoodsReceipt, GoodsReceiptLine, SupplierInvoice, SupplierInvoiceLine, SupplierCreditNote, SupplierCreditNoteLine, SupplierPayment, SupplierPaymentAllocation, StandingOrder, StandingOrderLine, RebateAgreement, RebateAccrual, NewsTitle, NewsDelivery, NewsDeliveryLine.
 *
 * @generated by `php artisan till:entities:generate` from docs/contracts/portal-api-v1.1
 * and app/Domain/TillData/definitions.php. Do not edit.
 */
return new class extends Migration
{
    public function up(): void
    {
        Schema::create('suppliers', function (Blueprint $table) {
            $table->string('id', 26)->primary();
            $table->string('company_id', 26);
            $table->string('name', 255)->nullable();
            $table->string('code', 255)->nullable();
            $table->boolean('is_active')->nullable();
            $table->string('contact_name', 255)->nullable();
            $table->string('phone', 255)->nullable();
            $table->string('email', 255)->nullable();
            $table->string('address_line1', 255)->nullable();
            $table->string('address_line2', 255)->nullable();
            $table->string('town', 255)->nullable();
            $table->string('postcode', 255)->nullable();
            $table->string('account_number', 255)->nullable();
            $table->string('terms_kind', 40)->nullable();
            $table->integer('payment_terms_days')->nullable();
            $table->integer('default_lead_days')->nullable();
            $table->decimal('minimum_order_value', 12, 2)->nullable();
            $table->string('order_method', 40)->nullable();
            $table->text('delivery_days')->nullable();
            $table->string('vat_number', 255)->nullable();
            $table->text('notes')->nullable();
            $table->unsignedBigInteger('row_version')->default(0);
            $table->dateTime('created_at')->nullable();
            $table->dateTime('updated_at')->nullable();
            $table->dateTime('deleted_at')->nullable();
            $table->unsignedBigInteger('hub_version')->nullable();
            $table->dateTime('hub_edited_at')->nullable();
            $table->dateTime('synced_at')->nullable();
            $table->unsignedBigInteger('sync_seq')->nullable();
            $table->json('extra')->nullable();

            $table->index(['company_id', 'updated_at'], 'suppliers_company_id_updated_at_index');
        });

        Schema::create('purchase_orders', function (Blueprint $table) {
            $table->string('id', 26)->primary();
            $table->string('company_id', 26);
            $table->string('branch_id', 26)->nullable();
            $table->string('supplier_id', 64)->nullable();
            $table->integer('number')->nullable();
            $table->string('status', 40)->nullable();
            $table->date('expected_date')->nullable();
            $table->dateTime('sent_at')->nullable();
            $table->string('sent_by_user_id', 64)->nullable();
            $table->dateTime('cancelled_at')->nullable();
            $table->string('cancelled_by_user_id', 64)->nullable();
            $table->text('cancel_reason')->nullable();
            $table->text('notes')->nullable();
            $table->decimal('net_total', 12, 2)->nullable();
            $table->decimal('vat_total', 12, 2)->nullable();
            $table->decimal('gross_total', 12, 2)->nullable();
            $table->decimal('discount_amount', 12, 2)->nullable();
            $table->string('discount_reason_id', 64)->nullable();
            $table->string('order_no', 255)->nullable();
            $table->unsignedBigInteger('row_version')->default(0);
            $table->dateTime('created_at')->nullable();
            $table->dateTime('updated_at')->nullable();
            $table->dateTime('deleted_at')->nullable();
            $table->dateTime('synced_at')->nullable();
            $table->unsignedBigInteger('sync_seq')->nullable();
            $table->json('extra')->nullable();

            $table->index(['company_id', 'updated_at'], 'purchase_orders_company_id_updated_at_index');
            $table->index(['company_id', 'branch_id'], 'purchase_orders_company_id_branch_id_index');
            $table->index(['company_id', 'supplier_id'], 'purchase_orders_company_id_supplier_id_index');
        });

        Schema::create('purchase_order_lines', function (Blueprint $table) {
            $table->string('id', 26)->primary();
            $table->string('company_id', 26);
            $table->string('branch_id', 26)->nullable();
            $table->string('purchase_order_id', 64)->nullable();
            $table->string('product_id', 64)->nullable();
            $table->integer('position')->nullable();
            $table->integer('ordered_cases')->nullable();
            $table->integer('case_qty_snapshot')->nullable();
            $table->decimal('ordered_units', 14, 4)->nullable();
            $table->decimal('unit_cost_snapshot', 14, 4)->nullable();
            $table->decimal('received_qty', 14, 4)->nullable();
            $table->string('vat_rate_id', 64)->nullable();
            $table->decimal('vat_percentage', 9, 4)->nullable();
            $table->unsignedBigInteger('row_version')->default(0);
            $table->dateTime('created_at')->nullable();
            $table->dateTime('updated_at')->nullable();
            $table->dateTime('deleted_at')->nullable();
            $table->dateTime('synced_at')->nullable();
            $table->unsignedBigInteger('sync_seq')->nullable();
            $table->json('extra')->nullable();

            $table->index(['company_id', 'updated_at'], 'purchase_order_lines_company_id_updated_at_index');
            $table->index(['company_id', 'branch_id'], 'purchase_order_lines_company_id_branch_id_index');
            $table->index(['purchase_order_id'], 'purchase_order_lines_purchase_order_id_index');
        });

        Schema::create('goods_receipts', function (Blueprint $table) {
            $table->string('id', 26)->primary();
            $table->string('company_id', 26);
            $table->string('branch_id', 26)->nullable();
            $table->string('supplier_id', 64)->nullable();
            $table->string('supplier_name', 255)->nullable();
            $table->string('purchase_order_id', 64)->nullable();
            $table->string('delivery_note_number', 255)->nullable();
            $table->date('received_date')->nullable();
            $table->string('status', 40)->nullable();
            $table->string('received_by_user_id', 64)->nullable();
            $table->decimal('net_amount', 12, 2)->nullable();
            $table->decimal('vat_amount', 12, 2)->nullable();
            $table->decimal('gross_amount', 12, 2)->nullable();
            $table->dateTime('posted_at')->nullable();
            $table->dateTime('cancelled_at')->nullable();
            $table->text('cancel_reason')->nullable();
            $table->text('note')->nullable();
            $table->unsignedBigInteger('row_version')->default(0);
            $table->dateTime('created_at')->nullable();
            $table->dateTime('updated_at')->nullable();
            $table->dateTime('deleted_at')->nullable();
            $table->dateTime('synced_at')->nullable();
            $table->unsignedBigInteger('sync_seq')->nullable();
            $table->json('extra')->nullable();

            $table->index(['company_id', 'updated_at'], 'goods_receipts_company_id_updated_at_index');
            $table->index(['company_id', 'branch_id'], 'goods_receipts_company_id_branch_id_index');
            $table->index(['company_id', 'supplier_id'], 'goods_receipts_company_id_supplier_id_index');
        });

        Schema::create('goods_receipt_lines', function (Blueprint $table) {
            $table->string('id', 26)->primary();
            $table->string('company_id', 26);
            $table->string('branch_id', 26)->nullable();
            $table->string('goods_receipt_id', 64)->nullable();
            $table->string('purchase_order_line_id', 64)->nullable();
            $table->string('product_id', 64)->nullable();
            $table->string('expected_product_id', 64)->nullable();
            $table->decimal('expected_qty', 14, 4)->nullable();
            $table->decimal('received_qty', 14, 4)->nullable();
            $table->integer('case_qty')->nullable();
            $table->decimal('unit_cost', 14, 4)->nullable();
            $table->string('vat_rate_id', 64)->nullable();
            $table->decimal('vat_percentage', 9, 4)->nullable();
            $table->boolean('is_short_or_over')->nullable();
            $table->text('note')->nullable();
            $table->date('expiry_date')->nullable();
            $table->string('batch_no', 255)->nullable();
            $table->unsignedBigInteger('row_version')->default(0);
            $table->dateTime('created_at')->nullable();
            $table->dateTime('updated_at')->nullable();
            $table->dateTime('deleted_at')->nullable();
            $table->dateTime('synced_at')->nullable();
            $table->unsignedBigInteger('sync_seq')->nullable();
            $table->json('extra')->nullable();

            $table->index(['company_id', 'updated_at'], 'goods_receipt_lines_company_id_updated_at_index');
            $table->index(['company_id', 'branch_id'], 'goods_receipt_lines_company_id_branch_id_index');
            $table->index(['goods_receipt_id'], 'goods_receipt_lines_goods_receipt_id_index');
        });

        Schema::create('supplier_invoices', function (Blueprint $table) {
            $table->string('id', 26)->primary();
            $table->string('company_id', 26);
            $table->string('branch_id', 26)->nullable();
            $table->string('supplier_id', 64)->nullable();
            $table->string('supplier_name', 255)->nullable();
            $table->string('invoice_number', 255)->nullable();
            $table->date('invoice_date')->nullable();
            $table->date('due_date')->nullable();
            $table->string('status', 40)->nullable();
            $table->decimal('net_amount', 12, 2)->nullable();
            $table->decimal('vat_amount', 12, 2)->nullable();
            $table->decimal('gross_amount', 12, 2)->nullable();
            $table->decimal('amount_paid', 12, 2)->nullable();
            $table->decimal('balance', 12, 2)->nullable();
            $table->text('variance_flags')->nullable();
            $table->dateTime('matched_at')->nullable();
            $table->dateTime('approved_at')->nullable();
            $table->string('approved_by_user_id', 64)->nullable();
            $table->dateTime('disputed_at')->nullable();
            $table->text('dispute_reason')->nullable();
            $table->text('attachment_path')->nullable();
            $table->text('notes')->nullable();
            $table->unsignedBigInteger('row_version')->default(0);
            $table->dateTime('created_at')->nullable();
            $table->dateTime('updated_at')->nullable();
            $table->dateTime('deleted_at')->nullable();
            $table->dateTime('synced_at')->nullable();
            $table->unsignedBigInteger('sync_seq')->nullable();
            $table->json('extra')->nullable();

            $table->index(['company_id', 'updated_at'], 'supplier_invoices_company_id_updated_at_index');
            $table->index(['company_id', 'branch_id'], 'supplier_invoices_company_id_branch_id_index');
            $table->index(['company_id', 'supplier_id'], 'supplier_invoices_company_id_supplier_id_index');
        });

        Schema::create('supplier_invoice_lines', function (Blueprint $table) {
            $table->string('id', 26)->primary();
            $table->string('company_id', 26);
            $table->string('branch_id', 26)->nullable();
            $table->string('supplier_invoice_id', 64)->nullable();
            $table->string('product_id', 64)->nullable();
            $table->text('description')->nullable();
            $table->decimal('qty', 14, 4)->nullable();
            $table->decimal('unit_cost', 14, 4)->nullable();
            $table->decimal('line_net', 12, 2)->nullable();
            $table->decimal('line_vat', 12, 2)->nullable();
            $table->string('vat_rate_id', 64)->nullable();
            $table->decimal('expected_qty', 14, 4)->nullable();
            $table->decimal('expected_unit_cost', 14, 4)->nullable();
            $table->boolean('has_qty_variance')->nullable();
            $table->boolean('has_price_variance')->nullable();
            $table->unsignedBigInteger('row_version')->default(0);
            $table->dateTime('created_at')->nullable();
            $table->dateTime('updated_at')->nullable();
            $table->dateTime('deleted_at')->nullable();
            $table->dateTime('synced_at')->nullable();
            $table->unsignedBigInteger('sync_seq')->nullable();
            $table->json('extra')->nullable();

            $table->index(['company_id', 'updated_at'], 'supplier_invoice_lines_company_id_updated_at_index');
            $table->index(['company_id', 'branch_id'], 'supplier_invoice_lines_company_id_branch_id_index');
            $table->index(['supplier_invoice_id'], 'supplier_invoice_lines_supplier_invoice_id_index');
        });

        Schema::create('supplier_credit_notes', function (Blueprint $table) {
            $table->string('id', 26)->primary();
            $table->string('company_id', 26);
            $table->string('branch_id', 26)->nullable();
            $table->string('supplier_id', 64)->nullable();
            $table->string('supplier_name', 255)->nullable();
            $table->string('credit_note_number', 255)->nullable();
            $table->date('credit_date')->nullable();
            $table->text('reason')->nullable();
            $table->string('linked_invoice_id', 64)->nullable();
            $table->decimal('net_amount', 12, 2)->nullable();
            $table->decimal('vat_amount', 12, 2)->nullable();
            $table->decimal('gross_amount', 12, 2)->nullable();
            $table->decimal('applied_amount', 12, 2)->nullable();
            $table->decimal('balance', 12, 2)->nullable();
            $table->text('notes')->nullable();
            $table->unsignedBigInteger('row_version')->default(0);
            $table->dateTime('created_at')->nullable();
            $table->dateTime('updated_at')->nullable();
            $table->dateTime('deleted_at')->nullable();
            $table->dateTime('synced_at')->nullable();
            $table->unsignedBigInteger('sync_seq')->nullable();
            $table->json('extra')->nullable();

            $table->index(['company_id', 'updated_at'], 'supplier_credit_notes_company_id_updated_at_index');
            $table->index(['company_id', 'branch_id'], 'supplier_credit_notes_company_id_branch_id_index');
            $table->index(['company_id', 'supplier_id'], 'supplier_credit_notes_company_id_supplier_id_index');
        });

        Schema::create('supplier_credit_note_lines', function (Blueprint $table) {
            $table->string('id', 26)->primary();
            $table->string('company_id', 26);
            $table->string('branch_id', 26)->nullable();
            $table->string('supplier_credit_note_id', 64)->nullable();
            $table->string('product_id', 64)->nullable();
            $table->text('description')->nullable();
            $table->decimal('qty', 14, 4)->nullable();
            $table->decimal('unit_cost', 14, 4)->nullable();
            $table->decimal('line_net', 12, 2)->nullable();
            $table->decimal('line_vat', 12, 2)->nullable();
            $table->unsignedBigInteger('row_version')->default(0);
            $table->dateTime('created_at')->nullable();
            $table->dateTime('updated_at')->nullable();
            $table->dateTime('deleted_at')->nullable();
            $table->dateTime('synced_at')->nullable();
            $table->unsignedBigInteger('sync_seq')->nullable();
            $table->json('extra')->nullable();

            $table->index(['company_id', 'updated_at'], 'supplier_credit_note_lines_company_id_updated_at_index');
            $table->index(['company_id', 'branch_id'], 'supplier_credit_note_lines_company_id_branch_id_index');
            $table->index(['supplier_credit_note_id'], 'supplier_credit_note_lines_supplier_credit_note_id_index');
        });

        Schema::create('supplier_payments', function (Blueprint $table) {
            $table->string('id', 26)->primary();
            $table->string('company_id', 26);
            $table->string('branch_id', 26)->nullable();
            $table->string('supplier_id', 64)->nullable();
            $table->string('supplier_name', 255)->nullable();
            $table->date('payment_date')->nullable();
            $table->string('method', 40)->nullable();
            $table->string('reference', 255)->nullable();
            $table->decimal('amount', 12, 2)->nullable();
            $table->decimal('allocated_amount', 12, 2)->nullable();
            $table->decimal('unallocated', 12, 2)->nullable();
            $table->text('notes')->nullable();
            $table->boolean('is_reversed')->nullable();
            $table->dateTime('reversed_at')->nullable();
            $table->string('reversed_by_user_id', 64)->nullable();
            $table->unsignedBigInteger('row_version')->default(0);
            $table->dateTime('created_at')->nullable();
            $table->dateTime('updated_at')->nullable();
            $table->dateTime('deleted_at')->nullable();
            $table->dateTime('synced_at')->nullable();
            $table->unsignedBigInteger('sync_seq')->nullable();
            $table->json('extra')->nullable();

            $table->index(['company_id', 'updated_at'], 'supplier_payments_company_id_updated_at_index');
            $table->index(['company_id', 'branch_id'], 'supplier_payments_company_id_branch_id_index');
            $table->index(['company_id', 'supplier_id'], 'supplier_payments_company_id_supplier_id_index');
        });

        Schema::create('supplier_payment_allocations', function (Blueprint $table) {
            $table->string('id', 26)->primary();
            $table->string('company_id', 26);
            $table->string('branch_id', 26)->nullable();
            $table->string('supplier_payment_id', 64)->nullable();
            $table->string('target_type', 40)->nullable();
            $table->string('target_id', 64)->nullable();
            $table->decimal('amount', 12, 2)->nullable();
            $table->dateTime('allocated_at')->nullable();
            $table->boolean('is_reversed')->nullable();
            $table->dateTime('reversed_at')->nullable();
            $table->unsignedBigInteger('row_version')->default(0);
            $table->dateTime('created_at')->nullable();
            $table->dateTime('updated_at')->nullable();
            $table->dateTime('deleted_at')->nullable();
            $table->dateTime('synced_at')->nullable();
            $table->unsignedBigInteger('sync_seq')->nullable();
            $table->json('extra')->nullable();

            $table->index(['company_id', 'updated_at'], 'supplier_payment_allocations_company_id_updated_at_index');
            $table->index(['company_id', 'branch_id'], 'supplier_payment_allocations_company_id_branch_id_index');
            $table->index(['supplier_payment_id'], 'supplier_payment_allocations_supplier_payment_id_index');
        });

        Schema::create('standing_orders', function (Blueprint $table) {
            $table->string('id', 26)->primary();
            $table->string('company_id', 26);
            $table->string('branch_id', 26)->nullable();
            $table->string('supplier_id', 64)->nullable();
            $table->string('name', 255)->nullable();
            $table->text('weekdays')->nullable();
            $table->boolean('is_active')->nullable();
            $table->date('last_generated_on')->nullable();
            $table->text('note')->nullable();
            $table->unsignedBigInteger('row_version')->default(0);
            $table->dateTime('created_at')->nullable();
            $table->dateTime('updated_at')->nullable();
            $table->dateTime('deleted_at')->nullable();
            $table->dateTime('synced_at')->nullable();
            $table->unsignedBigInteger('sync_seq')->nullable();
            $table->json('extra')->nullable();

            $table->index(['company_id', 'updated_at'], 'standing_orders_company_id_updated_at_index');
            $table->index(['company_id', 'branch_id'], 'standing_orders_company_id_branch_id_index');
        });

        Schema::create('standing_order_lines', function (Blueprint $table) {
            $table->string('id', 26)->primary();
            $table->string('company_id', 26);
            $table->string('branch_id', 26)->nullable();
            $table->string('standing_order_id', 64)->nullable();
            $table->string('product_id', 64)->nullable();
            $table->decimal('qty', 14, 4)->nullable();
            $table->decimal('unit_cost', 14, 4)->nullable();
            $table->text('note')->nullable();
            $table->unsignedBigInteger('row_version')->default(0);
            $table->dateTime('created_at')->nullable();
            $table->dateTime('updated_at')->nullable();
            $table->dateTime('deleted_at')->nullable();
            $table->dateTime('synced_at')->nullable();
            $table->unsignedBigInteger('sync_seq')->nullable();
            $table->json('extra')->nullable();

            $table->index(['company_id', 'updated_at'], 'standing_order_lines_company_id_updated_at_index');
            $table->index(['company_id', 'branch_id'], 'standing_order_lines_company_id_branch_id_index');
            $table->index(['standing_order_id'], 'standing_order_lines_standing_order_id_index');
        });

        Schema::create('rebate_agreements', function (Blueprint $table) {
            $table->string('id', 26)->primary();
            $table->string('company_id', 26);
            $table->string('supplier_id', 64)->nullable();
            $table->string('name', 255)->nullable();
            $table->string('scope', 40)->nullable();
            $table->string('scope_id', 64)->nullable();
            $table->string('basis', 40)->nullable();
            $table->decimal('rate', 14, 4)->nullable();
            $table->date('period_from')->nullable();
            $table->date('period_to')->nullable();
            $table->decimal('threshold', 12, 2)->nullable();
            $table->boolean('is_active')->nullable();
            $table->text('note')->nullable();
            $table->unsignedBigInteger('row_version')->default(0);
            $table->dateTime('created_at')->nullable();
            $table->dateTime('updated_at')->nullable();
            $table->dateTime('deleted_at')->nullable();
            $table->unsignedBigInteger('hub_version')->nullable();
            $table->dateTime('hub_edited_at')->nullable();
            $table->dateTime('synced_at')->nullable();
            $table->unsignedBigInteger('sync_seq')->nullable();
            $table->json('extra')->nullable();

            $table->index(['company_id', 'updated_at'], 'rebate_agreements_company_id_updated_at_index');
        });

        Schema::create('rebate_accruals', function (Blueprint $table) {
            $table->string('id', 26)->primary();
            $table->string('company_id', 26);
            $table->string('branch_id', 26)->nullable();
            $table->string('agreement_id', 64)->nullable();
            $table->string('supplier_id', 64)->nullable();
            $table->string('product_id', 64)->nullable();
            $table->decimal('qty', 14, 4)->nullable();
            $table->decimal('net_spend', 12, 2)->nullable();
            $table->decimal('amount', 12, 2)->nullable();
            $table->string('source_type', 255)->nullable();
            $table->string('source_id', 64)->nullable();
            $table->date('accrued_on')->nullable();
            $table->string('credit_note_id', 64)->nullable();
            $table->dateTime('settled_at')->nullable();
            $table->unsignedBigInteger('row_version')->default(0);
            $table->dateTime('created_at')->nullable();
            $table->dateTime('updated_at')->nullable();
            $table->dateTime('deleted_at')->nullable();
            $table->dateTime('synced_at')->nullable();
            $table->unsignedBigInteger('sync_seq')->nullable();
            $table->json('extra')->nullable();

            $table->index(['company_id', 'updated_at'], 'rebate_accruals_company_id_updated_at_index');
            $table->index(['company_id', 'branch_id'], 'rebate_accruals_company_id_branch_id_index');
        });

        Schema::create('news_titles', function (Blueprint $table) {
            $table->string('id', 26)->primary();
            $table->string('company_id', 26);
            $table->string('branch_id', 26)->nullable();
            $table->string('name', 255)->nullable();
            $table->string('frequency', 40)->nullable();
            $table->string('supplier_id', 64)->nullable();
            $table->decimal('cover_price', 12, 2)->nullable();
            $table->boolean('is_active')->nullable();
            $table->unsignedBigInteger('row_version')->default(0);
            $table->dateTime('created_at')->nullable();
            $table->dateTime('updated_at')->nullable();
            $table->dateTime('deleted_at')->nullable();
            $table->unsignedBigInteger('hub_version')->nullable();
            $table->dateTime('hub_edited_at')->nullable();
            $table->dateTime('synced_at')->nullable();
            $table->unsignedBigInteger('sync_seq')->nullable();
            $table->json('extra')->nullable();

            $table->index(['company_id', 'updated_at'], 'news_titles_company_id_updated_at_index');
            $table->index(['company_id', 'branch_id'], 'news_titles_company_id_branch_id_index');
        });

        Schema::create('news_deliveries', function (Blueprint $table) {
            $table->string('id', 26)->primary();
            $table->string('company_id', 26);
            $table->string('branch_id', 26)->nullable();
            $table->string('supplier_id', 64)->nullable();
            $table->string('supplier_name', 255)->nullable();
            $table->date('delivery_date')->nullable();
            $table->string('status', 40)->nullable();
            $table->dateTime('credit_posted_at')->nullable();
            $table->text('notes')->nullable();
            $table->unsignedBigInteger('row_version')->default(0);
            $table->dateTime('created_at')->nullable();
            $table->dateTime('updated_at')->nullable();
            $table->dateTime('deleted_at')->nullable();
            $table->dateTime('synced_at')->nullable();
            $table->unsignedBigInteger('sync_seq')->nullable();
            $table->json('extra')->nullable();

            $table->index(['company_id', 'updated_at'], 'news_deliveries_company_id_updated_at_index');
            $table->index(['company_id', 'branch_id'], 'news_deliveries_company_id_branch_id_index');
        });

        Schema::create('news_delivery_lines', function (Blueprint $table) {
            $table->string('id', 26)->primary();
            $table->string('company_id', 26);
            $table->string('branch_id', 26)->nullable();
            $table->string('delivery_id', 64)->nullable();
            $table->string('title_id', 64)->nullable();
            $table->string('title_name', 255)->nullable();
            $table->integer('qty_in')->nullable();
            $table->decimal('unit_cost', 14, 4)->nullable();
            $table->integer('qty_returned')->nullable();
            $table->integer('qty_sold')->nullable();
            $table->decimal('line_cost', 14, 4)->nullable();
            $table->decimal('return_value', 12, 2)->nullable();
            $table->unsignedBigInteger('row_version')->default(0);
            $table->dateTime('created_at')->nullable();
            $table->dateTime('updated_at')->nullable();
            $table->dateTime('deleted_at')->nullable();
            $table->dateTime('synced_at')->nullable();
            $table->unsignedBigInteger('sync_seq')->nullable();
            $table->json('extra')->nullable();

            $table->index(['company_id', 'updated_at'], 'news_delivery_lines_company_id_updated_at_index');
            $table->index(['company_id', 'branch_id'], 'news_delivery_lines_company_id_branch_id_index');
            $table->index(['delivery_id'], 'news_delivery_lines_delivery_id_index');
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('news_delivery_lines');
        Schema::dropIfExists('news_deliveries');
        Schema::dropIfExists('news_titles');
        Schema::dropIfExists('rebate_accruals');
        Schema::dropIfExists('rebate_agreements');
        Schema::dropIfExists('standing_order_lines');
        Schema::dropIfExists('standing_orders');
        Schema::dropIfExists('supplier_payment_allocations');
        Schema::dropIfExists('supplier_payments');
        Schema::dropIfExists('supplier_credit_note_lines');
        Schema::dropIfExists('supplier_credit_notes');
        Schema::dropIfExists('supplier_invoice_lines');
        Schema::dropIfExists('supplier_invoices');
        Schema::dropIfExists('goods_receipt_lines');
        Schema::dropIfExists('goods_receipts');
        Schema::dropIfExists('purchase_order_lines');
        Schema::dropIfExists('purchase_orders');
        Schema::dropIfExists('suppliers');
    }
};
