<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

/**
 * Till entity store, tables new in contract v1.4.1: BranchPrice, PurchaseReturn, PurchaseReturnLine, RolePermission, Setting.
 *
 * @generated by `php artisan till:entities:generate` from docs/contracts/portal-api-v1.4.1/docs/web-portal-api
 * and app/Domain/TillData/definitions.php. Do not edit.
 */
return new class extends Migration
{
    public function up(): void
    {
        Schema::create('branch_prices', function (Blueprint $table) {
            $table->string('id', 26)->primary();
            $table->string('company_id', 26);
            $table->string('branch_id', 26)->nullable();
            $table->string('product_id', 64)->nullable();
            $table->string('product_unit_id', 64)->nullable();
            $table->decimal('price', 12, 2)->nullable();
            $table->dateTime('valid_from_utc')->nullable();
            $table->dateTime('valid_to_utc')->nullable();
            $table->unsignedBigInteger('row_version')->default(0);
            $table->dateTime('created_at')->nullable();
            $table->dateTime('updated_at')->nullable();
            $table->dateTime('deleted_at')->nullable();
            $table->unsignedBigInteger('hub_version')->nullable();
            $table->dateTime('hub_edited_at')->nullable();
            $table->char('hub_hash', 64)->nullable();
            $table->string('origin_branch_id', 26)->nullable();
            $table->dateTime('synced_at')->nullable();
            $table->unsignedBigInteger('sync_seq')->nullable();
            $table->json('extra')->nullable();
            $table->dateTime('portal_received_at')->nullable();

            $table->index(['company_id', 'updated_at'], 'branch_prices_company_id_updated_at_index');
            $table->index(['company_id', 'branch_id'], 'branch_prices_company_id_branch_id_index');
            $table->index(['product_id'], 'branch_prices_product_id_index');
            $table->index(['company_id', 'branch_id', 'product_id', 'valid_from_utc'], 'branch_prices_469b9308_idx');
        });

        Schema::create('purchase_returns', function (Blueprint $table) {
            $table->string('id', 26)->primary();
            $table->string('company_id', 26);
            $table->string('branch_id', 26)->nullable();
            $table->string('supplier_id', 64)->nullable();
            $table->string('supplier_name', 255)->nullable();
            $table->integer('number')->nullable();
            $table->string('reference', 255)->nullable();
            $table->string('status', 40)->nullable();
            $table->date('return_date')->nullable();
            $table->string('goods_receipt_id', 64)->nullable();
            $table->string('purchase_order_id', 64)->nullable();
            $table->decimal('net_amount', 12, 2)->nullable();
            $table->decimal('vat_amount', 12, 2)->nullable();
            $table->decimal('gross_amount', 12, 2)->nullable();
            $table->string('created_by_user_id', 64)->nullable();
            $table->dateTime('sent_at')->nullable();
            $table->string('sent_by_user_id', 64)->nullable();
            $table->string('credit_note_number', 255)->nullable();
            $table->date('credit_date')->nullable();
            $table->dateTime('credited_at')->nullable();
            $table->string('supplier_credit_note_id', 64)->nullable();
            $table->dateTime('cancelled_at')->nullable();
            $table->text('note')->nullable();
            $table->unsignedBigInteger('row_version')->default(0);
            $table->dateTime('created_at')->nullable();
            $table->dateTime('updated_at')->nullable();
            $table->dateTime('deleted_at')->nullable();
            $table->dateTime('synced_at')->nullable();
            $table->unsignedBigInteger('sync_seq')->nullable();
            $table->json('extra')->nullable();
            $table->dateTime('portal_received_at')->nullable();

            $table->index(['company_id', 'updated_at'], 'purchase_returns_company_id_updated_at_index');
            $table->index(['company_id', 'branch_id'], 'purchase_returns_company_id_branch_id_index');
            $table->index(['company_id', 'supplier_id'], 'purchase_returns_company_id_supplier_id_index');
            $table->index(['company_id', 'goods_receipt_id'], 'purchase_returns_company_id_goods_receipt_id_index');
        });

        Schema::create('purchase_return_lines', function (Blueprint $table) {
            $table->string('id', 26)->primary();
            $table->string('company_id', 26);
            $table->string('branch_id', 26)->nullable();
            $table->string('purchase_return_id', 64)->nullable();
            $table->string('product_id', 64)->nullable();
            $table->string('product_name', 255)->nullable();
            $table->decimal('qty', 14, 4)->nullable();
            $table->decimal('unit_cost', 14, 4)->nullable();
            $table->string('vat_rate_id', 64)->nullable();
            $table->decimal('vat_percentage', 9, 4)->nullable();
            $table->string('reason', 40)->nullable();
            $table->boolean('from_stock')->nullable();
            $table->string('goods_receipt_line_id', 64)->nullable();
            $table->decimal('line_net', 12, 2)->nullable();
            $table->decimal('line_vat', 12, 2)->nullable();
            $table->text('note')->nullable();
            $table->unsignedBigInteger('row_version')->default(0);
            $table->dateTime('created_at')->nullable();
            $table->dateTime('updated_at')->nullable();
            $table->dateTime('deleted_at')->nullable();
            $table->dateTime('synced_at')->nullable();
            $table->unsignedBigInteger('sync_seq')->nullable();
            $table->json('extra')->nullable();
            $table->dateTime('portal_received_at')->nullable();

            $table->index(['company_id', 'updated_at'], 'purchase_return_lines_company_id_updated_at_index');
            $table->index(['company_id', 'branch_id'], 'purchase_return_lines_company_id_branch_id_index');
            $table->index(['purchase_return_id'], 'purchase_return_lines_purchase_return_id_index');
            $table->index(['company_id', 'product_id'], 'purchase_return_lines_company_id_product_id_index');
        });

        Schema::create('till_role_permissions', function (Blueprint $table) {
            $table->string('id', 26)->primary();
            $table->string('company_id', 26);
            $table->string('role_id', 64)->nullable();
            $table->string('permission_key', 255)->nullable();
            $table->unsignedBigInteger('row_version')->default(0);
            $table->dateTime('created_at')->nullable();
            $table->dateTime('updated_at')->nullable();
            $table->dateTime('deleted_at')->nullable();
            $table->unsignedBigInteger('hub_version')->nullable();
            $table->dateTime('hub_edited_at')->nullable();
            $table->char('hub_hash', 64)->nullable();
            $table->string('origin_branch_id', 26)->nullable();
            $table->dateTime('synced_at')->nullable();
            $table->unsignedBigInteger('sync_seq')->nullable();
            $table->json('extra')->nullable();
            $table->dateTime('portal_received_at')->nullable();

            $table->index(['company_id', 'updated_at'], 'till_role_permissions_company_id_updated_at_index');
            $table->index(['company_id', 'role_id'], 'till_role_permissions_company_id_role_id_index');
        });

        Schema::create('till_settings', function (Blueprint $table) {
            $table->string('id', 26)->primary();
            $table->string('company_id', 26);
            $table->string('scope', 40)->nullable();
            $table->string('scope_id', 64)->nullable();
            $table->string('setting_key', 255)->nullable();
            $table->text('value')->nullable();
            $table->unsignedBigInteger('row_version')->default(0);
            $table->dateTime('created_at')->nullable();
            $table->dateTime('updated_at')->nullable();
            $table->dateTime('deleted_at')->nullable();
            $table->unsignedBigInteger('hub_version')->nullable();
            $table->dateTime('hub_edited_at')->nullable();
            $table->char('hub_hash', 64)->nullable();
            $table->string('origin_branch_id', 26)->nullable();
            $table->dateTime('synced_at')->nullable();
            $table->unsignedBigInteger('sync_seq')->nullable();
            $table->json('extra')->nullable();
            $table->dateTime('portal_received_at')->nullable();

            $table->index(['company_id', 'updated_at'], 'till_settings_company_id_updated_at_index');
            $table->index(['company_id', 'scope', 'scope_id', 'setting_key'], 'till_settings_company_id_scope_scope_id_setting_key_index');
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('till_settings');
        Schema::dropIfExists('till_role_permissions');
        Schema::dropIfExists('purchase_return_lines');
        Schema::dropIfExists('purchase_returns');
        Schema::dropIfExists('branch_prices');
    }
};
