<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

/**
 * Till entity store, columns and indexes new in contract 0.1.51: 4 tables.
 *
 * @generated by `php artisan till:entities:generate` from docs/contracts/portal-api-v1.4.1/docs/web-portal-api
 * and app/Domain/TillData/definitions.php. Do not edit.
 */
return new class extends Migration
{
    public function up(): void
    {
        Schema::table('customers', function (Blueprint $table) {
            $table->integer('pending_points')->nullable();
            $table->boolean('earns_points')->nullable();
        });

        Schema::table('customer_transactions', function (Blueprint $table) {
            $table->string('tender', 255)->nullable();
            $table->string('register_id', 64)->nullable();
            $table->string('shift_id', 64)->nullable();
        });

        Schema::table('customer_orders', function (Blueprint $table) {
            $table->string('customer_id', 64)->nullable();
        });

        Schema::table('rota_shifts', function (Blueprint $table) {
            $table->boolean('ends_next_day')->nullable();
        });
    }

    public function down(): void
    {
        Schema::table('rota_shifts', function (Blueprint $table) {
            $table->dropColumn(['ends_next_day']);
        });

        Schema::table('customer_orders', function (Blueprint $table) {
            $table->dropColumn(['customer_id']);
        });

        Schema::table('customer_transactions', function (Blueprint $table) {
            $table->dropColumn(['tender', 'register_id', 'shift_id']);
        });

        Schema::table('customers', function (Blueprint $table) {
            $table->dropColumn(['pending_points', 'earns_points']);
        });
    }
};
