<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

/**
 * Till entity store, group "catalogue": Department, Category, Unit, VatRate, TaxRule, Product, ProductBarcode, ProductAlias, ProductUnit, ProductSupplier, ProductRecall, PriceHistory, ExchangeRate, BranchProduct, PriceChangeBatch, PriceChangeLine, ScalePluItem, ShelfLabel, TopSellerTile, HighValueCountItem.
 *
 * @generated by `php artisan till:entities:generate` from docs/contracts/portal-api-v1.1
 * and app/Domain/TillData/definitions.php. Do not edit.
 */
return new class extends Migration
{
    public function up(): void
    {
        Schema::create('departments', function (Blueprint $table) {
            $table->string('id', 26)->primary();
            $table->string('company_id', 26);
            $table->string('name', 255)->nullable();
            $table->integer('position')->nullable();
            $table->string('colour_hex', 255)->nullable();
            $table->boolean('is_active')->nullable();
            $table->boolean('is_visible_on_till')->nullable();
            $table->boolean('show_in_report')->nullable();
            $table->string('default_vat_rate_id', 64)->nullable();
            $table->unsignedBigInteger('row_version')->default(0);
            $table->dateTime('created_at')->nullable();
            $table->dateTime('updated_at')->nullable();
            $table->dateTime('deleted_at')->nullable();
            $table->unsignedBigInteger('hub_version')->nullable();
            $table->dateTime('hub_edited_at')->nullable();
            $table->dateTime('synced_at')->nullable();
            $table->unsignedBigInteger('sync_seq')->nullable();
            $table->json('extra')->nullable();

            $table->index(['company_id', 'updated_at'], 'departments_company_id_updated_at_index');
        });

        Schema::create('categories', function (Blueprint $table) {
            $table->string('id', 26)->primary();
            $table->string('company_id', 26);
            $table->string('department_id', 64)->nullable();
            $table->string('parent_category_id', 64)->nullable();
            $table->string('name', 255)->nullable();
            $table->integer('position')->nullable();
            $table->string('colour_hex', 255)->nullable();
            $table->boolean('is_active')->nullable();
            $table->boolean('is_visible_on_till')->nullable();
            $table->string('age_rule_default', 40)->nullable();
            $table->string('default_vat_rate_id', 64)->nullable();
            $table->string('negative_stock_mode', 40)->nullable();
            $table->unsignedBigInteger('row_version')->default(0);
            $table->dateTime('created_at')->nullable();
            $table->dateTime('updated_at')->nullable();
            $table->dateTime('deleted_at')->nullable();
            $table->unsignedBigInteger('hub_version')->nullable();
            $table->dateTime('hub_edited_at')->nullable();
            $table->dateTime('synced_at')->nullable();
            $table->unsignedBigInteger('sync_seq')->nullable();
            $table->json('extra')->nullable();

            $table->index(['company_id', 'updated_at'], 'categories_company_id_updated_at_index');
        });

        Schema::create('units', function (Blueprint $table) {
            $table->string('id', 26)->primary();
            $table->string('company_id', 26);
            $table->string('code', 255)->nullable();
            $table->string('name', 255)->nullable();
            $table->string('plural', 255)->nullable();
            $table->string('kind', 40)->nullable();
            $table->boolean('decimals_allowed')->nullable();
            $table->boolean('is_active')->nullable();
            $table->boolean('is_system')->nullable();
            $table->integer('position')->nullable();
            $table->unsignedBigInteger('row_version')->default(0);
            $table->dateTime('created_at')->nullable();
            $table->dateTime('updated_at')->nullable();
            $table->dateTime('deleted_at')->nullable();
            $table->unsignedBigInteger('hub_version')->nullable();
            $table->dateTime('hub_edited_at')->nullable();
            $table->dateTime('synced_at')->nullable();
            $table->unsignedBigInteger('sync_seq')->nullable();
            $table->json('extra')->nullable();

            $table->index(['company_id', 'updated_at'], 'units_company_id_updated_at_index');
        });

        Schema::create('vat_rates', function (Blueprint $table) {
            $table->string('id', 26)->primary();
            $table->string('company_id', 26);
            $table->string('name', 255)->nullable();
            $table->string('code', 255)->nullable();
            $table->decimal('percentage', 9, 4)->nullable();
            $table->string('treatment', 40)->nullable();
            $table->date('effective_from')->nullable();
            $table->date('effective_to')->nullable();
            $table->boolean('is_default')->nullable();
            $table->boolean('is_zero_valued')->nullable();
            $table->unsignedBigInteger('row_version')->default(0);
            $table->dateTime('created_at')->nullable();
            $table->dateTime('updated_at')->nullable();
            $table->dateTime('deleted_at')->nullable();
            $table->unsignedBigInteger('hub_version')->nullable();
            $table->dateTime('hub_edited_at')->nullable();
            $table->dateTime('synced_at')->nullable();
            $table->unsignedBigInteger('sync_seq')->nullable();
            $table->json('extra')->nullable();

            $table->index(['company_id', 'updated_at'], 'vat_rates_company_id_updated_at_index');
        });

        Schema::create('tax_rules', function (Blueprint $table) {
            $table->string('id', 26)->primary();
            $table->string('company_id', 26);
            $table->string('scope', 40)->nullable();
            $table->string('target_id', 64)->nullable();
            $table->string('mode', 40)->nullable();
            $table->string('vat_rate_id', 64)->nullable();
            $table->integer('priority')->nullable();
            $table->date('effective_from')->nullable();
            $table->date('effective_to')->nullable();
            $table->text('note')->nullable();
            $table->boolean('is_active')->nullable();
            $table->unsignedBigInteger('row_version')->default(0);
            $table->dateTime('created_at')->nullable();
            $table->dateTime('updated_at')->nullable();
            $table->dateTime('deleted_at')->nullable();
            $table->unsignedBigInteger('hub_version')->nullable();
            $table->dateTime('hub_edited_at')->nullable();
            $table->dateTime('synced_at')->nullable();
            $table->unsignedBigInteger('sync_seq')->nullable();
            $table->json('extra')->nullable();

            $table->index(['company_id', 'updated_at'], 'tax_rules_company_id_updated_at_index');
        });

        Schema::create('products', function (Blueprint $table) {
            $table->string('id', 26)->primary();
            $table->string('company_id', 26);
            $table->string('name', 255)->nullable();
            $table->string('short_name', 255)->nullable();
            $table->string('sku', 255)->nullable();
            $table->string('brand', 255)->nullable();
            $table->text('description')->nullable();
            $table->string('department_id', 64)->nullable();
            $table->string('category_id', 64)->nullable();
            $table->string('sub_category_id', 64)->nullable();
            $table->string('parent_product_id', 64)->nullable();
            $table->string('variant_label', 255)->nullable();
            $table->string('unit_type', 40)->nullable();
            $table->string('unit_code', 255)->nullable();
            $table->string('vat_rate_id', 64)->nullable();
            $table->decimal('cost_price', 14, 4)->nullable();
            $table->decimal('sell_price', 12, 2)->nullable();
            $table->decimal('trade_price', 12, 2)->nullable();
            $table->decimal('pmp_price', 12, 2)->nullable();
            $table->boolean('track_stock')->nullable();
            $table->decimal('min_stock_qty', 14, 4)->nullable();
            $table->decimal('max_stock_qty', 14, 4)->nullable();
            $table->decimal('reorder_qty', 14, 4)->nullable();
            $table->string('negative_stock_mode', 40)->nullable();
            $table->string('bin_location', 255)->nullable();
            $table->string('age_rule', 40)->nullable();
            $table->integer('max_qty_per_sale')->nullable();
            $table->text('max_qty_reason')->nullable();
            $table->string('availability_from', 255)->nullable();
            $table->string('availability_to', 255)->nullable();
            $table->string('availability_seasonal_event_id', 64)->nullable();
            $table->boolean('tracks_expiry_dates')->nullable();
            $table->date('nearest_expiry_date')->nullable();
            $table->boolean('is_hfss')->nullable();
            $table->boolean('is_deposit_item')->nullable();
            $table->decimal('deposit_amount', 12, 2)->nullable();
            $table->boolean('is_alcohol')->nullable();
            $table->decimal('abv_percent', 9, 4)->nullable();
            $table->decimal('volume_ml', 14, 4)->nullable();
            $table->boolean('is_tobacco')->nullable();
            $table->boolean('is_lottery')->nullable();
            $table->boolean('is_knife')->nullable();
            $table->boolean('is_banned')->nullable();
            $table->boolean('vape_duty_applies')->nullable();
            $table->string('commodity_code', 255)->nullable();
            $table->decimal('net_mass_kg', 14, 4)->nullable();
            $table->string('tile_colour_hex', 255)->nullable();
            $table->text('image_path')->nullable();
            $table->string('tile_emoji', 255)->nullable();
            $table->integer('tile_position')->nullable();
            $table->boolean('is_active')->nullable();
            $table->dateTime('archived_at')->nullable();
            $table->string('merged_into_product_id', 64)->nullable();
            $table->boolean('is_variant_parent')->nullable();
            $table->string('variant1_name', 255)->nullable();
            $table->string('variant1_value', 255)->nullable();
            $table->string('variant2_name', 255)->nullable();
            $table->string('variant2_value', 255)->nullable();
            $table->boolean('is_variant')->nullable();
            $table->boolean('is_weighed')->nullable();
            $table->boolean('is_open_price')->nullable();
            $table->boolean('is_age_restricted')->nullable();
            $table->string('receipt_name', 255)->nullable();
            $table->unsignedBigInteger('row_version')->default(0);
            $table->dateTime('created_at')->nullable();
            $table->dateTime('updated_at')->nullable();
            $table->dateTime('deleted_at')->nullable();
            $table->unsignedBigInteger('hub_version')->nullable();
            $table->dateTime('hub_edited_at')->nullable();
            $table->dateTime('synced_at')->nullable();
            $table->unsignedBigInteger('sync_seq')->nullable();
            $table->json('extra')->nullable();

            $table->index(['company_id', 'updated_at'], 'products_company_id_updated_at_index');
            $table->index(['company_id', 'sku'], 'products_company_id_sku_index');
            $table->index(['company_id', 'department_id'], 'products_company_id_department_id_index');
            $table->index(['company_id', 'category_id'], 'products_company_id_category_id_index');
        });

        Schema::create('product_barcodes', function (Blueprint $table) {
            $table->string('id', 26)->primary();
            $table->string('company_id', 26);
            $table->string('product_id', 64)->nullable();
            $table->string('barcode', 255)->nullable();
            $table->integer('pack_qty')->nullable();
            $table->boolean('is_primary')->nullable();
            $table->string('unit_code', 255)->nullable();
            $table->string('product_unit_id', 64)->nullable();
            $table->string('source', 40)->nullable();
            $table->unsignedBigInteger('row_version')->default(0);
            $table->dateTime('created_at')->nullable();
            $table->dateTime('updated_at')->nullable();
            $table->dateTime('deleted_at')->nullable();
            $table->unsignedBigInteger('hub_version')->nullable();
            $table->dateTime('hub_edited_at')->nullable();
            $table->dateTime('synced_at')->nullable();
            $table->unsignedBigInteger('sync_seq')->nullable();
            $table->json('extra')->nullable();

            $table->index(['company_id', 'updated_at'], 'product_barcodes_company_id_updated_at_index');
            $table->index(['product_id'], 'product_barcodes_product_id_index');
            $table->index(['company_id', 'barcode'], 'product_barcodes_company_id_barcode_index');
        });

        Schema::create('product_aliases', function (Blueprint $table) {
            $table->string('id', 26)->primary();
            $table->string('company_id', 26);
            $table->string('product_id', 64)->nullable();
            $table->string('alias', 255)->nullable();
            $table->string('normalised_alias', 255)->nullable();
            $table->string('source', 40)->nullable();
            $table->integer('hit_count')->nullable();
            $table->dateTime('last_used_at')->nullable();
            $table->unsignedBigInteger('row_version')->default(0);
            $table->dateTime('created_at')->nullable();
            $table->dateTime('updated_at')->nullable();
            $table->dateTime('deleted_at')->nullable();
            $table->unsignedBigInteger('hub_version')->nullable();
            $table->dateTime('hub_edited_at')->nullable();
            $table->dateTime('synced_at')->nullable();
            $table->unsignedBigInteger('sync_seq')->nullable();
            $table->json('extra')->nullable();

            $table->index(['company_id', 'updated_at'], 'product_aliases_company_id_updated_at_index');
            $table->index(['product_id'], 'product_aliases_product_id_index');
        });

        Schema::create('product_units', function (Blueprint $table) {
            $table->string('id', 26)->primary();
            $table->string('company_id', 26);
            $table->string('product_id', 64)->nullable();
            $table->string('unit_id', 64)->nullable();
            $table->decimal('conversion_factor', 14, 4)->nullable();
            $table->decimal('sell_price_inc_vat', 12, 2)->nullable();
            $table->decimal('cost', 14, 4)->nullable();
            $table->boolean('is_default_sell_unit')->nullable();
            $table->boolean('is_purchase_unit')->nullable();
            $table->integer('position')->nullable();
            $table->unsignedBigInteger('row_version')->default(0);
            $table->dateTime('created_at')->nullable();
            $table->dateTime('updated_at')->nullable();
            $table->dateTime('deleted_at')->nullable();
            $table->unsignedBigInteger('hub_version')->nullable();
            $table->dateTime('hub_edited_at')->nullable();
            $table->dateTime('synced_at')->nullable();
            $table->unsignedBigInteger('sync_seq')->nullable();
            $table->json('extra')->nullable();

            $table->index(['company_id', 'updated_at'], 'product_units_company_id_updated_at_index');
            $table->index(['product_id'], 'product_units_product_id_index');
        });

        Schema::create('product_suppliers', function (Blueprint $table) {
            $table->string('id', 26)->primary();
            $table->string('company_id', 26);
            $table->string('product_id', 64)->nullable();
            $table->string('supplier_id', 64)->nullable();
            $table->string('supplier_sku', 255)->nullable();
            $table->string('supplier_barcode', 255)->nullable();
            $table->string('supplier_product_name', 255)->nullable();
            $table->decimal('supplier_price', 14, 4)->nullable();
            $table->integer('case_qty')->nullable();
            $table->decimal('case_cost', 14, 4)->nullable();
            $table->decimal('last_cost', 14, 4)->nullable();
            $table->decimal('avg_cost', 14, 4)->nullable();
            $table->dateTime('last_purchased_at')->nullable();
            $table->integer('lead_days')->nullable();
            $table->decimal('min_order', 12, 2)->nullable();
            $table->boolean('is_preferred')->nullable();
            $table->boolean('is_consignment')->nullable();
            $table->decimal('consignment_cost', 14, 4)->nullable();
            $table->unsignedBigInteger('row_version')->default(0);
            $table->dateTime('created_at')->nullable();
            $table->dateTime('updated_at')->nullable();
            $table->dateTime('deleted_at')->nullable();
            $table->unsignedBigInteger('hub_version')->nullable();
            $table->dateTime('hub_edited_at')->nullable();
            $table->dateTime('synced_at')->nullable();
            $table->unsignedBigInteger('sync_seq')->nullable();
            $table->json('extra')->nullable();

            $table->index(['company_id', 'updated_at'], 'product_suppliers_company_id_updated_at_index');
            $table->index(['product_id'], 'product_suppliers_product_id_index');
            $table->index(['company_id', 'supplier_id'], 'product_suppliers_company_id_supplier_id_index');
        });

        Schema::create('product_recalls', function (Blueprint $table) {
            $table->string('id', 26)->primary();
            $table->string('company_id', 26);
            $table->string('reference', 255)->nullable();
            $table->string('product_id', 64)->nullable();
            $table->string('product_name', 255)->nullable();
            $table->string('batch_code', 255)->nullable();
            $table->date('expiry_from')->nullable();
            $table->date('expiry_to')->nullable();
            $table->string('source', 255)->nullable();
            $table->text('reason')->nullable();
            $table->string('status', 40)->nullable();
            $table->string('supplier_id', 64)->nullable();
            $table->decimal('returned_qty', 14, 4)->nullable();
            $table->string('raised_by_user_id', 64)->nullable();
            $table->dateTime('raised_at')->nullable();
            $table->string('closed_by_user_id', 64)->nullable();
            $table->dateTime('closed_at')->nullable();
            $table->text('note')->nullable();
            $table->string('scope', 255)->nullable();
            $table->unsignedBigInteger('row_version')->default(0);
            $table->dateTime('created_at')->nullable();
            $table->dateTime('updated_at')->nullable();
            $table->dateTime('deleted_at')->nullable();
            $table->unsignedBigInteger('hub_version')->nullable();
            $table->dateTime('hub_edited_at')->nullable();
            $table->dateTime('synced_at')->nullable();
            $table->unsignedBigInteger('sync_seq')->nullable();
            $table->json('extra')->nullable();

            $table->index(['company_id', 'updated_at'], 'product_recalls_company_id_updated_at_index');
        });

        Schema::create('price_histories', function (Blueprint $table) {
            $table->string('id', 26)->primary();
            $table->string('company_id', 26);
            $table->string('product_id', 64)->nullable();
            $table->string('branch_id', 64)->nullable();
            $table->string('level', 40)->nullable();
            $table->decimal('old_price', 12, 2)->nullable();
            $table->decimal('new_price', 12, 2)->nullable();
            $table->decimal('old_cost', 14, 4)->nullable();
            $table->decimal('new_cost', 14, 4)->nullable();
            $table->string('user_id', 64)->nullable();
            $table->string('source', 255)->nullable();
            $table->text('reason')->nullable();
            $table->dateTime('at')->nullable();
            $table->boolean('price_changed')->nullable();
            $table->boolean('cost_changed')->nullable();
            $table->unsignedBigInteger('row_version')->default(0);
            $table->dateTime('created_at')->nullable();
            $table->dateTime('updated_at')->nullable();
            $table->dateTime('deleted_at')->nullable();
            $table->unsignedBigInteger('hub_version')->nullable();
            $table->dateTime('hub_edited_at')->nullable();
            $table->dateTime('synced_at')->nullable();
            $table->unsignedBigInteger('sync_seq')->nullable();
            $table->json('extra')->nullable();

            $table->index(['company_id', 'updated_at'], 'price_histories_company_id_updated_at_index');
            $table->index(['company_id', 'branch_id'], 'price_histories_company_id_branch_id_index');
            $table->index(['company_id', 'product_id', 'at'], 'price_histories_company_id_product_id_at_index');
        });

        Schema::create('exchange_rates', function (Blueprint $table) {
            $table->string('id', 26)->primary();
            $table->string('company_id', 26);
            $table->string('currency', 255)->nullable();
            $table->decimal('rate', 16, 6)->nullable();
            $table->date('effective_date')->nullable();
            $table->unsignedBigInteger('row_version')->default(0);
            $table->dateTime('created_at')->nullable();
            $table->dateTime('updated_at')->nullable();
            $table->dateTime('deleted_at')->nullable();
            $table->unsignedBigInteger('hub_version')->nullable();
            $table->dateTime('hub_edited_at')->nullable();
            $table->dateTime('synced_at')->nullable();
            $table->unsignedBigInteger('sync_seq')->nullable();
            $table->json('extra')->nullable();

            $table->index(['company_id', 'updated_at'], 'exchange_rates_company_id_updated_at_index');
        });

        Schema::create('branch_products', function (Blueprint $table) {
            $table->string('id', 26)->primary();
            $table->string('company_id', 26);
            $table->string('branch_id', 26)->nullable();
            $table->string('product_id', 64)->nullable();
            $table->boolean('is_active')->nullable();
            $table->integer('tile_position')->nullable();
            $table->string('tile_colour_hex', 255)->nullable();
            $table->decimal('price_override', 12, 2)->nullable();
            $table->decimal('qty_on_hand', 14, 4)->nullable();
            $table->decimal('qty_reserved', 14, 4)->nullable();
            $table->decimal('qty_available', 14, 4)->nullable();
            $table->boolean('is_stock_tracked')->nullable();
            $table->decimal('reorder_point', 14, 4)->nullable();
            $table->decimal('min_qty', 14, 4)->nullable();
            $table->decimal('max_qty', 14, 4)->nullable();
            $table->unsignedBigInteger('row_version')->default(0);
            $table->dateTime('created_at')->nullable();
            $table->dateTime('updated_at')->nullable();
            $table->dateTime('deleted_at')->nullable();
            $table->dateTime('synced_at')->nullable();
            $table->unsignedBigInteger('sync_seq')->nullable();
            $table->json('extra')->nullable();

            $table->index(['company_id', 'updated_at'], 'branch_products_company_id_updated_at_index');
            $table->index(['company_id', 'branch_id'], 'branch_products_company_id_branch_id_index');
            $table->index(['company_id', 'branch_id', 'product_id'], 'branch_products_company_id_branch_id_product_id_index');
        });

        Schema::create('price_change_batches', function (Blueprint $table) {
            $table->string('id', 26)->primary();
            $table->string('company_id', 26);
            $table->string('branch_id', 26)->nullable();
            $table->string('reference', 255)->nullable();
            $table->string('name', 255)->nullable();
            $table->string('status', 40)->nullable();
            $table->dateTime('effective_at')->nullable();
            $table->text('reason')->nullable();
            $table->string('source', 255)->nullable();
            $table->string('created_by_user_id', 64)->nullable();
            $table->string('approved_by_user_id', 64)->nullable();
            $table->string('approval_override_user_id', 64)->nullable();
            $table->dateTime('approved_at')->nullable();
            $table->string('went_live_by_user_id', 64)->nullable();
            $table->dateTime('went_live_at')->nullable();
            $table->string('cancelled_by_user_id', 64)->nullable();
            $table->dateTime('cancelled_at')->nullable();
            $table->text('cancel_reason')->nullable();
            $table->unsignedBigInteger('row_version')->default(0);
            $table->dateTime('created_at')->nullable();
            $table->dateTime('updated_at')->nullable();
            $table->dateTime('deleted_at')->nullable();
            $table->dateTime('synced_at')->nullable();
            $table->unsignedBigInteger('sync_seq')->nullable();
            $table->json('extra')->nullable();

            $table->index(['company_id', 'updated_at'], 'price_change_batches_company_id_updated_at_index');
            $table->index(['company_id', 'branch_id'], 'price_change_batches_company_id_branch_id_index');
        });

        Schema::create('price_change_lines', function (Blueprint $table) {
            $table->string('id', 26)->primary();
            $table->string('company_id', 26);
            $table->string('branch_id', 26)->nullable();
            $table->string('batch_id', 64)->nullable();
            $table->string('product_id', 64)->nullable();
            $table->string('price_branch_id', 64)->nullable();
            $table->string('level', 40)->nullable();
            $table->string('product_name', 255)->nullable();
            $table->decimal('old_price', 12, 2)->nullable();
            $table->decimal('new_price', 12, 2)->nullable();
            $table->decimal('cost_price', 14, 4)->nullable();
            $table->string('status', 40)->nullable();
            $table->text('note')->nullable();
            $table->boolean('label_printed')->nullable();
            $table->dateTime('label_printed_at')->nullable();
            $table->decimal('change_percent', 9, 4)->nullable();
            $table->boolean('awaits_label')->nullable();
            $table->unsignedBigInteger('row_version')->default(0);
            $table->dateTime('created_at')->nullable();
            $table->dateTime('updated_at')->nullable();
            $table->dateTime('deleted_at')->nullable();
            $table->dateTime('synced_at')->nullable();
            $table->unsignedBigInteger('sync_seq')->nullable();
            $table->json('extra')->nullable();

            $table->index(['company_id', 'updated_at'], 'price_change_lines_company_id_updated_at_index');
            $table->index(['company_id', 'branch_id'], 'price_change_lines_company_id_branch_id_index');
            $table->index(['batch_id'], 'price_change_lines_batch_id_index');
        });

        Schema::create('scale_plu_items', function (Blueprint $table) {
            $table->string('id', 26)->primary();
            $table->string('company_id', 26);
            $table->string('branch_id', 26)->nullable();
            $table->string('product_id', 64)->nullable();
            $table->string('plu_code', 255)->nullable();
            $table->integer('tare_grams')->nullable();
            $table->integer('sell_by_days')->nullable();
            $table->text('allergen_text')->nullable();
            $table->dateTime('last_exported_at')->nullable();
            $table->unsignedBigInteger('row_version')->default(0);
            $table->dateTime('created_at')->nullable();
            $table->dateTime('updated_at')->nullable();
            $table->dateTime('deleted_at')->nullable();
            $table->dateTime('synced_at')->nullable();
            $table->unsignedBigInteger('sync_seq')->nullable();
            $table->json('extra')->nullable();

            $table->index(['company_id', 'updated_at'], 'scale_plu_items_company_id_updated_at_index');
            $table->index(['company_id', 'branch_id'], 'scale_plu_items_company_id_branch_id_index');
        });

        Schema::create('shelf_labels', function (Blueprint $table) {
            $table->string('id', 26)->primary();
            $table->string('company_id', 26);
            $table->string('branch_id', 26)->nullable();
            $table->string('vendor_label_id', 64)->nullable();
            $table->string('vendor_key', 255)->nullable();
            $table->string('product_id', 64)->nullable();
            $table->dateTime('bound_at')->nullable();
            $table->string('bound_by_user_id', 64)->nullable();
            $table->decimal('last_pushed_sell_price', 12, 2)->nullable();
            $table->dateTime('last_pushed_at')->nullable();
            $table->text('last_push_error')->nullable();
            $table->integer('consecutive_failures')->nullable();
            $table->unsignedBigInteger('row_version')->default(0);
            $table->dateTime('created_at')->nullable();
            $table->dateTime('updated_at')->nullable();
            $table->dateTime('deleted_at')->nullable();
            $table->dateTime('synced_at')->nullable();
            $table->unsignedBigInteger('sync_seq')->nullable();
            $table->json('extra')->nullable();

            $table->index(['company_id', 'updated_at'], 'shelf_labels_company_id_updated_at_index');
            $table->index(['company_id', 'branch_id'], 'shelf_labels_company_id_branch_id_index');
        });

        Schema::create('top_seller_tiles', function (Blueprint $table) {
            $table->string('id', 26)->primary();
            $table->string('company_id', 26);
            $table->string('branch_id', 26)->nullable();
            $table->string('product_id', 64)->nullable();
            $table->integer('rank')->nullable();
            $table->decimal('units_sold', 14, 4)->nullable();
            $table->boolean('is_pinned')->nullable();
            $table->integer('pinned_position')->nullable();
            $table->dateTime('rebuilt_at')->nullable();
            $table->unsignedBigInteger('row_version')->default(0);
            $table->dateTime('created_at')->nullable();
            $table->dateTime('updated_at')->nullable();
            $table->dateTime('deleted_at')->nullable();
            $table->dateTime('synced_at')->nullable();
            $table->unsignedBigInteger('sync_seq')->nullable();
            $table->json('extra')->nullable();

            $table->index(['company_id', 'updated_at'], 'top_seller_tiles_company_id_updated_at_index');
            $table->index(['company_id', 'branch_id'], 'top_seller_tiles_company_id_branch_id_index');
        });

        Schema::create('high_value_count_items', function (Blueprint $table) {
            $table->string('id', 26)->primary();
            $table->string('company_id', 26);
            $table->string('branch_id', 26)->nullable();
            $table->string('product_id', 64)->nullable();
            $table->string('product_name', 255)->nullable();
            $table->integer('sort_order')->nullable();
            $table->unsignedBigInteger('row_version')->default(0);
            $table->dateTime('created_at')->nullable();
            $table->dateTime('updated_at')->nullable();
            $table->dateTime('deleted_at')->nullable();
            $table->dateTime('synced_at')->nullable();
            $table->unsignedBigInteger('sync_seq')->nullable();
            $table->json('extra')->nullable();

            $table->index(['company_id', 'updated_at'], 'high_value_count_items_company_id_updated_at_index');
            $table->index(['company_id', 'branch_id'], 'high_value_count_items_company_id_branch_id_index');
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('high_value_count_items');
        Schema::dropIfExists('top_seller_tiles');
        Schema::dropIfExists('shelf_labels');
        Schema::dropIfExists('scale_plu_items');
        Schema::dropIfExists('price_change_lines');
        Schema::dropIfExists('price_change_batches');
        Schema::dropIfExists('branch_products');
        Schema::dropIfExists('exchange_rates');
        Schema::dropIfExists('price_histories');
        Schema::dropIfExists('product_recalls');
        Schema::dropIfExists('product_suppliers');
        Schema::dropIfExists('product_units');
        Schema::dropIfExists('product_aliases');
        Schema::dropIfExists('product_barcodes');
        Schema::dropIfExists('products');
        Schema::dropIfExists('tax_rules');
        Schema::dropIfExists('vat_rates');
        Schema::dropIfExists('units');
        Schema::dropIfExists('categories');
        Schema::dropIfExists('departments');
    }
};
