<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

/**
 * Till entity store, group "cash": PaymentType, Reason, Shift, ShiftTender, CashCount, CashMovement, CashOfficeBanking, CashOfficeReconciliation, ChangeOrder, CardSettlement, ZReport, DayLock, ShopRoutineRun.
 *
 * @generated by `php artisan till:entities:generate` from docs/contracts/portal-api-v1.1
 * and app/Domain/TillData/definitions.php. Do not edit.
 */
return new class extends Migration
{
    public function up(): void
    {
        Schema::create('payment_types', function (Blueprint $table) {
            $table->string('id', 26)->primary();
            $table->string('company_id', 26);
            $table->string('name', 255)->nullable();
            $table->integer('position')->nullable();
            $table->boolean('is_cash')->nullable();
            $table->boolean('is_card')->nullable();
            $table->boolean('is_voucher')->nullable();
            $table->boolean('is_points')->nullable();
            $table->boolean('is_account')->nullable();
            $table->boolean('is_drs_refund')->nullable();
            $table->boolean('opens_drawer')->nullable();
            $table->boolean('show_on_payment')->nullable();
            $table->boolean('show_on_refund')->nullable();
            $table->boolean('show_on_customer_payment')->nullable();
            $table->boolean('is_active')->nullable();
            $table->unsignedBigInteger('row_version')->default(0);
            $table->dateTime('created_at')->nullable();
            $table->dateTime('updated_at')->nullable();
            $table->dateTime('deleted_at')->nullable();
            $table->unsignedBigInteger('hub_version')->nullable();
            $table->dateTime('hub_edited_at')->nullable();
            $table->dateTime('synced_at')->nullable();
            $table->unsignedBigInteger('sync_seq')->nullable();
            $table->json('extra')->nullable();

            $table->index(['company_id', 'updated_at'], 'payment_types_company_id_updated_at_index');
        });

        Schema::create('reasons', function (Blueprint $table) {
            $table->string('id', 26)->primary();
            $table->string('company_id', 26);
            $table->string('type', 40)->nullable();
            $table->text('text')->nullable();
            $table->integer('position')->nullable();
            $table->boolean('is_active')->nullable();
            $table->string('account_code', 255)->nullable();
            $table->unsignedBigInteger('row_version')->default(0);
            $table->dateTime('created_at')->nullable();
            $table->dateTime('updated_at')->nullable();
            $table->dateTime('deleted_at')->nullable();
            $table->unsignedBigInteger('hub_version')->nullable();
            $table->dateTime('hub_edited_at')->nullable();
            $table->dateTime('synced_at')->nullable();
            $table->unsignedBigInteger('sync_seq')->nullable();
            $table->json('extra')->nullable();

            $table->index(['company_id', 'updated_at'], 'reasons_company_id_updated_at_index');
        });

        Schema::create('shifts', function (Blueprint $table) {
            $table->string('id', 26)->primary();
            $table->string('company_id', 26);
            $table->string('branch_id', 26)->nullable();
            $table->string('register_id', 26)->nullable();
            $table->string('user_id', 64)->nullable();
            $table->dateTime('opened_at')->nullable();
            $table->dateTime('closed_at')->nullable();
            $table->decimal('opening_float', 12, 2)->nullable();
            $table->string('closed_by', 255)->nullable();
            $table->string('override_by', 255)->nullable();
            $table->text('override_reason')->nullable();
            $table->string('status', 40)->nullable();
            $table->decimal('variance_total', 12, 2)->nullable();
            $table->text('close_notes')->nullable();
            $table->string('mode', 40)->nullable();
            $table->string('drawer_owner_user_id', 64)->nullable();
            $table->unsignedBigInteger('row_version')->default(0);
            $table->dateTime('created_at')->nullable();
            $table->dateTime('updated_at')->nullable();
            $table->dateTime('deleted_at')->nullable();
            $table->dateTime('synced_at')->nullable();
            $table->unsignedBigInteger('sync_seq')->nullable();
            $table->json('extra')->nullable();

            $table->index(['company_id', 'updated_at'], 'shifts_company_id_updated_at_index');
            $table->index(['company_id', 'branch_id'], 'shifts_company_id_branch_id_index');
            $table->index(['company_id', 'branch_id', 'opened_at'], 'shifts_company_id_branch_id_opened_at_index');
        });

        Schema::create('shift_tenders', function (Blueprint $table) {
            $table->string('id', 26)->primary();
            $table->string('company_id', 26);
            $table->string('branch_id', 26)->nullable();
            $table->string('register_id', 26)->nullable();
            $table->string('shift_id', 64)->nullable();
            $table->string('payment_type_id', 64)->nullable();
            $table->decimal('expected', 12, 2)->nullable();
            $table->decimal('declared', 12, 2)->nullable();
            $table->decimal('terminal_total', 12, 2)->nullable();
            $table->decimal('variance', 12, 2)->nullable();
            $table->unsignedBigInteger('row_version')->default(0);
            $table->dateTime('created_at')->nullable();
            $table->dateTime('updated_at')->nullable();
            $table->dateTime('deleted_at')->nullable();
            $table->dateTime('synced_at')->nullable();
            $table->unsignedBigInteger('sync_seq')->nullable();
            $table->json('extra')->nullable();

            $table->index(['company_id', 'updated_at'], 'shift_tenders_company_id_updated_at_index');
            $table->index(['company_id', 'branch_id'], 'shift_tenders_company_id_branch_id_index');
            $table->index(['shift_id'], 'shift_tenders_shift_id_index');
        });

        Schema::create('cash_counts', function (Blueprint $table) {
            $table->string('id', 26)->primary();
            $table->string('company_id', 26);
            $table->string('branch_id', 26)->nullable();
            $table->string('register_id', 26)->nullable();
            $table->string('shift_id', 64)->nullable();
            $table->string('stage', 40)->nullable();
            $table->decimal('denomination', 12, 2)->nullable();
            $table->integer('count')->nullable();
            $table->string('user_id', 64)->nullable();
            $table->dateTime('at')->nullable();
            $table->decimal('total', 12, 2)->nullable();
            $table->unsignedBigInteger('row_version')->default(0);
            $table->dateTime('created_at')->nullable();
            $table->dateTime('updated_at')->nullable();
            $table->dateTime('deleted_at')->nullable();
            $table->dateTime('synced_at')->nullable();
            $table->unsignedBigInteger('sync_seq')->nullable();
            $table->json('extra')->nullable();

            $table->index(['company_id', 'updated_at'], 'cash_counts_company_id_updated_at_index');
            $table->index(['company_id', 'branch_id'], 'cash_counts_company_id_branch_id_index');
            $table->index(['shift_id'], 'cash_counts_shift_id_index');
        });

        Schema::create('cash_movements', function (Blueprint $table) {
            $table->string('id', 26)->primary();
            $table->string('company_id', 26);
            $table->string('branch_id', 26)->nullable();
            $table->string('register_id', 26)->nullable();
            $table->string('shift_id', 64)->nullable();
            $table->string('user_id', 64)->nullable();
            $table->string('type', 40)->nullable();
            $table->decimal('amount', 12, 2)->nullable();
            $table->string('reason_id', 64)->nullable();
            $table->text('note')->nullable();
            $table->dateTime('at')->nullable();
            $table->unsignedBigInteger('row_version')->default(0);
            $table->dateTime('created_at')->nullable();
            $table->dateTime('updated_at')->nullable();
            $table->dateTime('deleted_at')->nullable();
            $table->dateTime('synced_at')->nullable();
            $table->unsignedBigInteger('sync_seq')->nullable();
            $table->json('extra')->nullable();

            $table->index(['company_id', 'updated_at'], 'cash_movements_company_id_updated_at_index');
            $table->index(['company_id', 'branch_id'], 'cash_movements_company_id_branch_id_index');
            $table->index(['company_id', 'branch_id', 'at'], 'cash_movements_company_id_branch_id_at_index');
            $table->index(['shift_id'], 'cash_movements_shift_id_index');
        });

        Schema::create('cash_office_bankings', function (Blueprint $table) {
            $table->string('id', 26)->primary();
            $table->string('company_id', 26);
            $table->string('branch_id', 26)->nullable();
            $table->string('reference', 255)->nullable();
            $table->decimal('amount', 12, 2)->nullable();
            $table->longText('denominations_json')->nullable();
            $table->string('status', 40)->nullable();
            $table->string('prepared_by_user_id', 64)->nullable();
            $table->dateTime('prepared_at')->nullable();
            $table->string('banked_by_user_id', 64)->nullable();
            $table->dateTime('banked_at')->nullable();
            $table->string('bank_reference', 255)->nullable();
            $table->text('note')->nullable();
            $table->string('seal_number', 255)->nullable();
            $table->string('collection_method', 40)->nullable();
            $table->string('carrier_name', 255)->nullable();
            $table->string('collected_signature_name', 255)->nullable();
            $table->string('collected_by_user_id', 64)->nullable();
            $table->dateTime('collected_at')->nullable();
            $table->decimal('confirmed_amount', 12, 2)->nullable();
            $table->decimal('variance_amount', 12, 2)->nullable();
            $table->unsignedBigInteger('row_version')->default(0);
            $table->dateTime('created_at')->nullable();
            $table->dateTime('updated_at')->nullable();
            $table->dateTime('deleted_at')->nullable();
            $table->dateTime('synced_at')->nullable();
            $table->unsignedBigInteger('sync_seq')->nullable();
            $table->json('extra')->nullable();

            $table->index(['company_id', 'updated_at'], 'cash_office_bankings_company_id_updated_at_index');
            $table->index(['company_id', 'branch_id'], 'cash_office_bankings_company_id_branch_id_index');
        });

        Schema::create('cash_office_reconciliations', function (Blueprint $table) {
            $table->string('id', 26)->primary();
            $table->string('company_id', 26);
            $table->string('branch_id', 26)->nullable();
            $table->date('trading_date')->nullable();
            $table->decimal('expected_balance', 12, 2)->nullable();
            $table->decimal('counted_balance', 12, 2)->nullable();
            $table->longText('denominations_json')->nullable();
            $table->string('reason_id', 64)->nullable();
            $table->text('note')->nullable();
            $table->string('counted_by_user_id', 64)->nullable();
            $table->dateTime('counted_at')->nullable();
            $table->decimal('variance', 12, 2)->nullable();
            $table->unsignedBigInteger('row_version')->default(0);
            $table->dateTime('created_at')->nullable();
            $table->dateTime('updated_at')->nullable();
            $table->dateTime('deleted_at')->nullable();
            $table->dateTime('synced_at')->nullable();
            $table->unsignedBigInteger('sync_seq')->nullable();
            $table->json('extra')->nullable();

            $table->index(['company_id', 'updated_at'], 'cash_office_reconciliations_company_id_updated_at_index');
            $table->index(['company_id', 'branch_id'], 'cash_office_reconciliations_company_id_branch_id_index');
        });

        Schema::create('change_orders', function (Blueprint $table) {
            $table->string('id', 26)->primary();
            $table->string('company_id', 26);
            $table->string('branch_id', 26)->nullable();
            $table->string('reference', 255)->nullable();
            $table->decimal('amount', 12, 2)->nullable();
            $table->longText('denominations_json')->nullable();
            $table->string('status', 40)->nullable();
            $table->string('requested_by_user_id', 64)->nullable();
            $table->dateTime('requested_at')->nullable();
            $table->string('received_by_user_id', 64)->nullable();
            $table->dateTime('received_at')->nullable();
            $table->text('note')->nullable();
            $table->unsignedBigInteger('row_version')->default(0);
            $table->dateTime('created_at')->nullable();
            $table->dateTime('updated_at')->nullable();
            $table->dateTime('deleted_at')->nullable();
            $table->dateTime('synced_at')->nullable();
            $table->unsignedBigInteger('sync_seq')->nullable();
            $table->json('extra')->nullable();

            $table->index(['company_id', 'updated_at'], 'change_orders_company_id_updated_at_index');
            $table->index(['company_id', 'branch_id'], 'change_orders_company_id_branch_id_index');
        });

        Schema::create('card_settlements', function (Blueprint $table) {
            $table->string('id', 26)->primary();
            $table->string('company_id', 26);
            $table->string('branch_id', 26)->nullable();
            $table->string('register_id', 26)->nullable();
            $table->date('trading_date')->nullable();
            $table->string('provider', 255)->nullable();
            $table->string('reference', 255)->nullable();
            $table->string('batch_reference', 255)->nullable();
            $table->decimal('terminal_total', 12, 2)->nullable();
            $table->decimal('pos_total', 12, 2)->nullable();
            $table->decimal('variance', 12, 2)->nullable();
            $table->decimal('fees', 12, 2)->nullable();
            $table->integer('transaction_count')->nullable();
            $table->string('status', 40)->nullable();
            $table->text('message')->nullable();
            $table->dateTime('settled_at')->nullable();
            $table->string('settled_by_user_id', 64)->nullable();
            $table->longText('response_json')->nullable();
            $table->unsignedBigInteger('row_version')->default(0);
            $table->dateTime('created_at')->nullable();
            $table->dateTime('updated_at')->nullable();
            $table->dateTime('deleted_at')->nullable();
            $table->dateTime('synced_at')->nullable();
            $table->unsignedBigInteger('sync_seq')->nullable();
            $table->json('extra')->nullable();

            $table->index(['company_id', 'updated_at'], 'card_settlements_company_id_updated_at_index');
            $table->index(['company_id', 'branch_id'], 'card_settlements_company_id_branch_id_index');
        });

        Schema::create('z_reports', function (Blueprint $table) {
            $table->string('id', 26)->primary();
            $table->string('company_id', 26);
            $table->string('branch_id', 26)->nullable();
            $table->string('register_id', 26)->nullable();
            $table->string('shift_id', 64)->nullable();
            $table->integer('sequence_no')->nullable();
            $table->dateTime('period_start')->nullable();
            $table->dateTime('period_end')->nullable();
            $table->dateTime('generated_at')->nullable();
            $table->longText('totals_json')->nullable();
            $table->dateTime('printed_at')->nullable();
            $table->string('printed_by', 255)->nullable();
            $table->integer('reprint_count')->nullable();
            $table->unsignedBigInteger('row_version')->default(0);
            $table->dateTime('created_at')->nullable();
            $table->dateTime('updated_at')->nullable();
            $table->dateTime('deleted_at')->nullable();
            $table->dateTime('synced_at')->nullable();
            $table->unsignedBigInteger('sync_seq')->nullable();
            $table->json('extra')->nullable();

            $table->index(['company_id', 'updated_at'], 'z_reports_company_id_updated_at_index');
            $table->index(['company_id', 'branch_id'], 'z_reports_company_id_branch_id_index');
            $table->index(['company_id', 'branch_id', 'period_end'], 'z_reports_company_id_branch_id_period_end_index');
        });

        Schema::create('day_locks', function (Blueprint $table) {
            $table->string('id', 26)->primary();
            $table->string('company_id', 26);
            $table->string('branch_id', 26)->nullable();
            $table->date('trading_date')->nullable();
            $table->dateTime('locked_at')->nullable();
            $table->string('locked_by', 255)->nullable();
            $table->dateTime('unlocked_at')->nullable();
            $table->string('unlocked_by', 255)->nullable();
            $table->text('unlock_reason')->nullable();
            $table->boolean('is_locked')->nullable();
            $table->unsignedBigInteger('row_version')->default(0);
            $table->dateTime('created_at')->nullable();
            $table->dateTime('updated_at')->nullable();
            $table->dateTime('deleted_at')->nullable();
            $table->dateTime('synced_at')->nullable();
            $table->unsignedBigInteger('sync_seq')->nullable();
            $table->json('extra')->nullable();

            $table->index(['company_id', 'updated_at'], 'day_locks_company_id_updated_at_index');
            $table->index(['company_id', 'branch_id'], 'day_locks_company_id_branch_id_index');
        });

        Schema::create('shop_routine_runs', function (Blueprint $table) {
            $table->string('id', 26)->primary();
            $table->string('company_id', 26);
            $table->string('branch_id', 26)->nullable();
            $table->string('type', 40)->nullable();
            $table->date('trading_date')->nullable();
            $table->string('status', 40)->nullable();
            $table->longText('steps_json')->nullable();
            $table->string('started_by', 255)->nullable();
            $table->dateTime('started_at')->nullable();
            $table->dateTime('completed_at')->nullable();
            $table->string('idempotency_key', 255)->nullable();
            $table->unsignedBigInteger('row_version')->default(0);
            $table->dateTime('created_at')->nullable();
            $table->dateTime('updated_at')->nullable();
            $table->dateTime('deleted_at')->nullable();
            $table->dateTime('synced_at')->nullable();
            $table->unsignedBigInteger('sync_seq')->nullable();
            $table->json('extra')->nullable();

            $table->index(['company_id', 'updated_at'], 'shop_routine_runs_company_id_updated_at_index');
            $table->index(['company_id', 'branch_id'], 'shop_routine_runs_company_id_branch_id_index');
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('shop_routine_runs');
        Schema::dropIfExists('day_locks');
        Schema::dropIfExists('z_reports');
        Schema::dropIfExists('card_settlements');
        Schema::dropIfExists('change_orders');
        Schema::dropIfExists('cash_office_reconciliations');
        Schema::dropIfExists('cash_office_bankings');
        Schema::dropIfExists('cash_movements');
        Schema::dropIfExists('cash_counts');
        Schema::dropIfExists('shift_tenders');
        Schema::dropIfExists('shifts');
        Schema::dropIfExists('reasons');
        Schema::dropIfExists('payment_types');
    }
};
