<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

/**
 * Till entity store, group "staff": User, Role, ClockEvent, RotaShift, TimesheetApproval, WageRate.
 *
 * @generated by `php artisan till:entities:generate` from docs/contracts/portal-api-v1.1
 * and app/Domain/TillData/definitions.php. Do not edit.
 */
return new class extends Migration
{
    public function up(): void
    {
        Schema::create('till_users', function (Blueprint $table) {
            $table->string('id', 26)->primary();
            $table->string('company_id', 26);
            $table->string('name', 255)->nullable();
            $table->string('pin_hash', 255)->nullable();
            $table->string('rfid', 255)->nullable();
            $table->string('role_id', 64)->nullable();
            $table->decimal('rate_per_hour', 12, 2)->nullable();
            $table->decimal('max_shift_hours', 14, 4)->nullable();
            $table->boolean('is_service_staff')->nullable();
            $table->boolean('allow_commission')->nullable();
            $table->boolean('is_personal_licence_holder')->nullable();
            $table->boolean('simple_mode_override')->nullable();
            $table->boolean('big_text_mode')->nullable();
            $table->boolean('is_active')->nullable();
            $table->unsignedBigInteger('row_version')->default(0);
            $table->dateTime('created_at')->nullable();
            $table->dateTime('updated_at')->nullable();
            $table->dateTime('deleted_at')->nullable();
            $table->unsignedBigInteger('hub_version')->nullable();
            $table->dateTime('hub_edited_at')->nullable();
            $table->dateTime('synced_at')->nullable();
            $table->unsignedBigInteger('sync_seq')->nullable();
            $table->json('extra')->nullable();

            $table->index(['company_id', 'updated_at'], 'till_users_company_id_updated_at_index');
        });

        Schema::create('till_roles', function (Blueprint $table) {
            $table->string('id', 26)->primary();
            $table->string('company_id', 26);
            $table->string('name', 255)->nullable();
            $table->integer('level')->nullable();
            $table->boolean('is_system')->nullable();
            $table->boolean('simple_mode_default')->nullable();
            $table->json('permissions')->nullable();
            $table->unsignedBigInteger('row_version')->default(0);
            $table->dateTime('created_at')->nullable();
            $table->dateTime('updated_at')->nullable();
            $table->dateTime('deleted_at')->nullable();
            $table->unsignedBigInteger('hub_version')->nullable();
            $table->dateTime('hub_edited_at')->nullable();
            $table->dateTime('synced_at')->nullable();
            $table->unsignedBigInteger('sync_seq')->nullable();
            $table->json('extra')->nullable();

            $table->index(['company_id', 'updated_at'], 'till_roles_company_id_updated_at_index');
        });

        Schema::create('clock_events', function (Blueprint $table) {
            $table->string('id', 26)->primary();
            $table->string('company_id', 26);
            $table->string('branch_id', 26)->nullable();
            $table->string('user_id', 64)->nullable();
            $table->string('type', 40)->nullable();
            $table->dateTime('at')->nullable();
            $table->text('note')->nullable();
            $table->unsignedBigInteger('row_version')->default(0);
            $table->dateTime('created_at')->nullable();
            $table->dateTime('updated_at')->nullable();
            $table->dateTime('deleted_at')->nullable();
            $table->dateTime('synced_at')->nullable();
            $table->unsignedBigInteger('sync_seq')->nullable();
            $table->json('extra')->nullable();

            $table->index(['company_id', 'updated_at'], 'clock_events_company_id_updated_at_index');
            $table->index(['company_id', 'branch_id'], 'clock_events_company_id_branch_id_index');
            $table->index(['company_id', 'user_id', 'at'], 'clock_events_company_id_user_id_at_index');
        });

        Schema::create('rota_shifts', function (Blueprint $table) {
            $table->string('id', 26)->primary();
            $table->string('company_id', 26);
            $table->string('branch_id', 26)->nullable();
            $table->string('user_id', 64)->nullable();
            $table->date('shift_date')->nullable();
            $table->string('start_time', 255)->nullable();
            $table->string('end_time', 255)->nullable();
            $table->integer('break_minutes')->nullable();
            $table->boolean('is_published')->nullable();
            $table->text('note')->nullable();
            $table->unsignedBigInteger('row_version')->default(0);
            $table->dateTime('created_at')->nullable();
            $table->dateTime('updated_at')->nullable();
            $table->dateTime('deleted_at')->nullable();
            $table->dateTime('synced_at')->nullable();
            $table->unsignedBigInteger('sync_seq')->nullable();
            $table->json('extra')->nullable();

            $table->index(['company_id', 'updated_at'], 'rota_shifts_company_id_updated_at_index');
            $table->index(['company_id', 'branch_id'], 'rota_shifts_company_id_branch_id_index');
        });

        Schema::create('timesheet_approvals', function (Blueprint $table) {
            $table->string('id', 26)->primary();
            $table->string('company_id', 26);
            $table->string('branch_id', 26)->nullable();
            $table->string('user_id', 64)->nullable();
            $table->date('week_start')->nullable();
            $table->string('approved_by_user_id', 64)->nullable();
            $table->dateTime('approved_at')->nullable();
            $table->decimal('total_hours', 14, 4)->nullable();
            $table->decimal('overtime_hours', 14, 4)->nullable();
            $table->unsignedBigInteger('row_version')->default(0);
            $table->dateTime('created_at')->nullable();
            $table->dateTime('updated_at')->nullable();
            $table->dateTime('deleted_at')->nullable();
            $table->dateTime('synced_at')->nullable();
            $table->unsignedBigInteger('sync_seq')->nullable();
            $table->json('extra')->nullable();

            $table->index(['company_id', 'updated_at'], 'timesheet_approvals_company_id_updated_at_index');
            $table->index(['company_id', 'branch_id'], 'timesheet_approvals_company_id_branch_id_index');
        });

        Schema::create('wage_rates', function (Blueprint $table) {
            $table->string('id', 26)->primary();
            $table->string('company_id', 26);
            $table->string('branch_id', 26)->nullable();
            $table->string('label', 255)->nullable();
            $table->integer('age_from')->nullable();
            $table->integer('age_to')->nullable();
            $table->date('effective_from')->nullable();
            $table->decimal('rate_per_hour', 12, 2)->nullable();
            $table->boolean('is_placeholder')->nullable();
            $table->unsignedBigInteger('row_version')->default(0);
            $table->dateTime('created_at')->nullable();
            $table->dateTime('updated_at')->nullable();
            $table->dateTime('deleted_at')->nullable();
            $table->dateTime('synced_at')->nullable();
            $table->unsignedBigInteger('sync_seq')->nullable();
            $table->json('extra')->nullable();

            $table->index(['company_id', 'updated_at'], 'wage_rates_company_id_updated_at_index');
            $table->index(['company_id', 'branch_id'], 'wage_rates_company_id_branch_id_index');
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('wage_rates');
        Schema::dropIfExists('timesheet_approvals');
        Schema::dropIfExists('rota_shifts');
        Schema::dropIfExists('clock_events');
        Schema::dropIfExists('till_roles');
        Schema::dropIfExists('till_users');
    }
};
