<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

/**
 * Till entity store, group "system": AuditLog, ExceptionLog, AlertSubscription, BackupRun, BranchHoursOverride, ComplianceLicence, EventSubscription, HardwareCheck, ImportColumnMap, ImportJob, Licence, LicenceAddOnTrial, PrintJob, PrinterProfile, ScaleCalibrationLog, SyncConflict, SyncState, UpdateRun.
 *
 * @generated by `php artisan till:entities:generate` from docs/contracts/portal-api-v1.1
 * and app/Domain/TillData/definitions.php. Do not edit.
 */
return new class extends Migration
{
    public function up(): void
    {
        Schema::create('till_audit_logs', function (Blueprint $table) {
            $table->string('id', 26)->primary();
            $table->string('company_id', 26);
            $table->string('branch_id', 26)->nullable();
            $table->string('register_id', 26)->nullable();
            $table->string('user_id', 64)->nullable();
            $table->string('entity_name', 255)->nullable();
            $table->string('entity_id', 64)->nullable();
            $table->string('action', 255)->nullable();
            $table->longText('before_json')->nullable();
            $table->longText('after_json')->nullable();
            $table->dateTime('at')->nullable();
            $table->text('reason')->nullable();
            $table->unsignedBigInteger('row_version')->default(0);
            $table->dateTime('created_at')->nullable();
            $table->dateTime('updated_at')->nullable();
            $table->dateTime('deleted_at')->nullable();
            $table->dateTime('synced_at')->nullable();
            $table->unsignedBigInteger('sync_seq')->nullable();
            $table->json('extra')->nullable();

            $table->index(['company_id', 'updated_at'], 'till_audit_logs_company_id_updated_at_index');
            $table->index(['company_id', 'branch_id'], 'till_audit_logs_company_id_branch_id_index');
            $table->index(['company_id', 'branch_id', 'at'], 'till_audit_logs_company_id_branch_id_at_index');
            $table->index(['company_id', 'entity_name', 'entity_id'], 'till_audit_logs_company_id_entity_name_entity_id_index');
        });

        Schema::create('exception_logs', function (Blueprint $table) {
            $table->string('id', 26)->primary();
            $table->string('company_id', 26);
            $table->string('branch_id', 26)->nullable();
            $table->string('register_id', 26)->nullable();
            $table->string('user_id', 64)->nullable();
            $table->string('type', 255)->nullable();
            $table->decimal('amount', 12, 2)->nullable();
            $table->text('before_value')->nullable();
            $table->text('after_value')->nullable();
            $table->string('ref_type', 255)->nullable();
            $table->string('ref_id', 64)->nullable();
            $table->string('reason_id', 64)->nullable();
            $table->dateTime('at')->nullable();
            $table->unsignedBigInteger('row_version')->default(0);
            $table->dateTime('created_at')->nullable();
            $table->dateTime('updated_at')->nullable();
            $table->dateTime('deleted_at')->nullable();
            $table->dateTime('synced_at')->nullable();
            $table->unsignedBigInteger('sync_seq')->nullable();
            $table->json('extra')->nullable();

            $table->index(['company_id', 'updated_at'], 'exception_logs_company_id_updated_at_index');
            $table->index(['company_id', 'branch_id'], 'exception_logs_company_id_branch_id_index');
        });

        Schema::create('alert_subscriptions', function (Blueprint $table) {
            $table->string('id', 26)->primary();
            $table->string('company_id', 26);
            $table->string('branch_id', 26)->nullable();
            $table->string('user_id', 64)->nullable();
            $table->string('type', 40)->nullable();
            $table->boolean('is_enabled')->nullable();
            $table->text('channels')->nullable();
            $table->string('email_address', 255)->nullable();
            $table->string('whats_app_number', 255)->nullable();
            $table->integer('quiet_hours_start_minute')->nullable();
            $table->integer('quiet_hours_end_minute')->nullable();
            $table->boolean('is_digest')->nullable();
            $table->unsignedBigInteger('row_version')->default(0);
            $table->dateTime('created_at')->nullable();
            $table->dateTime('updated_at')->nullable();
            $table->dateTime('deleted_at')->nullable();
            $table->dateTime('synced_at')->nullable();
            $table->unsignedBigInteger('sync_seq')->nullable();
            $table->json('extra')->nullable();

            $table->index(['company_id', 'updated_at'], 'alert_subscriptions_company_id_updated_at_index');
            $table->index(['company_id', 'branch_id'], 'alert_subscriptions_company_id_branch_id_index');
        });

        Schema::create('backup_runs', function (Blueprint $table) {
            $table->string('id', 26)->primary();
            $table->string('company_id', 26);
            $table->string('branch_id', 26)->nullable();
            $table->string('layer', 40)->nullable();
            $table->text('file_path')->nullable();
            $table->bigInteger('size_bytes')->nullable();
            $table->dateTime('started_at')->nullable();
            $table->dateTime('completed_at')->nullable();
            $table->boolean('is_success')->nullable();
            $table->text('failure_reason')->nullable();
            $table->boolean('is_verified')->nullable();
            $table->dateTime('verified_at')->nullable();
            $table->text('verification_detail')->nullable();
            $table->boolean('is_restore_test')->nullable();
            $table->unsignedBigInteger('row_version')->default(0);
            $table->dateTime('created_at')->nullable();
            $table->dateTime('updated_at')->nullable();
            $table->dateTime('deleted_at')->nullable();
            $table->dateTime('synced_at')->nullable();
            $table->unsignedBigInteger('sync_seq')->nullable();
            $table->json('extra')->nullable();

            $table->index(['company_id', 'updated_at'], 'backup_runs_company_id_updated_at_index');
            $table->index(['company_id', 'branch_id'], 'backup_runs_company_id_branch_id_index');
        });

        Schema::create('branch_hours_overrides', function (Blueprint $table) {
            $table->string('id', 26)->primary();
            $table->string('company_id', 26);
            $table->string('branch_id', 26)->nullable();
            $table->date('date')->nullable();
            $table->string('seasonal_event_id', 64)->nullable();
            $table->string('seasonal_event_name', 255)->nullable();
            $table->boolean('is_closed')->nullable();
            $table->time('licensed_opens_at')->nullable();
            $table->time('licensed_closes_at')->nullable();
            $table->time('general_opens_at')->nullable();
            $table->time('general_closes_at')->nullable();
            $table->text('notes')->nullable();
            $table->unsignedBigInteger('row_version')->default(0);
            $table->dateTime('created_at')->nullable();
            $table->dateTime('updated_at')->nullable();
            $table->dateTime('deleted_at')->nullable();
            $table->dateTime('synced_at')->nullable();
            $table->unsignedBigInteger('sync_seq')->nullable();
            $table->json('extra')->nullable();

            $table->index(['company_id', 'updated_at'], 'branch_hours_overrides_company_id_updated_at_index');
            $table->index(['company_id', 'branch_id'], 'branch_hours_overrides_company_id_branch_id_index');
        });

        Schema::create('compliance_licences', function (Blueprint $table) {
            $table->string('id', 26)->primary();
            $table->string('company_id', 26);
            $table->string('branch_id', 26)->nullable();
            $table->string('licence_type', 255)->nullable();
            $table->string('number', 255)->nullable();
            $table->string('holder_name', 255)->nullable();
            $table->date('issued_on')->nullable();
            $table->date('expires_on')->nullable();
            $table->text('notes')->nullable();
            $table->unsignedBigInteger('row_version')->default(0);
            $table->dateTime('created_at')->nullable();
            $table->dateTime('updated_at')->nullable();
            $table->dateTime('deleted_at')->nullable();
            $table->dateTime('synced_at')->nullable();
            $table->unsignedBigInteger('sync_seq')->nullable();
            $table->json('extra')->nullable();

            $table->index(['company_id', 'updated_at'], 'compliance_licences_company_id_updated_at_index');
            $table->index(['company_id', 'branch_id'], 'compliance_licences_company_id_branch_id_index');
        });

        Schema::create('event_subscriptions', function (Blueprint $table) {
            $table->string('id', 26)->primary();
            $table->string('company_id', 26);
            $table->string('branch_id', 26)->nullable();
            $table->string('handler_name', 255)->nullable();
            $table->bigInteger('last_seq')->nullable();
            $table->unsignedBigInteger('row_version')->default(0);
            $table->dateTime('created_at')->nullable();
            $table->dateTime('updated_at')->nullable();
            $table->dateTime('deleted_at')->nullable();
            $table->dateTime('synced_at')->nullable();
            $table->unsignedBigInteger('sync_seq')->nullable();
            $table->json('extra')->nullable();

            $table->index(['company_id', 'updated_at'], 'event_subscriptions_company_id_updated_at_index');
            $table->index(['company_id', 'branch_id'], 'event_subscriptions_company_id_branch_id_index');
        });

        Schema::create('hardware_checks', function (Blueprint $table) {
            $table->string('id', 26)->primary();
            $table->string('company_id', 26);
            $table->string('branch_id', 26)->nullable();
            $table->string('register_id', 26)->nullable();
            $table->string('kind', 40)->nullable();
            $table->string('result', 40)->nullable();
            $table->string('adapter', 255)->nullable();
            $table->string('port', 255)->nullable();
            $table->text('evidence')->nullable();
            $table->text('instruction')->nullable();
            $table->bigInteger('elapsed_ms')->nullable();
            $table->dateTime('at')->nullable();
            $table->string('user_id', 64)->nullable();
            $table->string('user_name', 255)->nullable();
            $table->string('confirms_check_id', 64)->nullable();
            $table->text('notes')->nullable();
            $table->unsignedBigInteger('row_version')->default(0);
            $table->dateTime('created_at')->nullable();
            $table->dateTime('updated_at')->nullable();
            $table->dateTime('deleted_at')->nullable();
            $table->dateTime('synced_at')->nullable();
            $table->unsignedBigInteger('sync_seq')->nullable();
            $table->json('extra')->nullable();

            $table->index(['company_id', 'updated_at'], 'hardware_checks_company_id_updated_at_index');
            $table->index(['company_id', 'branch_id'], 'hardware_checks_company_id_branch_id_index');
        });

        Schema::create('import_column_maps', function (Blueprint $table) {
            $table->string('id', 26)->primary();
            $table->string('company_id', 26);
            $table->string('branch_id', 26)->nullable();
            $table->string('name', 255)->nullable();
            $table->string('target', 40)->nullable();
            $table->string('header_signature', 255)->nullable();
            $table->string('sheet_name', 255)->nullable();
            $table->longText('mapping_json')->nullable();
            $table->dateTime('last_used_at')->nullable();
            $table->unsignedBigInteger('row_version')->default(0);
            $table->dateTime('created_at')->nullable();
            $table->dateTime('updated_at')->nullable();
            $table->dateTime('deleted_at')->nullable();
            $table->dateTime('synced_at')->nullable();
            $table->unsignedBigInteger('sync_seq')->nullable();
            $table->json('extra')->nullable();

            $table->index(['company_id', 'updated_at'], 'import_column_maps_company_id_updated_at_index');
            $table->index(['company_id', 'branch_id'], 'import_column_maps_company_id_branch_id_index');
        });

        Schema::create('import_jobs', function (Blueprint $table) {
            $table->string('id', 26)->primary();
            $table->string('company_id', 26);
            $table->string('branch_id', 26)->nullable();
            $table->string('target', 40)->nullable();
            $table->string('file_name', 255)->nullable();
            $table->dateTime('started_at')->nullable();
            $table->dateTime('finished_at')->nullable();
            $table->string('status', 40)->nullable();
            $table->integer('total_rows')->nullable();
            $table->integer('created_count')->nullable();
            $table->integer('updated_count')->nullable();
            $table->integer('skipped_count')->nullable();
            $table->integer('error_count')->nullable();
            $table->string('user_id', 64)->nullable();
            $table->text('error_report_path')->nullable();
            $table->unsignedBigInteger('row_version')->default(0);
            $table->dateTime('created_at')->nullable();
            $table->dateTime('updated_at')->nullable();
            $table->dateTime('deleted_at')->nullable();
            $table->dateTime('synced_at')->nullable();
            $table->unsignedBigInteger('sync_seq')->nullable();
            $table->json('extra')->nullable();

            $table->index(['company_id', 'updated_at'], 'import_jobs_company_id_updated_at_index');
            $table->index(['company_id', 'branch_id'], 'import_jobs_company_id_branch_id_index');
        });

        Schema::create('till_licences', function (Blueprint $table) {
            $table->string('id', 26)->primary();
            $table->string('company_id', 26);
            $table->string('branch_id', 26)->nullable();
            $table->char('licence_key_hash', 64)->nullable();
            $table->string('licence_key_last4', 4)->nullable();
            $table->dateTime('trial_started_at')->nullable();
            $table->dateTime('trial_ends_at')->nullable();
            $table->dateTime('activated_at')->nullable();
            $table->dateTime('expires_at')->nullable();
            $table->integer('grace_days')->nullable();
            $table->boolean('is_dealer')->nullable();
            $table->integer('branch_limit')->nullable();
            $table->integer('register_limit')->nullable();
            $table->string('device_id', 64)->nullable();
            $table->unsignedBigInteger('row_version')->default(0);
            $table->dateTime('created_at')->nullable();
            $table->dateTime('updated_at')->nullable();
            $table->dateTime('deleted_at')->nullable();
            $table->dateTime('synced_at')->nullable();
            $table->unsignedBigInteger('sync_seq')->nullable();
            $table->json('extra')->nullable();

            $table->index(['company_id', 'updated_at'], 'till_licences_company_id_updated_at_index');
            $table->index(['company_id', 'branch_id'], 'till_licences_company_id_branch_id_index');
        });

        Schema::create('till_licence_add_on_trials', function (Blueprint $table) {
            $table->string('id', 26)->primary();
            $table->string('company_id', 26);
            $table->string('branch_id', 26)->nullable();
            $table->string('feature_key', 255)->nullable();
            $table->dateTime('first_used_at')->nullable();
            $table->integer('trial_days')->nullable();
            $table->integer('usage_cap')->nullable();
            $table->integer('usage_count')->nullable();
            $table->decimal('money_found', 12, 2)->nullable();
            $table->integer('minutes_saved')->nullable();
            $table->dateTime('reminder_sent_at')->nullable();
            $table->boolean('is_downgraded')->nullable();
            $table->dateTime('trial_ends_at')->nullable();
            $table->unsignedBigInteger('row_version')->default(0);
            $table->dateTime('created_at')->nullable();
            $table->dateTime('updated_at')->nullable();
            $table->dateTime('deleted_at')->nullable();
            $table->dateTime('synced_at')->nullable();
            $table->unsignedBigInteger('sync_seq')->nullable();
            $table->json('extra')->nullable();

            $table->index(['company_id', 'updated_at'], 'till_licence_add_on_trials_company_id_updated_at_index');
            $table->index(['company_id', 'branch_id'], 'till_licence_add_on_trials_company_id_branch_id_index');
        });

        Schema::create('print_jobs', function (Blueprint $table) {
            $table->string('id', 26)->primary();
            $table->string('company_id', 26);
            $table->string('branch_id', 26)->nullable();
            $table->string('register_id', 26)->nullable();
            $table->string('kind', 255)->nullable();
            $table->string('printer_key', 255)->nullable();
            $table->longText('payload')->nullable();
            $table->string('status', 40)->nullable();
            $table->integer('attempts')->nullable();
            $table->text('last_error')->nullable();
            $table->dateTime('next_attempt_at')->nullable();
            $table->dateTime('printed_at')->nullable();
            $table->string('reference_id', 64)->nullable();
            $table->integer('copies')->nullable();
            $table->unsignedBigInteger('row_version')->default(0);
            $table->dateTime('created_at')->nullable();
            $table->dateTime('updated_at')->nullable();
            $table->dateTime('deleted_at')->nullable();
            $table->dateTime('synced_at')->nullable();
            $table->unsignedBigInteger('sync_seq')->nullable();
            $table->json('extra')->nullable();

            $table->index(['company_id', 'updated_at'], 'print_jobs_company_id_updated_at_index');
            $table->index(['company_id', 'branch_id'], 'print_jobs_company_id_branch_id_index');
        });

        Schema::create('printer_profiles', function (Blueprint $table) {
            $table->string('id', 26)->primary();
            $table->string('company_id', 26);
            $table->string('branch_id', 26)->nullable();
            $table->string('name', 255)->nullable();
            $table->string('role', 40)->nullable();
            $table->string('driver_key', 255)->nullable();
            $table->string('transport', 40)->nullable();
            $table->text('address')->nullable();
            $table->integer('port')->nullable();
            $table->integer('paper_width_mm')->nullable();
            $table->integer('chars_per_line')->nullable();
            $table->boolean('has_cutter')->nullable();
            $table->boolean('has_drawer_kick')->nullable();
            $table->integer('drawer_kick_pin')->nullable();
            $table->integer('code_page')->nullable();
            $table->text('logo_path')->nullable();
            $table->boolean('is_default')->nullable();
            $table->unsignedBigInteger('row_version')->default(0);
            $table->dateTime('created_at')->nullable();
            $table->dateTime('updated_at')->nullable();
            $table->dateTime('deleted_at')->nullable();
            $table->dateTime('synced_at')->nullable();
            $table->unsignedBigInteger('sync_seq')->nullable();
            $table->json('extra')->nullable();

            $table->index(['company_id', 'updated_at'], 'printer_profiles_company_id_updated_at_index');
            $table->index(['company_id', 'branch_id'], 'printer_profiles_company_id_branch_id_index');
        });

        Schema::create('scale_calibration_logs', function (Blueprint $table) {
            $table->string('id', 26)->primary();
            $table->string('company_id', 26);
            $table->string('branch_id', 26)->nullable();
            $table->string('register_id', 26)->nullable();
            $table->dateTime('calibrated_on')->nullable();
            $table->string('engineer_name', 255)->nullable();
            $table->string('certificate_reference', 255)->nullable();
            $table->dateTime('expires_on')->nullable();
            $table->text('notes')->nullable();
            $table->unsignedBigInteger('row_version')->default(0);
            $table->dateTime('created_at')->nullable();
            $table->dateTime('updated_at')->nullable();
            $table->dateTime('deleted_at')->nullable();
            $table->dateTime('synced_at')->nullable();
            $table->unsignedBigInteger('sync_seq')->nullable();
            $table->json('extra')->nullable();

            $table->index(['company_id', 'updated_at'], 'scale_calibration_logs_company_id_updated_at_index');
            $table->index(['company_id', 'branch_id'], 'scale_calibration_logs_company_id_branch_id_index');
        });

        Schema::create('till_sync_conflicts', function (Blueprint $table) {
            $table->string('id', 26)->primary();
            $table->string('company_id', 26);
            $table->string('branch_id', 26)->nullable();
            $table->string('entity', 255)->nullable();
            $table->string('entity_id', 64)->nullable();
            $table->string('ownership', 40)->nullable();
            $table->bigInteger('hub_version')->nullable();
            $table->bigInteger('branch_version')->nullable();
            $table->dateTime('detected_at')->nullable();
            $table->string('resolution', 40)->nullable();
            $table->dateTime('resolved_at')->nullable();
            $table->string('resolved_by_user_id', 64)->nullable();
            $table->text('detail')->nullable();
            $table->unsignedBigInteger('row_version')->default(0);
            $table->dateTime('created_at')->nullable();
            $table->dateTime('updated_at')->nullable();
            $table->dateTime('deleted_at')->nullable();
            $table->dateTime('synced_at')->nullable();
            $table->unsignedBigInteger('sync_seq')->nullable();
            $table->json('extra')->nullable();

            $table->index(['company_id', 'updated_at'], 'till_sync_conflicts_company_id_updated_at_index');
            $table->index(['company_id', 'branch_id'], 'till_sync_conflicts_company_id_branch_id_index');
        });

        Schema::create('till_sync_states', function (Blueprint $table) {
            $table->string('id', 26)->primary();
            $table->string('company_id', 26);
            $table->string('branch_id', 26)->nullable();
            $table->bigInteger('last_pushed_seq')->nullable();
            $table->bigInteger('last_pulled_version')->nullable();
            $table->dateTime('last_success_at')->nullable();
            $table->dateTime('last_attempt_at')->nullable();
            $table->text('last_error')->nullable();
            $table->integer('pending_at_last_attempt')->nullable();
            $table->integer('consecutive_failures')->nullable();
            $table->unsignedBigInteger('row_version')->default(0);
            $table->dateTime('created_at')->nullable();
            $table->dateTime('updated_at')->nullable();
            $table->dateTime('deleted_at')->nullable();
            $table->dateTime('synced_at')->nullable();
            $table->unsignedBigInteger('sync_seq')->nullable();
            $table->json('extra')->nullable();

            $table->index(['company_id', 'updated_at'], 'till_sync_states_company_id_updated_at_index');
            $table->index(['company_id', 'branch_id'], 'till_sync_states_company_id_branch_id_index');
        });

        Schema::create('update_runs', function (Blueprint $table) {
            $table->string('id', 26)->primary();
            $table->string('company_id', 26);
            $table->string('branch_id', 26)->nullable();
            $table->string('register_id', 26)->nullable();
            $table->string('action', 40)->nullable();
            $table->string('route', 40)->nullable();
            $table->string('version', 255)->nullable();
            $table->string('from_version', 255)->nullable();
            $table->dateTime('at')->nullable();
            $table->boolean('is_success')->nullable();
            $table->text('detail')->nullable();
            $table->text('notes')->nullable();
            $table->string('user_id', 64)->nullable();
            $table->unsignedBigInteger('row_version')->default(0);
            $table->dateTime('created_at')->nullable();
            $table->dateTime('updated_at')->nullable();
            $table->dateTime('deleted_at')->nullable();
            $table->dateTime('synced_at')->nullable();
            $table->unsignedBigInteger('sync_seq')->nullable();
            $table->json('extra')->nullable();

            $table->index(['company_id', 'updated_at'], 'update_runs_company_id_updated_at_index');
            $table->index(['company_id', 'branch_id'], 'update_runs_company_id_branch_id_index');
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('update_runs');
        Schema::dropIfExists('till_sync_states');
        Schema::dropIfExists('till_sync_conflicts');
        Schema::dropIfExists('scale_calibration_logs');
        Schema::dropIfExists('printer_profiles');
        Schema::dropIfExists('print_jobs');
        Schema::dropIfExists('till_licence_add_on_trials');
        Schema::dropIfExists('till_licences');
        Schema::dropIfExists('import_jobs');
        Schema::dropIfExists('import_column_maps');
        Schema::dropIfExists('hardware_checks');
        Schema::dropIfExists('event_subscriptions');
        Schema::dropIfExists('compliance_licences');
        Schema::dropIfExists('branch_hours_overrides');
        Schema::dropIfExists('backup_runs');
        Schema::dropIfExists('alert_subscriptions');
        Schema::dropIfExists('exception_logs');
        Schema::dropIfExists('till_audit_logs');
    }
};
