<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

/**
 * Till entity store, group "promotions": PromotionRule, PromotionItem, PromotionCoupon, PromotionRedemption, CouponRedemption, SeasonalEvent, SeasonalEventUplift.
 *
 * @generated by `php artisan till:entities:generate` from docs/contracts/portal-api-v1.1
 * and app/Domain/TillData/definitions.php. Do not edit.
 */
return new class extends Migration
{
    public function up(): void
    {
        Schema::create('promotion_rules', function (Blueprint $table) {
            $table->string('id', 26)->primary();
            $table->string('company_id', 26);
            $table->string('name', 255)->nullable();
            $table->string('type', 40)->nullable();
            $table->string('scope', 40)->nullable();
            $table->string('target_id', 64)->nullable();
            $table->decimal('percent', 9, 4)->nullable();
            $table->decimal('amount_off', 12, 2)->nullable();
            $table->decimal('deal_price', 12, 2)->nullable();
            $table->integer('buy_quantity')->nullable();
            $table->integer('get_quantity')->nullable();
            $table->integer('min_quantity')->nullable();
            $table->integer('priority')->nullable();
            $table->boolean('allow_stack')->nullable();
            $table->boolean('is_exclusive')->nullable();
            $table->integer('max_redemptions_per_sale')->nullable();
            $table->integer('max_redemptions_total')->nullable();
            $table->integer('redemption_count')->nullable();
            $table->string('coupon_code', 255)->nullable();
            $table->boolean('requires_coupon')->nullable();
            $table->string('branch_id', 64)->nullable();
            $table->string('customer_group_id', 64)->nullable();
            $table->boolean('is_hfss_safe')->nullable();
            $table->date('effective_from')->nullable();
            $table->date('effective_to')->nullable();
            $table->string('seasonal_event_id', 64)->nullable();
            $table->text('days')->nullable();
            $table->time('time_from')->nullable();
            $table->time('time_to')->nullable();
            $table->boolean('is_active')->nullable();
            $table->unsignedBigInteger('row_version')->default(0);
            $table->dateTime('created_at')->nullable();
            $table->dateTime('updated_at')->nullable();
            $table->dateTime('deleted_at')->nullable();
            $table->unsignedBigInteger('hub_version')->nullable();
            $table->dateTime('hub_edited_at')->nullable();
            $table->dateTime('synced_at')->nullable();
            $table->unsignedBigInteger('sync_seq')->nullable();
            $table->json('extra')->nullable();

            $table->index(['company_id', 'updated_at'], 'promotion_rules_company_id_updated_at_index');
            $table->index(['company_id', 'branch_id'], 'promotion_rules_company_id_branch_id_index');
        });

        Schema::create('promotion_items', function (Blueprint $table) {
            $table->string('id', 26)->primary();
            $table->string('company_id', 26);
            $table->string('promotion_rule_id', 64)->nullable();
            $table->string('scope', 40)->nullable();
            $table->string('target_id', 64)->nullable();
            $table->integer('group_no')->nullable();
            $table->integer('quantity')->nullable();
            $table->boolean('is_excluded')->nullable();
            $table->unsignedBigInteger('row_version')->default(0);
            $table->dateTime('created_at')->nullable();
            $table->dateTime('updated_at')->nullable();
            $table->dateTime('deleted_at')->nullable();
            $table->unsignedBigInteger('hub_version')->nullable();
            $table->dateTime('hub_edited_at')->nullable();
            $table->dateTime('synced_at')->nullable();
            $table->unsignedBigInteger('sync_seq')->nullable();
            $table->json('extra')->nullable();

            $table->index(['company_id', 'updated_at'], 'promotion_items_company_id_updated_at_index');
            $table->index(['promotion_rule_id'], 'promotion_items_promotion_rule_id_index');
        });

        Schema::create('promotion_coupons', function (Blueprint $table) {
            $table->string('id', 26)->primary();
            $table->string('company_id', 26);
            $table->string('promotion_rule_id', 64)->nullable();
            $table->string('code', 255)->nullable();
            $table->integer('max_uses')->nullable();
            $table->integer('use_count')->nullable();
            $table->date('expires_on')->nullable();
            $table->boolean('is_active')->nullable();
            $table->unsignedBigInteger('row_version')->default(0);
            $table->dateTime('created_at')->nullable();
            $table->dateTime('updated_at')->nullable();
            $table->dateTime('deleted_at')->nullable();
            $table->unsignedBigInteger('hub_version')->nullable();
            $table->dateTime('hub_edited_at')->nullable();
            $table->dateTime('synced_at')->nullable();
            $table->unsignedBigInteger('sync_seq')->nullable();
            $table->json('extra')->nullable();

            $table->index(['company_id', 'updated_at'], 'promotion_coupons_company_id_updated_at_index');
            $table->index(['promotion_rule_id'], 'promotion_coupons_promotion_rule_id_index');
        });

        Schema::create('promotion_redemptions', function (Blueprint $table) {
            $table->string('id', 26)->primary();
            $table->string('company_id', 26);
            $table->string('branch_id', 26)->nullable();
            $table->string('register_id', 26)->nullable();
            $table->string('sale_id', 64)->nullable();
            $table->string('sale_line_id', 64)->nullable();
            $table->string('promotion_rule_id', 64)->nullable();
            $table->string('promotion_name', 255)->nullable();
            $table->string('type', 40)->nullable();
            $table->string('scope', 40)->nullable();
            $table->string('source', 40)->nullable();
            $table->decimal('amount_off', 12, 2)->nullable();
            $table->string('coupon_code', 255)->nullable();
            $table->string('user_id', 64)->nullable();
            $table->date('trading_date')->nullable();
            $table->unsignedBigInteger('row_version')->default(0);
            $table->dateTime('created_at')->nullable();
            $table->dateTime('updated_at')->nullable();
            $table->dateTime('deleted_at')->nullable();
            $table->dateTime('synced_at')->nullable();
            $table->unsignedBigInteger('sync_seq')->nullable();
            $table->json('extra')->nullable();

            $table->index(['company_id', 'updated_at'], 'promotion_redemptions_company_id_updated_at_index');
            $table->index(['company_id', 'branch_id'], 'promotion_redemptions_company_id_branch_id_index');
            $table->index(['company_id', 'branch_id', 'trading_date'], 'promotion_redemptions_company_id_branch_id_trading_date_index');
            $table->index(['sale_id'], 'promotion_redemptions_sale_id_index');
        });

        Schema::create('coupon_redemptions', function (Blueprint $table) {
            $table->string('id', 26)->primary();
            $table->string('company_id', 26);
            $table->string('branch_id', 26)->nullable();
            $table->string('scanned_code', 255)->nullable();
            $table->string('company_prefix', 255)->nullable();
            $table->string('offer_code', 255)->nullable();
            $table->decimal('face_value', 12, 2)->nullable();
            $table->string('product_id', 64)->nullable();
            $table->string('product_name', 255)->nullable();
            $table->string('sale_id', 64)->nullable();
            $table->string('user_id', 64)->nullable();
            $table->dateTime('at')->nullable();
            $table->dateTime('reclaimed_at')->nullable();
            $table->boolean('was_scanned')->nullable();
            $table->unsignedBigInteger('row_version')->default(0);
            $table->dateTime('created_at')->nullable();
            $table->dateTime('updated_at')->nullable();
            $table->dateTime('deleted_at')->nullable();
            $table->dateTime('synced_at')->nullable();
            $table->unsignedBigInteger('sync_seq')->nullable();
            $table->json('extra')->nullable();

            $table->index(['company_id', 'updated_at'], 'coupon_redemptions_company_id_updated_at_index');
            $table->index(['company_id', 'branch_id'], 'coupon_redemptions_company_id_branch_id_index');
            $table->index(['sale_id'], 'coupon_redemptions_sale_id_index');
        });

        Schema::create('seasonal_events', function (Blueprint $table) {
            $table->string('id', 26)->primary();
            $table->string('company_id', 26);
            $table->string('branch_id', 26)->nullable();
            $table->string('name', 255)->nullable();
            $table->string('kind', 40)->nullable();
            $table->date('starts_on')->nullable();
            $table->date('ends_on')->nullable();
            $table->string('nation', 255)->nullable();
            $table->text('notes')->nullable();
            $table->boolean('is_active')->nullable();
            $table->integer('days')->nullable();
            $table->unsignedBigInteger('row_version')->default(0);
            $table->dateTime('created_at')->nullable();
            $table->dateTime('updated_at')->nullable();
            $table->dateTime('deleted_at')->nullable();
            $table->dateTime('synced_at')->nullable();
            $table->unsignedBigInteger('sync_seq')->nullable();
            $table->json('extra')->nullable();

            $table->index(['company_id', 'updated_at'], 'seasonal_events_company_id_updated_at_index');
            $table->index(['company_id', 'branch_id'], 'seasonal_events_company_id_branch_id_index');
        });

        Schema::create('seasonal_event_uplifts', function (Blueprint $table) {
            $table->string('id', 26)->primary();
            $table->string('company_id', 26);
            $table->string('branch_id', 26)->nullable();
            $table->string('seasonal_event_id', 64)->nullable();
            $table->string('department_id', 64)->nullable();
            $table->string('department_name', 255)->nullable();
            $table->decimal('uplift_percent', 9, 4)->nullable();
            $table->boolean('is_learned')->nullable();
            $table->unsignedBigInteger('row_version')->default(0);
            $table->dateTime('created_at')->nullable();
            $table->dateTime('updated_at')->nullable();
            $table->dateTime('deleted_at')->nullable();
            $table->dateTime('synced_at')->nullable();
            $table->unsignedBigInteger('sync_seq')->nullable();
            $table->json('extra')->nullable();

            $table->index(['company_id', 'updated_at'], 'seasonal_event_uplifts_company_id_updated_at_index');
            $table->index(['company_id', 'branch_id'], 'seasonal_event_uplifts_company_id_branch_id_index');
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('seasonal_event_uplifts');
        Schema::dropIfExists('seasonal_events');
        Schema::dropIfExists('coupon_redemptions');
        Schema::dropIfExists('promotion_redemptions');
        Schema::dropIfExists('promotion_coupons');
        Schema::dropIfExists('promotion_items');
        Schema::dropIfExists('promotion_rules');
    }
};
