<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

/**
 * Till entity store, group "customers": Customer, Consent, CustomerTransaction, CustomerCorrection, CustomerOrder, CustomerOrderPayment, StoreCreditVoucher, VoucherTransaction, EReceiptLog.
 *
 * @generated by `php artisan till:entities:generate` from docs/contracts/portal-api-v1.1
 * and app/Domain/TillData/definitions.php. Do not edit.
 */
return new class extends Migration
{
    public function up(): void
    {
        Schema::create('customers', function (Blueprint $table) {
            $table->string('id', 26)->primary();
            $table->string('company_id', 26);
            $table->string('name', 255)->nullable();
            $table->string('phone', 255)->nullable();
            $table->string('email', 255)->nullable();
            $table->text('address')->nullable();
            $table->date('dob')->nullable();
            $table->string('card_no', 255)->nullable();
            $table->decimal('balance', 12, 2)->nullable();
            $table->integer('points')->nullable();
            $table->decimal('credit_limit', 12, 2)->nullable();
            $table->string('tier', 255)->nullable();
            $table->text('notes')->nullable();
            $table->boolean('is_active')->nullable();
            $table->dateTime('anonymised_at')->nullable();
            $table->unsignedBigInteger('row_version')->default(0);
            $table->dateTime('created_at')->nullable();
            $table->dateTime('updated_at')->nullable();
            $table->dateTime('deleted_at')->nullable();
            $table->unsignedBigInteger('hub_version')->nullable();
            $table->dateTime('hub_edited_at')->nullable();
            $table->dateTime('synced_at')->nullable();
            $table->unsignedBigInteger('sync_seq')->nullable();
            $table->json('extra')->nullable();

            $table->index(['company_id', 'updated_at'], 'customers_company_id_updated_at_index');
            $table->index(['company_id', 'card_no'], 'customers_company_id_card_no_index');
        });

        Schema::create('consents', function (Blueprint $table) {
            $table->string('id', 26)->primary();
            $table->string('company_id', 26);
            $table->string('branch_id', 26)->nullable();
            $table->string('customer_id', 64)->nullable();
            $table->string('channel', 40)->nullable();
            $table->boolean('given')->nullable();
            $table->string('source', 40)->nullable();
            $table->dateTime('at')->nullable();
            $table->dateTime('withdrawn_at')->nullable();
            $table->boolean('is_active')->nullable();
            $table->unsignedBigInteger('row_version')->default(0);
            $table->dateTime('created_at')->nullable();
            $table->dateTime('updated_at')->nullable();
            $table->dateTime('deleted_at')->nullable();
            $table->dateTime('synced_at')->nullable();
            $table->unsignedBigInteger('sync_seq')->nullable();
            $table->json('extra')->nullable();

            $table->index(['company_id', 'updated_at'], 'consents_company_id_updated_at_index');
            $table->index(['company_id', 'branch_id'], 'consents_company_id_branch_id_index');
            $table->index(['customer_id'], 'consents_customer_id_index');
        });

        Schema::create('customer_transactions', function (Blueprint $table) {
            $table->string('id', 26)->primary();
            $table->string('company_id', 26);
            $table->string('branch_id', 26)->nullable();
            $table->string('customer_id', 64)->nullable();
            $table->string('type', 40)->nullable();
            $table->decimal('amount', 12, 2)->nullable();
            $table->integer('points')->nullable();
            $table->string('sale_id', 64)->nullable();
            $table->decimal('balance_after', 12, 2)->nullable();
            $table->integer('points_after')->nullable();
            $table->string('user_id', 64)->nullable();
            $table->text('note')->nullable();
            $table->dateTime('at')->nullable();
            $table->unsignedBigInteger('row_version')->default(0);
            $table->dateTime('created_at')->nullable();
            $table->dateTime('updated_at')->nullable();
            $table->dateTime('deleted_at')->nullable();
            $table->dateTime('synced_at')->nullable();
            $table->unsignedBigInteger('sync_seq')->nullable();
            $table->json('extra')->nullable();

            $table->index(['company_id', 'updated_at'], 'customer_transactions_company_id_updated_at_index');
            $table->index(['company_id', 'branch_id'], 'customer_transactions_company_id_branch_id_index');
            $table->index(['company_id', 'customer_id', 'at'], 'customer_transactions_company_id_customer_id_at_index');
        });

        Schema::create('customer_corrections', function (Blueprint $table) {
            $table->string('id', 26)->primary();
            $table->string('company_id', 26);
            $table->string('branch_id', 26)->nullable();
            $table->string('register_id', 26)->nullable();
            $table->string('sale_id', 64)->nullable();
            $table->string('previous_customer_id', 64)->nullable();
            $table->string('new_customer_id', 64)->nullable();
            $table->string('user_id', 64)->nullable();
            $table->string('reason_id', 64)->nullable();
            $table->text('reason_text')->nullable();
            $table->string('approved_by', 255)->nullable();
            $table->string('idempotency_key', 255)->nullable();
            $table->dateTime('corrected_at')->nullable();
            $table->unsignedBigInteger('row_version')->default(0);
            $table->dateTime('created_at')->nullable();
            $table->dateTime('updated_at')->nullable();
            $table->dateTime('deleted_at')->nullable();
            $table->dateTime('synced_at')->nullable();
            $table->unsignedBigInteger('sync_seq')->nullable();
            $table->json('extra')->nullable();

            $table->index(['company_id', 'updated_at'], 'customer_corrections_company_id_updated_at_index');
            $table->index(['company_id', 'branch_id'], 'customer_corrections_company_id_branch_id_index');
        });

        Schema::create('customer_orders', function (Blueprint $table) {
            $table->string('id', 26)->primary();
            $table->string('company_id', 26);
            $table->string('branch_id', 26)->nullable();
            $table->string('reference', 255)->nullable();
            $table->string('token', 255)->nullable();
            $table->string('customer_name', 255)->nullable();
            $table->string('customer_phone', 255)->nullable();
            $table->string('customer_email', 255)->nullable();
            $table->string('status', 40)->nullable();
            $table->longText('lines_json')->nullable();
            $table->decimal('goods_total', 12, 2)->nullable();
            $table->decimal('paid_total', 12, 2)->nullable();
            $table->dateTime('due_date')->nullable();
            $table->dateTime('expires_at')->nullable();
            $table->string('created_by_user_id', 64)->nullable();
            $table->dateTime('ready_at')->nullable();
            $table->dateTime('notified_at')->nullable();
            $table->dateTime('collected_at')->nullable();
            $table->string('sale_id', 64)->nullable();
            $table->dateTime('cancelled_at')->nullable();
            $table->string('cancel_reason_id', 64)->nullable();
            $table->decimal('forfeited_amount', 12, 2)->nullable();
            $table->text('notes')->nullable();
            $table->string('idempotency_key', 255)->nullable();
            $table->unsignedBigInteger('row_version')->default(0);
            $table->dateTime('created_at')->nullable();
            $table->dateTime('updated_at')->nullable();
            $table->dateTime('deleted_at')->nullable();
            $table->dateTime('synced_at')->nullable();
            $table->unsignedBigInteger('sync_seq')->nullable();
            $table->json('extra')->nullable();

            $table->index(['company_id', 'updated_at'], 'customer_orders_company_id_updated_at_index');
            $table->index(['company_id', 'branch_id'], 'customer_orders_company_id_branch_id_index');
            $table->index(['company_id', 'branch_id', 'status'], 'customer_orders_company_id_branch_id_status_index');
            $table->index(['company_id', 'reference'], 'customer_orders_company_id_reference_index');
        });

        Schema::create('customer_order_payments', function (Blueprint $table) {
            $table->string('id', 26)->primary();
            $table->string('company_id', 26);
            $table->string('branch_id', 26)->nullable();
            $table->string('order_id', 64)->nullable();
            $table->string('sale_id', 64)->nullable();
            $table->string('kind', 40)->nullable();
            $table->decimal('amount', 12, 2)->nullable();
            $table->dateTime('at')->nullable();
            $table->string('user_id', 64)->nullable();
            $table->unsignedBigInteger('row_version')->default(0);
            $table->dateTime('created_at')->nullable();
            $table->dateTime('updated_at')->nullable();
            $table->dateTime('deleted_at')->nullable();
            $table->dateTime('synced_at')->nullable();
            $table->unsignedBigInteger('sync_seq')->nullable();
            $table->json('extra')->nullable();

            $table->index(['company_id', 'updated_at'], 'customer_order_payments_company_id_updated_at_index');
            $table->index(['company_id', 'branch_id'], 'customer_order_payments_company_id_branch_id_index');
            $table->index(['order_id'], 'customer_order_payments_order_id_index');
            $table->index(['sale_id'], 'customer_order_payments_sale_id_index');
        });

        Schema::create('store_credit_vouchers', function (Blueprint $table) {
            $table->string('id', 26)->primary();
            $table->string('company_id', 26);
            $table->string('branch_id', 26)->nullable();
            $table->string('barcode', 255)->nullable();
            $table->string('type', 40)->nullable();
            $table->decimal('amount', 12, 2)->nullable();
            $table->decimal('remaining', 12, 2)->nullable();
            $table->string('issued_sale_id', 64)->nullable();
            $table->string('issued_by_user_id', 64)->nullable();
            $table->dateTime('issued_at')->nullable();
            $table->dateTime('activated_at')->nullable();
            $table->dateTime('expires_at')->nullable();
            $table->boolean('is_active')->nullable();
            $table->dateTime('cancelled_at')->nullable();
            $table->unsignedBigInteger('row_version')->default(0);
            $table->dateTime('created_at')->nullable();
            $table->dateTime('updated_at')->nullable();
            $table->dateTime('deleted_at')->nullable();
            $table->dateTime('synced_at')->nullable();
            $table->unsignedBigInteger('sync_seq')->nullable();
            $table->json('extra')->nullable();

            $table->index(['company_id', 'updated_at'], 'store_credit_vouchers_company_id_updated_at_index');
            $table->index(['company_id', 'branch_id'], 'store_credit_vouchers_company_id_branch_id_index');
            $table->index(['company_id', 'barcode'], 'store_credit_vouchers_company_id_barcode_index');
        });

        Schema::create('voucher_transactions', function (Blueprint $table) {
            $table->string('id', 26)->primary();
            $table->string('company_id', 26);
            $table->string('branch_id', 26)->nullable();
            $table->string('voucher_id', 64)->nullable();
            $table->string('type', 40)->nullable();
            $table->decimal('amount', 12, 2)->nullable();
            $table->decimal('balance_after', 12, 2)->nullable();
            $table->string('sale_id', 64)->nullable();
            $table->string('user_id', 64)->nullable();
            $table->text('note')->nullable();
            $table->dateTime('at')->nullable();
            $table->unsignedBigInteger('row_version')->default(0);
            $table->dateTime('created_at')->nullable();
            $table->dateTime('updated_at')->nullable();
            $table->dateTime('deleted_at')->nullable();
            $table->dateTime('synced_at')->nullable();
            $table->unsignedBigInteger('sync_seq')->nullable();
            $table->json('extra')->nullable();

            $table->index(['company_id', 'updated_at'], 'voucher_transactions_company_id_updated_at_index');
            $table->index(['company_id', 'branch_id'], 'voucher_transactions_company_id_branch_id_index');
        });

        Schema::create('e_receipt_logs', function (Blueprint $table) {
            $table->string('id', 26)->primary();
            $table->string('company_id', 26);
            $table->string('branch_id', 26)->nullable();
            $table->string('sale_id', 64)->nullable();
            $table->string('channel', 40)->nullable();
            $table->text('address')->nullable();
            $table->string('status', 40)->nullable();
            $table->text('error')->nullable();
            $table->dateTime('sent_at')->nullable();
            $table->unsignedBigInteger('row_version')->default(0);
            $table->dateTime('created_at')->nullable();
            $table->dateTime('updated_at')->nullable();
            $table->dateTime('deleted_at')->nullable();
            $table->dateTime('synced_at')->nullable();
            $table->unsignedBigInteger('sync_seq')->nullable();
            $table->json('extra')->nullable();

            $table->index(['company_id', 'updated_at'], 'e_receipt_logs_company_id_updated_at_index');
            $table->index(['company_id', 'branch_id'], 'e_receipt_logs_company_id_branch_id_index');
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('e_receipt_logs');
        Schema::dropIfExists('voucher_transactions');
        Schema::dropIfExists('store_credit_vouchers');
        Schema::dropIfExists('customer_order_payments');
        Schema::dropIfExists('customer_orders');
        Schema::dropIfExists('customer_corrections');
        Schema::dropIfExists('customer_transactions');
        Schema::dropIfExists('consents');
        Schema::dropIfExists('customers');
    }
};
