<?php

namespace App\Domain\TillData\Generator;

use RuntimeException;

/**
 * Decides which migrations the current contract release needs, so migrations stay additive after deploy.
 *
 * database/till-schema.json records, per release, the till tables, columns and indexes its migrations made. The
 * current release (definitions.php `release`) gets at most two migrations: one creating the tables no earlier
 * release has, one adding the columns and indexes earlier releases' tables lack. Earlier releases' migrations are
 * never rewritten or deleted. The generator rewrites the current release's entry each run (deterministic), so the
 * next release sees this one as applied. A column whose definition changed cannot be expressed additively: the
 * generator stops and names it (write that alter migration by hand).
 */
final class MigrationPlanner
{
    public const LOCK = 'database/till-schema.json';

    /**
     * @param  array{name: string, migrationPrefix: string}  $release
     */
    public function __construct(private readonly MigrationWriter $writer, private readonly array $release) {}

    /**
     * @param  list<EntitySpec>  $entities  stored entities, in migration order
     * @param  array{releases?: list<array{release: string, migrations: list<string>, tables: array<string, array{columns: array<string, string>, indexes: array<string, list<string>>}>}>}  $lock
     * @return array<string, string> relative path => contents (migrations and the lock)
     */
    public function plan(array $entities, array $lock): array
    {
        $earlier = [];

        foreach ($lock['releases'] ?? [] as $release) {
            if ($release['release'] === $this->release['name']) {
                break;
            }

            $earlier[] = $release;
        }

        $applied = $this->applied($earlier);
        $new = [];
        $additions = [];
        $tables = [];
        $changed = [];

        foreach ($entities as $entity) {
            $columns = $this->writer->columns($entity);
            $indexes = $this->writer->indexes($entity);
            $had = $applied[$entity->table] ?? null;

            if ($had === null) {
                $new[] = $entity;
                $tables[$entity->table] = ['columns' => $columns, 'indexes' => $indexes];

                continue;
            }

            foreach ($columns as $column => $definition) {
                if (isset($had['columns'][$column]) && $had['columns'][$column] !== $definition) {
                    $changed[] = "{$entity->table}.{$column}: {$had['columns'][$column]} → {$definition}";
                }
            }

            $add = [
                'columns' => array_diff_key($columns, $had['columns']),
                'indexes' => array_diff_key($indexes, $had['indexes']),
            ];

            if ($add['columns'] !== [] || $add['indexes'] !== []) {
                $additions[$entity->table] = $add;
                $tables[$entity->table] = $add;
            }
        }

        if ($changed !== []) {
            throw new RuntimeException("These till columns changed definition since an applied release; additive migrations cannot change them:\n".implode("\n", $changed));
        }

        $slug = str_replace(['.', '-'], '_', $this->release['name']);
        $prefix = 'database/migrations/'.$this->release['migrationPrefix'];
        $files = [];

        if ($new !== []) {
            $files["{$prefix}00_create_till_{$slug}_tables.php"] = $this->writer->create("Till entity store, tables new in contract {$this->release['name']}", $new);
        }

        if ($additions !== []) {
            $files["{$prefix}01_add_till_{$slug}_columns.php"] = $this->writer->alter("Till entity store, columns and indexes new in contract {$this->release['name']}", $additions);
        }

        ksort($tables);
        $releases = $earlier;

        if ($tables !== []) {
            $releases[] = [
                'release' => $this->release['name'],
                'migrations' => array_map(basename(...), array_keys($files)),
                'tables' => $tables,
            ];
        }

        $files[self::LOCK] = json_encode([
            'about' => 'Generated by php artisan till:entities:generate. The till tables, columns and indexes each contract release\'s migrations made; the generator writes only what earlier releases lack. Do not edit.',
            'releases' => $releases,
        ], JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE | JSON_THROW_ON_ERROR)."\n";

        return $files;
    }

    /**
     * Migration files the current release may own (for stale-file cleanup).
     */
    public function currentGlob(string $basePath): string
    {
        return $basePath.'/database/migrations/'.$this->release['migrationPrefix'].'*_till_*.php';
    }

    /**
     * @param  list<array{release: string, migrations: list<string>, tables: array<string, array{columns: array<string, string>, indexes: array<string, list<string>>}>}>  $releases
     * @return array<string, array{columns: array<string, string>, indexes: array<string, list<string>>}>
     */
    private function applied(array $releases): array
    {
        $applied = [];

        foreach ($releases as $release) {
            foreach ($release['tables'] as $table => $schema) {
                $applied[$table] = [
                    'columns' => ($applied[$table]['columns'] ?? []) + $schema['columns'],
                    'indexes' => ($applied[$table]['indexes'] ?? []) + $schema['indexes'],
                ];
            }
        }

        return $applied;
    }
}
