<?php

namespace App\Domain\TillData\Generator;

use Illuminate\Support\Str;

/**
 * Small helpers that write PHP source the way Pint (Laravel preset) formats it, so generated files pass
 * `pint --test` untouched and regenerating is byte-for-byte stable.
 */
final class Php
{
    public const GENERATED_TAG = '@generated by `php artisan till:entities:generate`';

    /**
     * A scalar, null or flat list as a one-line PHP literal.
     *
     * @param  scalar|list<scalar>|array<string, scalar>|null  $value
     */
    public static function literal(mixed $value): string
    {
        return match (true) {
            $value === null => 'null',
            is_bool($value) => $value ? 'true' : 'false',
            is_int($value) => (string) $value,
            is_string($value) => "'".str_replace(['\\', "'"], ['\\\\', "\\'"], $value)."'",
            is_array($value) && array_is_list($value) => '['.implode(', ', array_map(self::literal(...), $value)).']',
            is_array($value) => '['.implode(', ', array_map(
                fn ($k, $v) => self::literal($k).' => '.self::literal($v),
                array_keys($value),
                $value,
            )).']',
            default => throw new \InvalidArgumentException('Unsupported literal.'),
        };
    }

    /**
     * `use` lines for fully-qualified class names, sorted like Pint's ordered_imports (alpha, case-insensitive).
     *
     * @param  list<string>  $classes
     */
    public static function imports(array $classes): string
    {
        $classes = array_values(array_unique($classes));
        usort($classes, fn (string $a, string $b) => strcasecmp(str_replace('\\', ' ', $a), str_replace('\\', ' ', $b)));

        return implode("\n", array_map(fn (string $class) => "use {$class};", $classes));
    }

    public static function caseName(string $value): string
    {
        return Str::studly($value);
    }
}
