<?php

namespace App\Domain\Billing\Data;

use App\Domain\Billing\Enums\InvoiceStatus;
use App\Domain\Billing\Models\Invoice;
use App\Domain\Billing\Models\InvoiceLine;
use App\Domain\Billing\Models\PaymentAllocation;
use App\Domain\Billing\Support\BillingDates;
use App\Domain\Billing\Support\BillingFormat;
use App\Domain\Billing\Support\BillingMailer;
use App\Domain\Shared\Models\AuditLog;
use App\Domain\Shared\Support\Money;
use App\Domain\Tenancy\Data\TenantActivity;
use Carbon\CarbonImmutable;

/**
 * Invoice rows and detail for the admin screens. Money comes formatted ("£1,234.50") plus the raw decimal
 * string where the UI needs to calculate (payment dialog).
 */
final class InvoiceData
{
    /**
     * @return array<string, mixed>
     */
    public static function row(Invoice $invoice, ?CarbonImmutable $now = null): array
    {
        $today = BillingDates::today($now);
        $daysOverdue = $invoice->isOpen() && $invoice->due_date !== null && $invoice->due_date->lessThan($today)
            ? (int) $invoice->due_date->diffInDays($today)
            : 0;

        return [
            'id' => $invoice->id,
            'number' => $invoice->number,
            'displayNumber' => $invoice->displayNumber(),
            'status' => $invoice->status->value,
            'statusLabel' => $invoice->status->label(),
            'company' => ['id' => $invoice->company_id, 'name' => $invoice->company->name ?? 'Deleted business'],
            'period' => BillingDates::range($invoice->period_start, $invoice->period_end),
            'periodStart' => $invoice->period_start->format('Y-m-d'),
            'periodEnd' => $invoice->period_end->format('Y-m-d'),
            'issueDate' => $invoice->issue_date?->format('Y-m-d'),
            'dueDate' => $invoice->due_date?->format('Y-m-d'),
            'total' => BillingFormat::money($invoice->total),
            'balance' => BillingFormat::money($invoice->balance),
            'balanceRaw' => $invoice->balance,
            'isOpen' => $invoice->isOpen(),
            'daysOverdue' => $daysOverdue,
            'autoGenerated' => $invoice->auto_generated,
        ];
    }

    /**
     * @return array<string, mixed>
     */
    public static function detail(Invoice $invoice, bool $canManage, CarbonImmutable $now): array
    {
        $invoice->loadMissing(['company', 'lines.licence', 'allAllocations.payment', 'creditNotes', 'replaces']);
        $replacedBy = Invoice::withoutCompanyScope()->where('replaces_invoice_id', $invoice->id)->first(['id', 'number', 'status']);
        $status = $invoice->status;
        $company = $invoice->company;

        return self::row($invoice, $now) + [
            'document' => InvoiceDocument::for($invoice),
            'vatRate' => $invoice->vat_rate,
            'notes' => $invoice->notes,
            'cycle' => $invoice->cycle->value,
            'prorated' => $invoice->prorated,
            'companyStatus' => $company?->status->value,
            'amountPaid' => BillingFormat::money($invoice->amount_paid),
            'amountCredited' => BillingFormat::money($invoice->amount_credited),
            'issuedAt' => $invoice->issued_at?->toIso8601String(),
            'paidAt' => $invoice->paid_at?->toIso8601String(),
            'voidedAt' => $invoice->voided_at?->toIso8601String(),
            'voidReason' => $invoice->void_reason,
            'lastSentAt' => $invoice->last_sent_at?->toIso8601String(),
            'sentCount' => $invoice->sent_count,
            'recipients' => $company !== null ? array_keys(app(BillingMailer::class)->invoiceRecipients($company)) : [],
            'lines' => $invoice->lines->map(fn (InvoiceLine $line) => [
                'id' => $line->id,
                'description' => $line->description,
                'quantity' => BillingFormat::quantity($line->quantity),
                'unitPrice' => $line->unit_price,
                'hasLicence' => $line->licence_id !== null,
                'licenceId' => $line->licence_id,
            ])->values()->all(),
            'payments' => $invoice->allAllocations->map(fn (PaymentAllocation $allocation) => [
                'id' => $allocation->id,
                'paymentId' => $allocation->payment_id,
                'number' => $allocation->payment?->number,
                'method' => $allocation->payment?->method->label(),
                'receivedAt' => $allocation->payment?->received_at->toIso8601String(),
                'amount' => BillingFormat::money($allocation->amount),
                'released' => $allocation->released_at !== null,
            ])->values()->all(),
            'replaces' => $invoice->replaces === null ? null : ['id' => $invoice->replaces->id, 'number' => $invoice->replaces->number],
            'replacedBy' => $replacedBy === null ? null : ['id' => $replacedBy->id, 'number' => $replacedBy->displayNumber()],
            'can' => [
                'manage' => $canManage,
                'edit' => $canManage && $status === InvoiceStatus::Draft,
                'issue' => $canManage && $status === InvoiceStatus::Draft && $invoice->lines->isNotEmpty(),
                'delete' => $canManage && $status === InvoiceStatus::Draft,
                'send' => $canManage && ! in_array($status, [InvoiceStatus::Draft, InvoiceStatus::Void], true),
                'recordPayment' => $canManage && $invoice->isOpen(),
                'credit' => $canManage && $invoice->isOpen(),
                'void' => $canManage && $invoice->isOpen(),
            ],
            'maxCredit' => $invoice->isOpen() ? $invoice->balance : '0.00',
            'hasPayments' => ! Money::isZero($invoice->amount_paid),
        ];
    }

    /**
     * The invoice's audit trail (newest first), as readable rows.
     *
     * @return list<array<string, mixed>>
     */
    public static function activity(Invoice $invoice): array
    {
        $entries = AuditLog::query()
            ->where('subject_type', $invoice->getMorphClass())->where('subject_id', $invoice->id)
            ->latest('created_at')->latest('id')->limit(50)->get();
        $presenter = new TenantActivity($entries);

        return $entries->map(fn (AuditLog $entry) => $presenter->row($entry))->values()->all();
    }
}
